// =====================================================================
// Banco de datos curiosos para el welcome-screen de Trivials Wars
// 100+ facts en categorías diversas, generados por scripts/gen-facts.py
// =====================================================================

export interface FunFact {
  id: number
  emoji: string
  category: string
  color: string
  title: string
  description: string
}

// Mapa de colores por categoría (18 categorías)
export const FACT_COLOR: Record<string, string> = {
  ciencia: "#00E5FF",
  historia: "#FFEA00",
  cultura: "#FF4D6D",
  naturaleza: "#39FF14",
  geografia: "#7DD3FC",
  videojuegos: "#a855f7",
  deporte: "#f97316",
  espacio: "#C084FC",
  arte: "#F472B6",
  musica: "#34D399",
  tecnologia: "#60A5FA",
  idiomas: "#FBBF24",
  ocean: "#22D3EE",
  cuerpo: "#FB7185",
  inventos: "#A78BFA",
  literatura: "#FCD34D",
  mitologia: "#F87171",
  mariposas: "#F59E0B",
}

export const FUN_FACTS: FunFact[] = [
  {
    id: 1,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El pulpo tiene tres corazones",
    description: "Dos corazones bombean sangre a las branquias y el tercero al resto del cuerpo. Cuando nada, el corazón principal se detiene, por eso prefieren caminar.",
  },
  {
    id: 2,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El cerebro usa el 20% de tu energía",
    description: "Pesa apenas 1.4 kg pero consume el 20% del oxígeno y calorías. Genera energía suficiente para encender una bombilla de bajo consumo.",
  },
  {
    id: 3,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El agua puede hervir y congelarse a la vez",
    description: "En el 'punto triple' (0.01°C y 611 Pa) el agua existe simultáneamente como sólido, líquido y gas. Es así como se calibran los termómetros exactos.",
  },
  {
    id: 4,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "Los diamantes llueven en Júpiter",
    description: "El relámpago convierte el metano en carbono sólido que, al caer, se comprime y forma diamantes. Pero se derriten antes de llegar al núcleo.",
  },
  {
    id: 5,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El helio líquido sube por las paredes",
    description: "A -271°C forma una película que trepa por las paredes de cualquier recipiente y se escurre hacia afuera, desafiando la gravedad. Es un 'superfluido' sin viscosidad.",
  },
  {
    id: 6,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El átomo es 99.9999% espacio vacío",
    description: "Si el núcleo fuera una canica en el centro de un estadio, los electrones estarían en las gradas. Toda la 'masa' está concentrada en un punto minúsculo.",
  },
  {
    id: 7,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "Tu ADN llegaría al Sol y volvería",
    description: "Estirado, el ADN de todas tus células daría 200 mil millones de km: ida y vuelta al Sol 600 veces. Es la molécula más larga del universo conocido.",
  },
  {
    id: 8,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "La lava es tan caliente como la superficie del Sol",
    description: "La lava fresca alcanza 1,200°C. La superficie del Sol está a 5,500°C, pero el interior de la Tierra llega a 6,000°C: más caliente que el Sol exterior.",
  },
  {
    id: 9,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "Un tornado puede girar a 480 km/h",
    description: "El récord de velocidad de vientos en un tornado es de 484 km/h (Oklahoma, 1999). Son los fenómenos más violentos del planeta.",
  },
  {
    id: 10,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El oro viene de estrellas muertas",
    description: "El oro no se forma en la Tierra. Lo crean las explosiones de estrellas de neutrones (kilonovas) hace miles de millones de años, antes de que existiera el Sol.",
  },
  {
    id: 11,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "Cada copo de nieve es único",
    description: "Ningún copo de nieve en la historia ha sido idéntico a otro. La combinación de temperatura, humedad y trayectoria genera formas infinitas.",
  },
  {
    id: 12,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El sonido viaja 4x más rápido en agua",
    description: "En aire: 343 m/s. En agua: 1,500 m/s. Por eso las ballenas pueden comunicarse a cientos de kilómetros bajo el mar.",
  },
  {
    id: 13,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "Un rayo tiene 5 veces la temperatura del Sol",
    description: "El aire alrededor de un rayo alcanza 30,000°C. La superficie del Sol está a 5,500°C. El rayo es la cosa más caliente que existe naturalmente en la Tierra.",
  },
  {
    id: 14,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "La Tierra tiene campo magnético desde hace 4,000M años",
    description: "Sin él, el viento solar habría arrancado nuestra atmósfera hace eones, como le pasó a Marte. Es lo que permite la vida en la superficie.",
  },
  {
    id: 15,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "Un microbio sobrevive en el espacio exterior",
    description: "Tardigrades ('osos de agua') soportan radiación, vacío y temperaturas de -271°C a 150°C. Son los únicos animales que sobrevivirían a un evento de extinción total.",
  },
  {
    id: 16,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "La Gran Muralla China mide +21,000 km",
    description: "No es una sola pared, sino una red de tramos construidos a lo largo de 2,000 años. Se dice que es visible desde la órbita baja terrestre.",
  },
  {
    id: 17,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "Los romanos usaban orina para lavar ropa",
    description: "El amoníaco de la orina era un detergente natural. El emperador Vespasiano incluso cobraba impuestos por la recolección de orina pública.",
  },
  {
    id: 18,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "La Biblioteca de Alejandría tuvo 700,000 rollos",
    description: "Su pérdida retrasó el avance científico 1,000 años. Hipatia, su última gran científica, fue asesinada en el 415 d.C. por una multitud enfurecida.",
  },
  {
    id: 19,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "La guerra más corta duró 38 minutos",
    description: "Guerra Anglo-Zanzíbar (1896): el sultán Khalid se negó a rendirse, los británicos bombardearon su palacio, y todo terminó antes de la hora.",
  },
  {
    id: 20,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "Cleopatra vivió más cerca del iPhone que de las pirámides",
    description: "Las pirámides se construyeron hace 4,500 años. Cleopatra vivió hace 2,000 años. El primer iPhone salió hace 18. Para ella, las pirámides eran 'antigüedades'.",
  },
  {
    id: 21,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "Los vikingos llegaron a América 500 años antes que Colón",
    description: "Leif Erikson pisó Terranova alrededor del año 1000 d.C. Colón llegó en 1492. Los vikingos no se quedaron porque los pueblos originarios los expulsaron.",
  },
  {
    id: 22,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "El Imperio Romano duró 1,500 años",
    description: "Desde la fundación (753 a.C.) hasta la caída de Constantinopla (1453). Es el imperio más longevo de la historia occidental.",
  },
  {
    id: 23,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "La escritura más antigua tiene 5,500 años",
    description: "Los sumerios inventaron la cuneiforme en Mesopotamia hacia el 3,500 a.C. Para escribir, usaban una caña sobre tablillas de arcilla húmeda.",
  },
  {
    id: 24,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "Las pirámides se construyeron con agua, no esclavos",
    description: "Estudios recientes muestran que los constructores eran trabajadores pagados y alimentados, y que usaban canales para acercar las piedras en barcazas.",
  },
  {
    id: 25,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "El Imperio Mongol fue el más grande de la historia",
    description: "Bajo Gengis Khan y sus sucesores, abarcó 24 millones de km² (16% de la tierra emergida). Conectó Europa y Asia por primera vez por vía terrestre.",
  },
  {
    id: 26,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "La Tierra rotó más rápido en 2020",
    description: "El 19 de julio de 2020 fue el día más corto jamás medido: 1.46 ms menos de 24 horas. El clima, los océanos y el núcleo afectan la rotación planetaria.",
  },
  {
    id: 27,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "Saturno flotaría en agua",
    description: "Su densidad es de 0.687 g/cm³, menor que la del agua (1). Si existiera una bañera suficientemente grande, el planeta entero flotaría en su superficie.",
  },
  {
    id: 28,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "Hay más estrellas que granos de arena",
    description: "El universo observable tiene ~10²⁴ estrellas. Todas las playas de la Tierra suman ~10¹⁹ granos de arena. Por cada grano, hay 100,000 estrellas.",
  },
  {
    id: 29,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "La luz del Sol tarda 8 minutos en llegarnos",
    description: "8 minutos y 20 segundos. Cuando miras el Sol, lo ves como era en el pasado. Si desapareciera de golpe, no lo sabríamos por 8 minutos.",
  },
  {
    id: 30,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "La Luna se aleja 3.8 cm al año",
    description: "Cada año la Luna está más lejos de la Tierra. En 600 millones de años no habrá más eclipses totales de Sol visibles desde aquí.",
  },
  {
    id: 31,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "Voyager 1 sigue viajando después de 47 años",
    description: "Lanzada en 1977, es el objeto más lejano creado por el ser humano. Salió del sistema solar en 2012 y viaja a 17 km/s hacia la estrella AC+79 3888.",
  },
  {
    id: 32,
    emoji: "⭐",
    category: "Espacio",
    color: "#C084FC",
    title: "Una cucharadita de estrella de neutrones pesa 6 mil millones de toneladas",
    description: "Son tan densas que un cubito de azúcar de su material pesaría tanto como una montaña. Es la materia en su estado más extremo del universo.",
  },
  {
    id: 33,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "La Vía Láctea y Andrómeda chocarán en 4,500M años",
    description: "Se acercan a 110 km/s. La fusión creará una nueva galaxia elíptica llamada 'Milkdromeda'. Probablemente el Sol sobreviva al impacto.",
  },
  {
    id: 34,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "Hay un agujero negro en el centro de la Vía Láctea",
    description: "Se llama Sagitario A* y tiene 4.3 millones de masas solares. Es invisible, pero vemos las órbitas de estrellas girando alrededor de 'la nada'.",
  },
  {
    id: 35,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "La ISS orbita la Tierra cada 90 minutos",
    description: "A 27,600 km/h y 400 km de altura. Los astronautas ven 16 amaneceres y 16 atardeceres cada día terrestre.",
  },
  {
    id: 36,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "Los cometas tienen dos colas, no una",
    description: "Una cola de polvo (curva, amarillenta) y una cola de iones (recta, azulada). Ambas apuntan en dirección contraria al Sol.",
  },
  {
    id: 37,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "Marte tiene la montaña más alta del sistema solar",
    description: "El Olympus Mons mide 22 km (casi 3 Everests). Su base es del tamaño de Francia. Es un volcán extinto hace millones de años.",
  },
  {
    id: 38,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Las hormigas pueden cargar 50x su peso",
    description: "Si un humano tuviera esa fuerza proporcional, levantaría un automóvil. Existen más de 12,000 especies de hormigas en el planeta.",
  },
  {
    id: 39,
    emoji: "",
    category: "Naturaleza",
    color: "#F59E0B",
    title: "La mariposa monarca viaja 4,500 km",
    description: "Cada otoño migra de Canadá a México, pero la hace en 4 generaciones: las que llegan nunca han estado allí, pero saben exactamente dónde ir.",
  },
  {
    id: 40,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "El panda pasa 14 horas al día comiendo",
    description: "Su dieta es 99% bambú, pero su estómago es de carnívoro. Para nutrirse debe ingerir entre 12 y 38 kg diarios de bambú.",
  },
  {
    id: 41,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Un caracol puede dormir 3 años seguidos",
    description: "Si el clima es muy seco, entran en estivación: sellan su concha y esperan. Algunos han sobrevivido así 3 años pegados a una pared.",
  },
  {
    id: 42,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Una abeja produce 1/12 de cucharadita de miel en su vida",
    description: "Para 1 kg de miel, las abejas de una colmena recorren el equivalente a 3 vueltas a la Tierra visitando flores.",
  },
  {
    id: 43,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Los pulpos tienen sangre azul",
    description: "Su hemocianina (en lugar de hemoglobina) transporta oxígeno usando cobre en vez de hierro. Por eso su sangre es azul, no roja.",
  },
  {
    id: 44,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "La jirafa tiene el cuello más largo pero 7 vértebras",
    description: "Las mismas que los humanos. Cada vértebra mide hasta 28 cm. Su corazón pesa 11 kg para bombear sangre a 2.5 m de altura.",
  },
  {
    id: 45,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Un león ruge a 114 decibelios",
    description: "Se puede escuchar a 8 km de distancia. Es el rugido más potente de cualquier felino, usado para marcar territorio y llamar a la manada.",
  },
  {
    id: 46,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Un cactus puede vivir 200 años",
    description: "El saguaro del desierto de Sonora crece solo 2 cm en sus primeros 10 años. A los 75 da su primera flor. Algunos superan los 15 metros.",
  },
  {
    id: 47,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Los hongos están más cerca de los animales que de las plantas",
    description: "Compartimos un ancestro común de hace 1,500 millones de años. Los hongos no fotosintetizan: 'comen' como nosotros, absorbiendo materia orgánica.",
  },
  {
    id: 48,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "La ballena azul es el animal más grande jamás existente",
    description: "Mide hasta 30 m y pesa 180 toneladas. Su corazón es del tamaño de un coche pequeño y su lengua pesa tanto como un elefante.",
  },
  {
    id: 49,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "Los tiburones existían antes que los árboles",
    description: "Aparecieron hace 400 millones de años; los árboles aparecieron hace 350 millones. Sobrevivieron a 4 extinciones masivas sin cambiar casi su diseño.",
  },
  {
    id: 50,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "Las medusas Turritopsis son biológicamente inmortales",
    description: "Pueden revertir su ciclo vital y empezar de nuevo. En teoría, podrían vivir para siempre... si no se las comen o enferman.",
  },
  {
    id: 51,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "La Gran Barrera de Coral es visible desde el espacio",
    description: "Es la estructura viva más grande del planeta: 2,300 km de largo, formada por miles de millones de pólipos diminutos. Lleva creciendo 20,000 años.",
  },
  {
    id: 52,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "Los delfines tienen 'nombres' propios",
    description: "Cada delfín tiene un silbido único que lo identifica. Otros delfines lo usan para 'llamarlo', como un nombre humano.",
  },
  {
    id: 53,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "El 95% del océano está inexplorado",
    description: "Conocemos mejor la superficie de Marte que el fondo del mar. La fosa de Mariana (11 km) fue visitada por primera vez en 1960.",
  },
  {
    id: 54,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "Los cangrejos ermitaños hacen fila para intercambiar conchas",
    description: "Cuando encuentran una concha grande vacía, se organizan por tamaño y la pasan al siguiente que calce. Es una verdadera cadena de trueque.",
  },
  {
    id: 55,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "El pez payaso puede cambiar de sexo",
    description: "Si la hembra dominante muere, el macho más grande se convierte en hembra. Son hermafroditas secuenciales: nacen machos, algunos se vuelven hembras.",
  },
  {
    id: 56,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "El Everest crece 4 mm cada año",
    description: "La colisión de placas tectónicas entre India y Asia empuja la montaña hacia arriba. Hace 50 millones de años esta zona estaba bajo el mar.",
  },
  {
    id: 57,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "La Estatua de la Libertad fue un regalo francés",
    description: "Inaugurada en 1886, fue diseñada por Frédéric Auguste Bartholdi con estructura interna de Gustave Eiffel. Su color verde es por la oxidación natural del cobre.",
  },
  {
    id: 58,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "El desierto del Sahara fue un bosque hace 6,000 años",
    description: "Hubo monzones que lo cubrieron de vegetación y lagos. El cambio en la órbita terrestre desplazó las lluvias y lo convirtió en desierto.",
  },
  {
    id: 59,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "Rusia tiene 11 zonas horarias",
    description: "Es el país más grande del mundo: 17 millones de km². Cuando amanece en Moscú, en Vladivostok ya está oscureciendo.",
  },
  {
    id: 60,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "La Antártida es el desierto más grande del mundo",
    description: "Aunque está cubierta de hielo, recibe menos de 200 mm de precipitación anual. Es técnicamente un desierto polar más seco que el Sahara.",
  },
  {
    id: 61,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "Islandia crece 2 cm al año",
    description: "Está sobre la dorsal mesoatlántica: Norteamérica y Eurasia se separan, e Islandia se 'estira'. En 10M años será el doble de ancha.",
  },
  {
    id: 62,
    emoji: "",
    category: "Cuerpo humano",
    color: "#FB7185",
    title: "Tus vasos sanguíneos darían 2.5 vueltas a la Tierra",
    description: "Puestos en línea miden ~100,000 km. El corazón bombea 7,500 litros de sangre al día a través de esta red, sin parar ni un segundo.",
  },
  {
    id: 63,
    emoji: "",
    category: "Cuerpo humano",
    color: "#FB7185",
    title: "El ojo humano distingue 10 millones de colores",
    description: "Tenemos ~6 millones de conos (color) y 120 millones de bastones (luz). Las mujeres, en promedio, distinguen más tonos que los hombres.",
  },
  {
    id: 64,
    emoji: "",
    category: "Cuerpo humano",
    color: "#FB7185",
    title: "El esmalte dental es más duro que el acero",
    description: "Es la sustancia más dura del cuerpo humano: 5 en la escala Mohs. Pero no puede regenerarse, así que cuidarlo es para toda la vida.",
  },
  {
    id: 65,
    emoji: "",
    category: "Cuerpo humano",
    color: "#FB7185",
    title: "El fémur soporta 30x tu peso",
    description: "El hueso más largo y fuerte del cuerpo. En compresión puede aguantar hasta 1,800 kg. Es más resistente que el hormigón armado, peso por peso.",
  },
  {
    id: 66,
    emoji: "",
    category: "Cuerpo humano",
    color: "#FB7185",
    title: "Los alvéolos pulmonares tendrían 70 m²",
    description: "Si extendieras todos los sacos de aire de tus pulmones, cubrirían la mitad de una cancha de tenis. Es el área de intercambio de oxígeno.",
  },
  {
    id: 67,
    emoji: "",
    category: "Cuerpo humano",
    color: "#FB7185",
    title: "El cerebro genera 20 W de potencia",
    description: "Suficiente para encender una bombilla de bajo consumo. Funciona con la misma energía que un pequeño portátil, pero procesa billones de señales por segundo.",
  },
  {
    id: 68,
    emoji: "",
    category: "Cuerpo humano",
    color: "#FB7185",
    title: "El oído nunca deja de escuchar",
    description: "Aunque duermas, el cerebro sigue procesando sonidos. Por eso el ruido interrumpe el sueño, pero los sonidos familiares pueden no hacerlo.",
  },
  {
    id: 69,
    emoji: "",
    category: "Cuerpo humano",
    color: "#FB7185",
    title: "Tu lengua tiene 10,000 papilas gustativas",
    description: "Pero se renuevan cada 10-14 días. Por eso una quemadura en la lengua se cura rápido. Cada papila tiene 50-100 células receptoras de sabor.",
  },
  {
    id: 70,
    emoji: "",
    category: "Tecnología",
    color: "#60A5FA",
    title: "El primer SMS decía 'Merry Christmas'",
    description: "Neil Papworth lo envió el 3 de diciembre de 1992 desde un PC a un móvil Orbitel 901. Nadie imaginaba que iniciaría una revolución de mensajería.",
  },
  {
    id: 71,
    emoji: "",
    category: "Tecnología",
    color: "#60A5FA",
    title: "Tu smartphone es más potente que el Apollo 11",
    description: "El iPhone moderno tiene ~100,000x la memoria y procesadores millones de veces más rápidos. El Apollo 11 llevó al hombre a la Luna con apenas 4 KB de RAM.",
  },
  {
    id: 72,
    emoji: "",
    category: "Tecnología",
    color: "#60A5FA",
    title: "La primera webcam vigilaba una cafetera",
    description: "En la Universidad de Cambridge (1991) querían saber si quedaba café sin subir las escaleras. Conectaron una cámara y nació la primera webcam del mundo.",
  },
  {
    id: 73,
    emoji: "",
    category: "Tecnología",
    color: "#60A5FA",
    title: "El primer disco duro pesaba 1 tonelada",
    description: "IBM RAMAC (1956) almacenaba 5 MB y ocupaba el tamaño de dos armarios. Hoy un microSD del tamaño de una uña guarda 1 TB: 200,000 veces más.",
  },
  {
    id: 74,
    emoji: "",
    category: "Tecnología",
    color: "#60A5FA",
    title: "Hay más móviles que personas en la Tierra",
    description: "8,500 millones de líneas móviles vs 8,000 millones de personas. El país con más móviles por habitante es Hong Kong (2.4 por persona).",
  },
  {
    id: 75,
    emoji: "",
    category: "Tecnología",
    color: "#60A5FA",
    title: "El primer joystick era un bote de jabón",
    description: "Ralph Baer, inventor de la consola Magnavox Odyssey (1972), usó un bote vacío de jabón para crear el primer control de videojuegos casero.",
  },
  {
    id: 76,
    emoji: "",
    category: "Tecnología",
    color: "#60A5FA",
    title: "El GPS se basa en la teoría de Einstein",
    description: "Sin la corrección de la relatividad (tiempo corre más lento en órbita), el GPS fallaría 10 km por día. Einstein hace que Google Maps funcione.",
  },
  {
    id: 77,
    emoji: "",
    category: "Tecnología",
    color: "#60A5FA",
    title: "El primer programador fue mujer",
    description: "Ada Lovelace escribió el primer algoritmo en 1843, para la 'máquina analítica' de Babbage que nunca se construyó. Previó que las computadoras harían más que cálculos.",
  },
  {
    id: 78,
    emoji: "",
    category: "Arte",
    color: "#F472B6",
    title: "Van Gogh vendió un solo cuadro en vida",
    description: "'La viña roja' se vendió por 400 francos en 1890, meses antes de su muerte. Hoy sus obras superan los 100 millones de dólares.",
  },
  {
    id: 79,
    emoji: "",
    category: "Música",
    color: "#34D399",
    title: "Mozart compuso a los 5 años",
    description: "Su primera pieza, un minueto para clavecín, la escribió a los 5 años. A los 12 ya había compuesto su primera ópera. Murió a los 35 con más de 600 obras.",
  },
  {
    id: 80,
    emoji: "",
    category: "Arte",
    color: "#F472B6",
    title: "La Mona Lisa no tenía cejas",
    description: "Análisis digitales muestran que Da Vinci sí pintó cejas, pero se borraron por restauraciones agresivas. En el siglo XVI se usaban cejas depiladas como símbolo de belleza.",
  },
  {
    id: 81,
    emoji: "",
    category: "Música",
    color: "#34D399",
    title: "La guitarra eléctrica se inventó en 1932",
    description: "Gibson lanzó la ES-150 con pickup magnético. Hasta entonces, las guitarras no se escuchaban en orquestas. Esto cambió el jazz, el blues y el rock para siempre.",
  },
  {
    id: 82,
    emoji: "",
    category: "Música",
    color: "#34D399",
    title: "Beethoven compuso sordo",
    description: "Empezó a perder el oído a los 26 años. La 'Novena Sinfonía' la escribió completamente sordo. La dirigió sin escuchar una sola nota.",
  },
  {
    id: 83,
    emoji: "",
    category: "Arte",
    color: "#F472B6",
    title: "El David de Miguel Ángel mide 5.17 m",
    description: "Lo esculpió entre 1501 y 1504 a los 26 años, de un bloque de mármol abandonado por otros escultores. Tiene manos desproporcionadas para sugerir fuerza.",
  },
  {
    id: 84,
    emoji: "",
    category: "Idiomas",
    color: "#FBBF24",
    title: "Existen +7,000 idiomas en el mundo",
    description: "Pero el 40% está en peligro de extinción. El papamiento, el silbo gomero y el pirahã son algunos de los más fascinantes del planeta.",
  },
  {
    id: 85,
    emoji: "",
    category: "Literatura",
    color: "#FCD34D",
    title: "El Quijote se tradujo a +50 idiomas",
    description: "Publicada en 1605, es la segunda obra más traducida de la historia después de la Biblia. Cervantes murió el mismo día que Shakespeare: 23 de abril de 1616.",
  },
  {
    id: 86,
    emoji: "",
    category: "Idiomas",
    color: "#FBBF24",
    title: "El coreano tiene un alfabeto científico",
    description: "Hangul fue creado en 1443 por el rey Sejong. Cada letra representa la forma que hace la boca al pronunciarla. Es considerado el alfabeto más lógico del mundo.",
  },
  {
    id: 87,
    emoji: "",
    category: "Literatura",
    color: "#FCD34D",
    title: "El libro más largo del mundo tiene 17,000 páginas",
    description: "'À la recherche du temps perdu' de Proust. En español son 3,000 páginas. Tiene una sola frase de 958 palabras sobre un dormitorio.",
  },
  {
    id: 88,
    emoji: "",
    category: "Idiomas",
    color: "#FBBF24",
    title: "El esperanto se creó para unir el mundo",
    description: "L.L. Zamenhof lo publicó en 1887 como lengua neutral internacional. Hoy lo hablan ~2 millones de personas, pero nunca desbancó al inglés.",
  },
  {
    id: 89,
    emoji: "",
    category: "Inventos",
    color: "#A78BFA",
    title: "La bombilla led dura 25,000 horas",
    description: "Frente a las 1,200 de una incandescente. El primer LED visible lo creó Nick Holonyak en 1962; hoy iluminan el 60% de los hogares del mundo.",
  },
  {
    id: 90,
    emoji: "",
    category: "Inventos",
    color: "#A78BFA",
    title: "El fuego se 'inventó' hace 1 millón de años",
    description: "El Homo erectus ya lo controlaba en África. Cambió la evolución humana: permitió cocinar (más calorías para el cerebro) y extender la vida social nocturna.",
  },
  {
    id: 91,
    emoji: "",
    category: "Inventos",
    color: "#A78BFA",
    title: "La rueda se inventó para cerámica, no para transporte",
    description: "Los primeros registros de ruedas son del 3,500 a.C. en Mesopotamia, usadas para hacer vasijas. Tuvieron que pasar 300 años para ponerlas en carros.",
  },
  {
    id: 92,
    emoji: "",
    category: "Inventos",
    color: "#A78BFA",
    title: "El lápiz se inventó tras un descubrimiento de grafito",
    description: "En 1564 se encontró un yacimiento gigante en Inglaterra. Se envolvía grafito en cuerda para escribir. La goma de borrar vino 200 años después.",
  },
  {
    id: 93,
    emoji: "",
    category: "Inventos",
    color: "#A78BFA",
    title: "La primera foto tomó 8 horas",
    description: "Joseph Niépce la capturó en 1826 desde su ventana. La emulsión necesitaba 8 horas de exposición. Hoy un sensor captura una imagen en 1/8,000 de segundo.",
  },
  {
    id: 94,
    emoji: "",
    category: "Cultura",
    color: "#FF4D6D",
    title: "Shakespeare inventó +1,700 palabras",
    description: "Palabras como 'lonely', 'bedroom' y 'eyeball' aparecieron por primera vez en sus obras. Su vocabulario superaba los 29,000 términos.",
  },
  {
    id: 95,
    emoji: "",
    category: "Mitología",
    color: "#F87171",
    title: "Zeus no siempre gobernó el Olimpo",
    description: "En la mitología griega, derrocó a su padre Crono, quien a su vez había derrocado a Urano. La guerra de los Titanes duró 10 años antes de su victoria.",
  },
  {
    id: 96,
    emoji: "",
    category: "Mitología",
    color: "#F87171",
    title: "El dragón existe en casi todas las culturas",
    description: "Aparece en mitos chinos, europeos, mesoamericanos y africanos. Probablemente nació del miedo instintivo a serpientes, grandes felinos y aves rapaces combinados.",
  },
  {
    id: 97,
    emoji: "",
    category: "Mitología",
    color: "#F87171",
    title: "Anubis es el dios más antiguo de Egipto",
    description: "Antes de Osiris, Anubis era el dios principal del inframundo. Se representaba con cabeza de chacal por ser estos animales carroñeros que merodeaban las tumbas.",
  },
  {
    id: 98,
    emoji: "",
    category: "Mitología",
    color: "#F87171",
    title: "Aladín era originalmente chino",
    description: "En 'Las mil y una noches', la historia de Aladín se ambienta en 'China' (un país imaginario musulmán). Disney lo cambió a Agrabah, ciudad ficticia árabe.",
  },
  {
    id: 99,
    emoji: "",
    category: "Mitología",
    color: "#F87171",
    title: "Quetzalcóatl era un dios con forma de serpiente emplumada",
    description: "Para los aztecas, era el dios de la vida, la luz, el viento y la sabiduría. Su nombre combina 'quetzal' (pájaro sagrado) y 'cóatl' (serpiente).",
  },
  {
    id: 100,
    emoji: "",
    category: "Videojuegos",
    color: "#a855f7",
    title: "El primer videojuego es de 1958",
    description: "'Tennis for Two' fue creado por el físico William Higinbotham en un osciloscopio. Se creó para entretener a los visitantes de un laboratorio.",
  },
  {
    id: 101,
    emoji: "",
    category: "Videojuegos",
    color: "#a855f7",
    title: "Pac-Man tenía nombre japonés",
    description: "Se llamaba 'Puck-Man' (por 'paku', comer). En EE.UU. lo cambiaron a Pac-Man para evitar que los graffiteros convirtieran la P en una F en los arcades.",
  },
  {
    id: 102,
    emoji: "",
    category: "Deporte",
    color: "#f97316",
    title: "El basketball se inventó en 1891",
    description: "James Naismith usó canastas de melocotones y un balón de fútbol. El primer partido terminó 1-0. Hoy se juega en más de 200 países.",
  },
  {
    id: 103,
    emoji: "",
    category: "Deporte",
    color: "#f97316",
    title: "El fútbol se juega en 200+ países",
    description: "Es el deporte más popular del mundo: más de 250 millones de jugadores activos. La FIFA tiene más federaciones miembro que la ONU tiene países.",
  },
  {
    id: 104,
    emoji: "",
    category: "Deporte",
    color: "#f97316",
    title: "Los Juegos Olímpicos tienen 2,700 años",
    description: "Se celebraban en Olimpia desde el 776 a.C. hasta que el emperador Teodosio los prohibió en el 393 d.C. Fueron resucitados en 1896 por Pierre de Coubertin.",
  },
  {
    id: 105,
    emoji: "",
    category: "Matemáticas",
    color: "#60A5FA",
    title: "El cero se inventó en India",
    description: "Brahmagupta lo definió formalmente en el 628 d.C. Los mayas también lo usaron, pero sin concepto de 'negativo'. Sin cero, no habría informática moderna.",
  },
  {
    id: 106,
    emoji: "",
    category: "Matemáticas",
    color: "#60A5FA",
    title: "Algunos infinitos son más grandes que otros",
    description: "Georg Cantor demostró en 1874 que el infinito de los decimales es mayor que el de los enteros. Hay infinitos tamaños de infinito.",
  },
  {
    id: 107,
    emoji: "",
    category: "Matemáticas",
    color: "#60A5FA",
    title: "Pi tiene 100 trillones de decimales calculados",
    description: "En 2024 se alcanzaron 100,000,000,000,000 de decimales. Pero 39 decimales bastan para calcular la circunferencia del universo con precisión atómica.",
  },
  {
    id: 108,
    emoji: "",
    category: "Matemáticas",
    color: "#60A5FA",
    title: "La probabilidad de sacar 6 y 6 con dos dados es 1/36",
    description: "Pero la gente cree que '7' sale más. Y es cierto: el 7 tiene 6 combinaciones de 36, frente a 1 del 2 o del 12. Es el resultado más probable.",
  },
  {
    id: 109,
    emoji: "",
    category: "Comida",
    color: "#A78BFA",
    title: "El chocolate fue dinero durante siglos",
    description: "Los aztecas usaban granos de cacao como moneda: 1 conejo costaba 10 granos. Y pagaban impuestos en cacao. Para ellos era más valioso que el oro.",
  },
  {
    id: 110,
    emoji: "",
    category: "Comida",
    color: "#FF4D6D",
    title: "La pizza Margherita imita la bandera italiana",
    description: "Creada en 1889 para la reina Margherita: rojo (tomate), blanco (mozzarella) y verde (albahaca). Se ha convertido en la comida más global de la historia.",
  },
  {
    id: 111,
    emoji: "",
    category: "Comida",
    color: "#39FF14",
    title: "La miel nunca se echa a perder",
    description: "En tumbas egipcias de 3,000 años se encontró miel comestible. Su baja humedad y pH ácido impiden bacterias. Es el único alimento que no caduca.",
  },
  {
    id: 112,
    emoji: "",
    category: "Comida",
    color: "#39FF14",
    title: "El picante no es un sabor, es dolor",
    description: "La capsaicina activa los receptores de dolor, no los de sabor. Tu cuerpo reacciona como si te quemaras. Por eso sudas: el cerebro intenta enfriarte.",
  },
  {
    id: 113,
    emoji: "",
    category: "Cine",
    color: "#FF4D6D",
    title: "La primera película es de 1895",
    description: "Los hermanos Lumière proyectaron 'La salida de los obreros de la fábrica'. El público gritó cuando vio un tren acercándose en pantalla.",
  },
  {
    id: 114,
    emoji: "",
    category: "Cine",
    color: "#FF4D6D",
    title: "Drácula se basó en un príncipe real",
    description: "Vlad III de Valaquia, 'El Empalador' (siglo XV), inspiró a Bram Stoker. Su apodo 'Drăculea' significa 'hijo del dragón' en rumano.",
  },
  {
    id: 115,
    emoji: "",
    category: "Cine",
    color: "#FF4D6D",
    title: "El primer Oscar se entregó en 1929",
    description: "Duró 15 minutos y solo asistieron 270 personas. Las entradas costaban 5 dólares. Hoy la ceremonia dura más de 3 horas y se ve en 200 países.",
  },
  {
    id: 116,
    emoji: "",
    category: "Cine",
    color: "#FF4D6D",
    title: "Titanic costó más que el barco real",
    description: "La película de 1997 costó 200M USD. El Titanic original costó 7.5M USD de la época (unos 200M ajustados). James Cameron replicó el barco a escala 90%.",
  },
  {
    id: 117,
    emoji: "",
    category: "Clima",
    color: "#00E5FF",
    title: "Cada arcoíris es único para cada observador",
    description: "No existen dos personas viendo el mismo arcoíris. El ángulo depende de la posición exacta de tus ojos respecto a las gotas de agua.",
  },
  {
    id: 118,
    emoji: "",
    category: "Clima",
    color: "#00E5FF",
    title: "Una nube pesa 500 toneladas",
    description: "Una nube cumulus típica (1 km de diámetro) contiene 500,000 kg de agua. Flota porque el aire caliente bajo ella es aún más ligero que la nube.",
  },
  {
    id: 119,
    emoji: "",
    category: "Clima",
    color: "#00E5FF",
    title: "El récord de temperatura son 56.7°C",
    description: "En el Valle de la Muerte, California (10 julio 1913). La más baja: -89.2°C en la base Vostok, Antártida (1983). Una diferencia de 146°C en el mismo planeta.",
  },
  {
    id: 120,
    emoji: "",
    category: "Clima",
    color: "#00E5FF",
    title: "Un huracán libera energía como 10,000 bombas nucleares",
    description: "Pero disipada en horas y sobre un área enorme. La energía viene del calor latente del vapor de agua tropical al condensarse.",
  },
  {
    id: 121,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "Los dinosaurios reinaron 165 millones de años",
    description: "El Homo sapiens existe desde hace 300,000 años. Si la historia de la Tierra fuera un día, los dinosaurios habrían reinado 41 minutos; nosotros solo 0.6 segundos.",
  },
  {
    id: 122,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "La Luna tiene 'temblores'",
    description: "Los Apollo detectaron moonquakes en 1969. Son causados por las mareas gravitacionales de la Tierra. Pueden durar hasta una hora porque la Luna no tiene agua que amortigüe.",
  },
  {
    id: 123,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "El río más largo está bajo el Amazonas",
    description: "El río Hamza, descubierto en 2011, fluye a 4 km de profundidad bajo el Amazonas. Mide ~6,000 km, igual o más que su hermano superficial.",
  },
  {
    id: 124,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Un águila puede ver un conejo a 3 km",
    description: "Su agudeza visual es 8x mejor que la humana. Tiene dos foveas (puntos de enfoque) en cada ojo, permitiéndole ver adelante y a los lados a la vez.",
  },
  {
    id: 125,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "La luz es más lenta en el agua",
    description: "En el vacío viaja a 300,000 km/s. En agua, a 225,000 km/s. En vidrio, a 200,000 km/s. Esto es lo que permite que los lentes y los ojos funcionen.",
  },
  {
    id: 126,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El fuego no tiene sombra",
    description: "Porque es luz en sí mismo. Solo proyecta sombra si lo atraviesa un material denso (humo o gas caliente) que refracta la luz parcialmente.",
  },
  {
    id: 127,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "Júpiter tiene 95 lunas conocidas",
    description: "Cuatro de ellas (Galileanas: Ío, Europa, Ganímedes, Calixto) son del tamaño de planetas. Europa tiene océano bajo su hielo, candidato a vida extraterrestre.",
  },
  {
    id: 128,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "Tu cuerpo tiene más bacterias que células humanas",
    description: "Ratio aproximado: 1.3 bacterias por cada célula humana. La mayoría son beneficiosas y viven en tu intestino, pesando en total unos 200 gramos.",
  },
  {
    id: 129,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Los gusanos de seda son insectos domesticados",
    description: "Bombyx mori ya no existe en estado silvestre. Lleva 5,000 años siendo criado por humanos para producir seda. Es el segundo animal domesticado tras el perro.",
  },
  {
    id: 130,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "El 69% del agua dulce está en glaciares",
    description: "Solo el 2.5% del agua del planeta es dulce. De esa, 69% está congelada en polos y glaciares, 30% bajo tierra, y solo 1% en ríos y lagos accesibles.",
  },
  {
    id: 131,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "El rey más joven fue coronado antes de nacer",
    description: "Shapur II de Persia (309 d.C.) fue coronado en el vientre de su madre. Reinó 70 años y expandió el Imperio Sasánida.",
  },
  {
    id: 132,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "La Torre de Pisa se inclinó por error",
    description: "Se construyó sobre suelo blando en 1173. Tras siglos de inclinación progresiva, en 2008 se estabilizó con obras de ingeniería. Sigue inclinada 4 grados, a propósito.",
  },
  {
    id: 133,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "El tiburón blanco huele 1 gota de sangre en 100L de agua",
    description: "Su olfato es tan fino que detecta concentraciones de 1 parte por millón. Pero los tiburones no atacan por la sangre como en las películas: prefieren peces.",
  },
  {
    id: 134,
    emoji: "",
    category: "Espacio",
    color: "#C084FC",
    title: "El meteorito más grande pesa 60 toneladas",
    description: "Hoba (Namibia, 1920) mide 3x3x1 metros y nunca se movió tras caer. Cayó hace 80,000 años. Es el objeto natural más grande de origen extraterrestre en la Tierra.",
  },
  {
    id: 135,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Los tulipanes causaron la primera burbuja financiera",
    description: "En Holanda (1637) un bulbo de tulipán llegó a costar 10x el salario anual de un artesano. La 'Tulipomanía' estalló en febrero: los precios cayeron 99% en días.",
  },
  {
    id: 136,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Un loro puede aprender 1,000 palabras",
    description: "El récord lo tiene un loro gris africano llamado Puck (Guinness 1995): 1,728 palabras. Algunos loros entienden conceptos como color, forma y cantidad.",
  },
  {
    id: 137,
    emoji: "",
    category: "Historia",
    color: "#FFEA00",
    title: "Los caballos regresaron a América en 1493",
    description: "Colón los trajo en su segundo viaje. Curiosamente, los caballos EVOLUCIONARON en América hace 50M años, pero se extinguieron allí hace 10,000.",
  },
  {
    id: 138,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Los árboles se 'comunican' entre sí",
    description: "Por micelios de hongos en sus raíces (Wood Wide Web), pueden enviarse señales químicas, nutrientes y avisos de plagas. Una sola red puede conectar cientos de árboles.",
  },
  {
    id: 139,
    emoji: "",
    category: "Océano",
    color: "#22D3EE",
    title: "Los pulpos usan herramientas",
    description: "El pulpo de coco recoge conchas vacías y las usa como refugio transportable. Es uno de los pocos animales no mamíferos que demuestra uso de herramientas.",
  },
  {
    id: 140,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El hielo se forma en 17 estados distintos",
    description: "El hielo común es 'hielo Ih'. Pero existen al menos 17 fases sólidas del agua con estructuras cristalinas distintas, dependiendo de presión y temperatura.",
  },
  {
    id: 141,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Los elefantes reconocen su reflejo",
    description: "Solo humanos, grandes monos, delfines, orcas y elefantes pasan el 'test del espejo'. Se reconocen a sí mismos y se inspeccionan marcas pintadas en su cuerpo.",
  },
  {
    id: 142,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "El nombre 'América' viene de un italiano",
    description: "Américo Vespucio, navegante florentino, fue el primero en darse cuenta de que las tierras de Colón eran un continente nuevo, no Asia. El cartógrafo Waldseemüller lo nombró así en 1507.",
  },
  {
    id: 143,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Algunos lagartos caminan sobre el agua",
    description: "El basilisco verde corre sobre el agua hasta 4.5 metros gracias a sus pies con escamas. Mueve las patas tan rápido que crea una 'burbuja' de aire que lo sostiene.",
  },
  {
    id: 144,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "El volcán más activo está en Italia",
    description: "El Stromboli lleva 2,000 años en erupción casi continua. Los romanos lo llamaban 'el faro del Mediterráneo' por su brillo nocturno constante.",
  },
  {
    id: 145,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El agua es un 'anómalo' del universo",
    description: "Es la única sustancia que se expande al congelarse (por eso el hielo flota). Si no fuera así, los lagos se congelarían desde el fondo y la vida acuática moriría.",
  },
  {
    id: 146,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Los búhos no pueden mover los ojos",
    description: "Sus ojos son tubulares, fijos en las órbitas. Por eso giran la cabeza hasta 270°. Tienen 14 vértebras cervicales (nosotros solo 7), permitiendo ese giro extremo.",
  },
  {
    id: 147,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "Australia es más ancha que la Luna",
    description: "Diámetro lunar: 3,474 km. Anchura de Australia (este-oeste): 4,000 km. Pero la Luna tiene 5x la superficie del continente australiano.",
  },
  {
    id: 148,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "Las abejas entienden el concepto de cero",
    description: "En 2018 se demostró que las abejas pueden ser entrenadas para reconocer 'cero' como menor que 1. Es una capacidad matemática que creíamos exclusiva de primates y loros.",
  },
  {
    id: 149,
    emoji: "",
    category: "Geografía",
    color: "#7DD3FC",
    title: "El lugar más remoto de la Tierra es la Isla Bouvet",
    description: "Está en el Atlántico Sur, a 1,700 km de la tierra habitada más cercana. El 93% de su superficie está cubierta por un glaciar. Es territorio noruego.",
  },
  {
    id: 150,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Los escarabajos son el 25% de todas las especies",
    description: "Se conocen 400,000 especies de escarabajos. J.R.S. Haldane dijo: 'El Creador debió tener una pasión desmesurada por los escarabajos'.",
  },
  {
    id: 151,
    emoji: "",
    category: "Ciencia",
    color: "#00E5FF",
    title: "El cristal más antiguo tiene 4,400 millones de años",
    description: "Un zircon hallado en Australia occidental. Es la sustancia terrestre más antigua conocida. La Tierra misma se formó hace 4,540 millones de años.",
  },
  {
    id: 152,
    emoji: "",
    category: "Naturaleza",
    color: "#39FF14",
    title: "Las tortugas pueden vivir más de 190 años",
    description: "Jonathan, una tortuga gigante de las Seychelles nacida en 1832, es el animal terrestre vivo más viejo conocido. Tiene 191+ años y vive en Santa Elena.",
  },
]
