// Banco de preguntas para Trivials Wars
// 1000+ preguntas en total (100+ por categoría × 10 categorías)
// Las preguntas se cargan desde src/lib/questions-data/*.ts

import { randomUUID } from "crypto"
import { HISTORIA_QUESTIONS } from "./questions-data/historia"
import { MATEMATICAS_QUESTIONS } from "./questions-data/matematicas"
import { CIENCIA_QUESTIONS } from "./questions-data/ciencia"
import { VIDEOJUEGOS_QUESTIONS } from "./questions-data/videojuegos"
import { GEOGRAFIA_QUESTIONS } from "./questions-data/geografia"
import { ARTE_QUESTIONS } from "./questions-data/arte"
import { TECNOLOGIA_QUESTIONS } from "./questions-data/tecnologia"
import { MITOLOGIA_QUESTIONS } from "./questions-data/mitologia"
// Nuevas categorías Aquatic Ambience
import { OCEANO_QUESTIONS } from "./questions-data/oceano"
import { RETROFUTURISMO_QUESTIONS } from "./questions-data/retrofuturismo"
import { IA_QUESTIONS } from "./questions-data/ia"
import { ASTRONOMIA_QUESTIONS } from "./questions-data/astronomia"
import { CULTURAPOP_QUESTIONS } from "./questions-data/culturapop"
import { MARAVILLAS_QUESTIONS } from "./questions-data/maravillas"

export interface QuestionSeed {
  uuid: string
  category: string
  question: string
  options: [string, string, string, string]
  correctAnswer: string
  difficulty: "Facil" | "Medio" | "Dificil" | "Experto"
  explanation?: string // explicación opcional (Aquatic Ambience GDD)
}

// Preguntas de Entretenimiento y Deporte (definidas aquí directamente)
const RAW_ENTRETENIMIENTO_DEPORTE: Omit<QuestionSeed, "uuid">[] = [
  // ===== ENTRETENIMIENTO (100) =====
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Quién dirigió la película 'Titanic' de 1997?", options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Martin Scorsese"], correctAnswer: "James Cameron" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Cuál es el nombre del mago protagonista de la saga de J.K. Rowling?", options: ["Frodo Bolson", "Harry Potter", "Percy Jackson", "Ron Weasley"], correctAnswer: "Harry Potter" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Qué color es la almohada de SpongeBob?", options: ["Azul", "Verde", "Roja", "Amarilla"], correctAnswer: "Roja" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿En qué año se estrenó el primer film de 'Star Wars: Una nueva esperanza'?", options: ["1975", "1977", "1980", "1983"], correctAnswer: "1977" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Quién interpretó a Jack Sparrow en 'Piratas del Caribe'?", options: ["Orlando Bloom", "Johnny Depp", "Brad Pitt", "Tom Hanks"], correctAnswer: "Johnny Depp" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Cuál es el nombre de la muñeca más famosa de Mattel?", options: ["Barbie", "Bratz", "Monster High", "American Girl"], correctAnswer: "Barbie" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Quién creó a Mickey Mouse?", options: ["Walt Disney y Ub Iwerks", "Tex Avery", "Chuck Jones", "Hanna-Barbera"], correctAnswer: "Walt Disney y Ub Iwerks" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Qué banda británica lanzó el álbum 'Abbey Road' en 1969?", options: ["The Rolling Stones", "The Beatles", "The Who", "Pink Floyd"], correctAnswer: "The Beatles" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Cuál es el nombre real de Batman?", options: ["Peter Parker", "Bruce Wayne", "Clark Kent", "Tony Stark"], correctAnswer: "Bruce Wayne" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿En qué país se originó el anime?", options: ["China", "Corea del Sur", "Japón", "Estados Unidos"], correctAnswer: "Japón" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Quién escribió 'Don Quijote de la Mancha'?", options: ["Cervantes", "Shakespeare", "Lope de Vega", "García Márquez"], correctAnswer: "Cervantes" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Cómo se llama el león rey en la película de Disney 'El Rey León'?", options: ["Mufasa", "Simba", "Scar", "Timón"], correctAnswer: "Simba" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Qué actor interpreta a Iron Man en el MCU?", options: ["Chris Evans", "Robert Downey Jr.", "Mark Ruffalo", "Chris Hemsworth"], correctAnswer: "Robert Downey Jr." },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Cuál es el nombre del dragón de Hagrid en Harry Potter?", options: ["Norberto", "Fawkes", "Buckbeak", "Aragog"], correctAnswer: "Norberto" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Qué programa de TV tiene a Homer, Marge, Bart, Lisa y Maggie?", options: ["Family Guy", "Los Simpson", "South Park", "Futurama"], correctAnswer: "Los Simpson" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿En qué ciudad vive Spider-Man?", options: ["Los Ángeles", "Gotham", "Nueva York", "Chicago"], correctAnswer: "Nueva York" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Quién interpretó a Hermione Granger en las películas?", options: ["Emma Stone", "Emma Watson", "Dakota Fanning", "Daniel Radcliffe"], correctAnswer: "Emma Watson" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Cuál es el nombre del protagonista de 'Indiana Jones'?", options: ["Han Solo", "Indiana Jones", "Allan Quatermain", "Rick O'Connell"], correctAnswer: "Indiana Jones" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Qué famoso grupo musical cantó 'Bohemian Rhapsody'?", options: ["Queen", "The Beatles", "Led Zeppelin", "Pink Floyd"], correctAnswer: "Queen" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Cuál es el superhéroe más rápido del universo DC?", options: ["Batman", "Superman", "Flash", "Green Lantern"], correctAnswer: "Flash" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿En qué año se estrenó 'Avatar' de James Cameron?", options: ["2007", "2009", "2011", "2013"], correctAnswer: "2009" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Quién pintó la Mona Lisa?", options: ["Miguel Ángel", "Leonardo da Vinci", "Rafael", "Caravaggio"], correctAnswer: "Leonardo da Vinci" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Cuál es el nombre del villano principal en 'Star Wars'?", options: ["Darth Vader", "Darth Maul", "Emperador Palpatine", "Kylo Ren"], correctAnswer: "Darth Vader" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Qué streaming produce 'Stranger Things'?", options: ["Netflix", "Disney+", "HBO Max", "Amazon Prime"], correctAnswer: "Netflix" },
  { category: "Entretenimiento", difficulty: "Facil", question: "¿Cuál es el nombre del loro de Aladdin?", options: ["Iago", "Jafar", "Abu", "Rajah"], correctAnswer: "Iago" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Cuántas películas de Harry Potter se estrenaron en total?", options: ["7", "8", "9", "10"], correctAnswer: "8" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Quién dirigió 'Pulp Fiction'?", options: ["Martin Scorsese", "Quentin Tarantino", "David Fincher", "Ridley Scott"], correctAnswer: "Quentin Tarantino" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Qué actor interpreta a Sherlock Holmes en la serie BBC de 2010?", options: ["Benedict Cumberbatch", "Robert Downey Jr.", "Jonny Lee Miller", "Ian McKellen"], correctAnswer: "Benedict Cumberbatch" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿En qué año se estrenó 'El Padrino'?", options: ["1970", "1972", "1974", "1975"], correctAnswer: "1972" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Cuál es el nombre del robot principal en 'Wall-E'?", options: ["EVE", "R2-D2", "Wall-E", "BB-8"], correctAnswer: "Wall-E" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Quién compuso la banda sonora de 'Star Wars'?", options: ["Hans Zimmer", "John Williams", "Ennio Morricone", "Danny Elfman"], correctAnswer: "John Williams" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Qué actor interpreta a Neo en 'The Matrix'?", options: ["Brad Pitt", "Keanu Reeves", "Tom Cruise", "Will Smith"], correctAnswer: "Keanu Reeves" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿En qué película se canta 'Let It Go'?", options: ["Tangled", "Frozen", "Moana", "Brave"], correctAnswer: "Frozen" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Quién escribió y dirigió 'Inception'?", options: ["Christopher Nolan", "Steven Spielberg", "J.J. Abrams", "Ridley Scott"], correctAnswer: "Christopher Nolan" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Cómo se llama la espada de Harry Potter?", options: ["Excalibur", "Gryffindor", "Andúril", "Stormbringer"], correctAnswer: "Gryffindor" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Qué cantante es conocida como la 'Reina del Pop'?", options: ["Beyoncé", "Madonna", "Lady Gaga", "Britney Spears"], correctAnswer: "Madonna" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Qué banda compuso 'Smells Like Teen Spirit'?", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Alice in Chains"], correctAnswer: "Nirvana" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿En qué año se estrenó 'El Señor de los Anillos: La Comunidad del Anillo'?", options: ["1999", "2001", "2003", "2005"], correctAnswer: "2001" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Quién interpreta a Wolverine en las películas de X-Men?", options: ["Hugh Jackman", "Ryan Reynolds", "Chris Evans", "Andrew Garfield"], correctAnswer: "Hugh Jackman" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Cuál es el nombre del protagonista de 'Breaking Bad'?", options: ["Walter White", "Jesse Pinkman", "Saul Goodman", "Hank Schrader"], correctAnswer: "Walter White" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Qué grupo canta 'Billie Jean'?", options: ["Prince", "Michael Jackson", "Madonna", "David Bowie"], correctAnswer: "Michael Jackson" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿En qué año se estrenó 'Jurassic Park'?", options: ["1990", "1993", "1995", "1997"], correctAnswer: "1993" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Quién dirigió 'El Laberinto del Fauno'?", options: ["Pedro Almodóvar", "Guillermo del Toro", "Alejandro González Iñárritu", "Alfonso Cuarón"], correctAnswer: "Guillermo del Toro" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Qué actor interpreta al Joker en 'El Caballero de la Noche' (2008)?", options: ["Joaquin Phoenix", "Heath Ledger", "Jared Leto", "Jack Nicholson"], correctAnswer: "Heath Ledger" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Cuál es el nombre del bar donde se reúnen los personajes de 'How I Met Your Mother'?", options: ["MacLaren's", "Central Perk", "Cheers", "Paddy's Pub"], correctAnswer: "MacLaren's" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Quién compuso la canción 'Imagine'?", options: ["Bob Dylan", "John Lennon", "Paul McCartney", "Elton John"], correctAnswer: "John Lennon" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Cuál es el nombre del monstruo de Frankenstein?", options: ["Drácula", "Frankenstein", "La Criatura", "Golem"], correctAnswer: "La Criatura" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿En qué año se emitió el último episodio de 'Friends'?", options: ["2002", "2004", "2006", "2008"], correctAnswer: "2004" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Quién interpretó a Mary Poppins en 1964?", options: ["Julie Andrews", "Audrey Hepburn", "Deborah Kerr", "Emily Blunt"], correctAnswer: "Julie Andrews" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Qué cantante es conocido como 'El Rey del Pop'?", options: ["Elvis Presley", "Michael Jackson", "Prince", "David Bowie"], correctAnswer: "Michael Jackson" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Qué estudio creó 'Toy Story' (1995)?", options: ["DreamWorks", "Pixar", "Disney", "Blue Sky"], correctAnswer: "Pixar" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Cómo se llama el barco en 'Piratas del Caribe'?", options: ["HMS Victory", "Black Pearl", "Flying Dutchman", "Queen Anne's Revenge"], correctAnswer: "Black Pearl" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Quién interpretó a Hannibal Lecter en 'El Silencio de los Inocentes'?", options: ["Anthony Hopkins", "Brian Cox", "Mads Mikkelsen", "Gaspard Ulliel"], correctAnswer: "Anthony Hopkins" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Cuántas temporadas tiene 'Game of Thrones'?", options: ["6", "7", "8", "9"], correctAnswer: "8" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Quién interpretó a Joker en 'Joker' (2019)?", options: ["Joaquin Phoenix", "Jared Leto", "Christian Bale", "Heath Ledger"], correctAnswer: "Joaquin Phoenix" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿En qué año se estrenó 'Forrest Gump'?", options: ["1992", "1994", "1996", "1998"], correctAnswer: "1994" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Cómo se llama el pez azul en 'Buscando a Nemo'?", options: ["Nemo", "Dory", "Marlin", "Tad"], correctAnswer: "Dory" },
  { category: "Entretenimiento", difficulty: "Medio", question: "¿Qué actor interpreta a Tony Soprano en 'Los Soprano'?", options: ["James Gandolfini", "Steve Buscemi", "Edie Falco", "Michael Imperioli"], correctAnswer: "James Gandolfini" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Quién dirigió 'Ciudad de Dios' (2002)?", options: ["Fernando Meirelles", "Walter Salles", "Alfonso Cuarón", "Alejandro González Iñárritu"], correctAnswer: "Fernando Meirelles" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Qué película ganó el Óscar a Mejor Película en 2020?", options: ["1917", "Joker", "Parásitos", "Once Upon a Time in Hollywood"], correctAnswer: "Parásitos" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Cuál es el primer film de Studio Ghibli?", options: ["Mi Vecino Totoro", "Nausicaä del Valle del Viento", "La Princesa Mononoke", "El Viaje de Chihiro"], correctAnswer: "Nausicaä del Valle del Viento" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Qué actor interpretó a Norman Bates en 'Psicosis' (1960)?", options: ["Anthony Perkins", "Janet Leigh", "Martin Balsam", "Vera Miles"], correctAnswer: "Anthony Perkins" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿En qué año se estrenó 'Blade Runner'?", options: ["1980", "1982", "1984", "1986"], correctAnswer: "1982" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Quién compuso 'The Wall' (1979)?", options: ["The Beatles", "Pink Floyd", "The Who", "Led Zeppelin"], correctAnswer: "Pink Floyd" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Cuál es el verdadero nombre de Lady Gaga?", options: ["Stefani Germanotta", "Beyoncé Knowles", "Katy Perry", "Adele Adkins"], correctAnswer: "Stefani Germanotta" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Qué actor interpreta a Loki en el MCU?", options: ["Tom Hiddleston", "Chris Hemsworth", "Mark Ruffalo", "Benedict Cumberbatch"], correctAnswer: "Tom Hiddleston" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿En qué año se publicó el primer cómic de Spider-Man?", options: ["1960", "1962", "1964", "1966"], correctAnswer: "1962" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Qué álbum de The Beatles incluye 'A Day in the Life'?", options: ["Revolver", "Sgt. Pepper's Lonely Hearts Club Band", "Abbey Road", "Let It Be"], correctAnswer: "Sgt. Pepper's Lonely Hearts Club Band" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿En qué año se estrenó 'Metrópolis' de Fritz Lang?", options: ["1925", "1927", "1929", "1931"], correctAnswer: "1927" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Quién interpretó a Rick Blaine en 'Casablanca'?", options: ["Humphrey Bogart", "Cary Grant", "Clark Gable", "James Stewart"], correctAnswer: "Humphrey Bogart" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Qué director es conocido como 'El Maestro del Suspense'?", options: ["Alfred Hitchcock", "Stanley Kubrick", "Steven Spielberg", "Martin Scorsese"], correctAnswer: "Alfred Hitchcock" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Cuál fue el primer largometraje de Pixar?", options: ["Bichos", "Toy Story", "Buscando a Nemo", "Monsters, Inc."], correctAnswer: "Toy Story" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿En qué año se estrenó 'Lo Que el Viento se Llevó'?", options: ["1937", "1939", "1941", "1943"], correctAnswer: "1939" },
  { category: "Entretenimiento", difficulty: "Dificil", question: "¿Quién compuso 'Las Cuatro Estaciones'?", options: ["Johann Sebastian Bach", "Antonio Vivaldi", "Wolfgang Amadeus Mozart", "Georg Friedrich Händel"], correctAnswer: "Antonio Vivaldi" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Quién dirigió 'Stalker' (1979)?", options: ["Andrei Tarkovsky", "Stanley Kubrick", "Akira Kurosawa", "Federico Fellini"], correctAnswer: "Andrei Tarkovsky" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Qué álbum de Pink Floyd incluye 'Shine On You Crazy Diamond'?", options: ["The Dark Side of the Moon", "Wish You Were Here", "Animals", "The Wall"], correctAnswer: "Wish You Were Here" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Quién ganó el Óscar a Mejor Director por 'La Forma del Agua' (2017)?", options: ["Guillermo del Toro", "Christopher Nolan", "Jordan Peele", "Paul Thomas Anderson"], correctAnswer: "Guillermo del Toro" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿En qué año se estrenó 'Solaris' de Tarkovsky?", options: ["1970", "1972", "1974", "1976"], correctAnswer: "1972" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Cuál fue la ópera debut de Mozart?", options: ["Las Bodas de Fígaro", "Don Giovanni", "La Flauta Mágica", "Mitridate"], correctAnswer: "Mitridate" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Quién escribió 'La Madre' (obra de teatro)?", options: ["Bertolt Brecht", "Anton Chéjov", "Henrik Ibsen", "August Strindberg"], correctAnswer: "Bertolt Brecht" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Qué actor ha ganado más Óscars de la historia?", options: ["Katharine Hepburn", "Meryl Streep", "Jack Nicholson", "Daniel Day-Lewis"], correctAnswer: "Katharine Hepburn" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Cuál fue la primera película en color de Disney?", options: ["Blancanieves", "Pinocho", "Fantasía", "La Cenicienta"], correctAnswer: "Blancanieves" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Quién compuso 'El Pájaro de Fuego'?", options: ["Igor Stravinsky", "Sergéi Prokófiev", "Dmitri Shostakóvich", "Claude Debussy"], correctAnswer: "Igor Stravinsky" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿En qué año se estrenó 'Akira' (anime)?", options: ["1986", "1988", "1990", "1992"], correctAnswer: "1988" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Qué director es conocido por la trilogía 'Tres Colores'?", options: ["Krzysztof Kieślowski", "Andrei Tarkovsky", "Milos Forman", "Roman Polanski"], correctAnswer: "Krzysztof Kieślowski" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿Cuál es el nombre del personaje principal de 'Evangelion'?", options: ["Shinji Ikari", "Asuka Langley", "Rei Ayanami", "Misato Katsuragi"], correctAnswer: "Shinji Ikari" },
  { category: "Entretenimiento", difficulty: "Experto", question: "¿En qué año se publicó el primer número de 'Watchmen'?", options: ["1985", "1986", "1987", "1988"], correctAnswer: "1986" },

  // ===== DEPORTE (100) =====
  { category: "Deporte", difficulty: "Facil", question: "¿Cuántos jugadores tiene un equipo de fútbol en el campo?", options: ["9", "10", "11", "12"], correctAnswer: "11" },
  { category: "Deporte", difficulty: "Facil", question: "¿En qué país se originó el fútbol moderno?", options: ["Brasil", "Inglaterra", "Italia", "España"], correctAnswer: "Inglaterra" },
  { category: "Deporte", difficulty: "Facil", question: "¿Cada cuántos años se celebran los Juegos Olímpicos de verano?", options: ["2", "3", "4", "5"], correctAnswer: "4" },
  { category: "Deporte", difficulty: "Facil", question: "¿Qué deporte se juega en Wimbledon?", options: ["Fútbol", "Tenis", "Golf", "Críquet"], correctAnswer: "Tenis" },
  { category: "Deporte", difficulty: "Facil", question: "¿De qué país es originario el sumo?", options: ["China", "Japón", "Corea", "Mongolia"], correctAnswer: "Japón" },
  { category: "Deporte", difficulty: "Facil", question: "¿Cuántos puntos vale un triple en baloncesto?", options: ["2", "3", "4", "5"], correctAnswer: "3" },
  { category: "Deporte", difficulty: "Facil", question: "¿En qué deporte se usa una raqueta y una pelota amarilla?", options: ["Bádminton", "Tenis", "Squash", "Ping-pong"], correctAnswer: "Tenis" },
  { category: "Deporte", difficulty: "Facil", question: "¿Qué país ganó el Mundial de Fútbol de 2014?", options: ["Argentina", "Brasil", "Alemania", "España"], correctAnswer: "Alemania" },
  { category: "Deporte", difficulty: "Facil", question: "¿Cuántos minutos dura un partido de fútbol (sin descuentos)?", options: ["60", "80", "90", "100"], correctAnswer: "90" },
  { category: "Deporte", difficulty: "Facil", question: "¿En qué deporte se usa un palo y una pelota pequeña?", options: ["Golf", "Béisbol", "Críquet", "Hockey"], correctAnswer: "Golf" },
  { category: "Deporte", difficulty: "Facil", question: "¿Quién es conocido como 'O Rei' del fútbol?", options: ["Maradona", "Pelé", "Messi", "Cruyff"], correctAnswer: "Pelé" },
  { category: "Deporte", difficulty: "Facil", question: "¿Qué color es la tarjeta de expulsión en fútbol?", options: ["Verde", "Amarilla", "Roja", "Azul"], correctAnswer: "Roja" },
  { category: "Deporte", difficulty: "Facil", question: "¿En qué deporte se anota un 'try'?", options: ["Fútbol", "Rugby", "Béisbol", "Críquet"], correctAnswer: "Rugby" },
  { category: "Deporte", difficulty: "Facil", question: "¿Cuántos jugadores tiene un equipo de voleibol en cancha?", options: ["5", "6", "7", "8"], correctAnswer: "6" },
  { category: "Deporte", difficulty: "Facil", question: "¿En qué país se inventó el basketball?", options: ["Canadá", "Estados Unidos", "Inglaterra", "Francia"], correctAnswer: "Estados Unidos" },
  { category: "Deporte", difficulty: "Facil", question: "¿Cuál es el deporte rey en Estados Unidos?", options: ["Béisbol", "Fútbol Americano", "Basketball", "Hockey"], correctAnswer: "Fútbol Americano" },
  { category: "Deporte", difficulty: "Facil", question: "¿En qué ciudad están los Juegos Olímpicos de 2024?", options: ["Londres", "Tokio", "París", "Los Ángeles"], correctAnswer: "París" },
  { category: "Deporte", difficulty: "Facil", question: "¿Qué material es la pelota de ping-pong?", options: ["Plástico", "Madera", "Goma", "Cuero"], correctAnswer: "Plástico" },
  { category: "Deporte", difficulty: "Facil", question: "¿Cuántos sets se necesitan para ganar un partido de tenis al mejor de 5?", options: ["2", "3", "4", "5"], correctAnswer: "3" },
  { category: "Deporte", difficulty: "Facil", question: "¿En qué país nació Lionel Messi?", options: ["Brasil", "Argentina", "Uruguay", "España"], correctAnswer: "Argentina" },
  { category: "Deporte", difficulty: "Facil", question: "¿Cuánto dura un partido de basketball de la NBA (sin tiempos muertos)?", options: ["40 min", "48 min", "60 min", "72 min"], correctAnswer: "48 min" },
  { category: "Deporte", difficulty: "Facil", question: "¿En qué deporte se usa un 'shuttlecock'?", options: ["Bádminton", "Tenis", "Voleibol", "Squash"], correctAnswer: "Bádminton" },
  { category: "Deporte", difficulty: "Facil", question: "¿Qué país ganó la Copa Mundial Femenina 2019?", options: ["Alemania", "Inglaterra", "Estados Unidos", "Holanda"], correctAnswer: "Estados Unidos" },
  { category: "Deporte", difficulty: "Facil", question: "¿Qué deporte practica Usain Bolt?", options: ["Maratón", "Atletismo (100m)", "Ciclismo", "Natación"], correctAnswer: "Atletismo (100m)" },
  { category: "Deporte", difficulty: "Facil", question: "¿Cuál es el deporte nacional de Japón?", options: ["Judo", "Sumo", "Kendo", "Karate"], correctAnswer: "Sumo" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué año se celebró el primer Mundial de Fútbol?", options: ["1924", "1930", "1934", "1938"], correctAnswer: "1930" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién ganó el Balón de Oro 2021?", options: ["Lionel Messi", "Robert Lewandowski", "Karim Benzema", "Cristiano Ronaldo"], correctAnswer: "Lionel Messi" },
  { category: "Deporte", difficulty: "Medio", question: "¿Cuántos Grand Slam ha ganado Rafael Nadal en Roland Garros?", options: ["10", "12", "14", "16"], correctAnswer: "14" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué equipo jugó Michael Jordan la mayor parte de su carrera?", options: ["Lakers", "Bulls", "Celtics", "Pistons"], correctAnswer: "Bulls" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién tiene el récord de más home runs en una temporada de MLB?", options: ["Babe Ruth", "Barry Bonds", "Hank Aaron", "Mark McGwire"], correctAnswer: "Barry Bonds" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué año se jugó el primer Super Bowl?", options: ["1965", "1967", "1969", "1971"], correctAnswer: "1967" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué país se inventó el rugby?", options: ["Escocia", "Inglaterra", "Irlanda", "Gales"], correctAnswer: "Inglaterra" },
  { category: "Deporte", difficulty: "Medio", question: "¿Cuántos jugadores tiene un equipo de rugby union en el campo?", options: ["11", "13", "15", "17"], correctAnswer: "15" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién ganó el Tour de France 2020?", options: ["Tadej Pogačar", "Egan Bernal", "Primož Roglič", "Chris Froome"], correctAnswer: "Tadej Pogačar" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué año se celebraron los Juegos Olímpicos de Barcelona?", options: ["1988", "1992", "1996", "2000"], correctAnswer: "1992" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué deporte se destacó Muhammad Ali?", options: ["Boxeo", "Lucha libre", "Kickboxing", "MMA"], correctAnswer: "Boxeo" },
  { category: "Deporte", difficulty: "Medio", question: "¿Qué país tiene más Copas del Mundo de fútbol (masculino)?", options: ["Argentina", "Brasil", "Italia", "Alemania"], correctAnswer: "Brasil" },
  { category: "Deporte", difficulty: "Medio", question: "¿Cuántos jugadores hay en un equipo de hockey sobre hielo en el hielo?", options: ["5", "6", "7", "8"], correctAnswer: "6" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién ganó 8 medallas de oro en los Juegos Olímpicos de Beijing 2008?", options: ["Usain Bolt", "Michael Phelps", "Carl Lewis", "Mark Spitz"], correctAnswer: "Michael Phelps" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué equipo juega LeBron James (2024)?", options: ["Lakers", "Cavaliers", "Heat", "Celtics"], correctAnswer: "Lakers" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién tiene el récord de más goles en mundiales?", options: ["Pelé", "Ronaldo", "Klose", "Messi"], correctAnswer: "Klose" },
  { category: "Deporte", difficulty: "Medio", question: "¿Cuánto mide una maratón oficial?", options: ["40 km", "42.195 km", "45 km", "50 km"], correctAnswer: "42.195 km" },
  { category: "Deporte", difficulty: "Medio", question: "¿Qué equipo ha ganado más Champions League?", options: ["Bayern Munich", "Barcelona", "Real Madrid", "AC Milan"], correctAnswer: "Real Madrid" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué deporte se usa una tabla y remos?", options: ["Surf", "Paddle surf", "Kayak", "Windsurf"], correctAnswer: "Paddle surf" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién fue el primer boxeador en ganar el título mundial en tres pesos distintos?", options: ["Muhammad Ali", "Bob Fitzsimmons", "Henry Armstrong", "Roberto Durán"], correctAnswer: "Bob Fitzsimmons" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué deporte se lanzan 'strikes' y 'balls'?", options: ["Críquet", "Béisbol", "Softball", "Rounders"], correctAnswer: "Béisbol" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué año Argentina ganó su última Copa del Mundo (hasta 2022)?", options: ["1982", "1986", "1990", "2014"], correctAnswer: "1986" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién ganó Wimbledon 2023 en hombres?", options: ["Novak Djokovic", "Carlos Alcaraz", "Daniil Medvedev", "Jannik Sinner"], correctAnswer: "Carlos Alcaraz" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué deporte compite Simone Biles?", options: ["Gimnasia artística", "Patinación", "Natación", "Atletismo"], correctAnswer: "Gimnasia artística" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué ciudad se encuentran los Juegos Olímpicos de 2028?", options: ["París", "Tokio", "Los Ángeles", "Brisbane"], correctAnswer: "Los Ángeles" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién ganó la Copa América 2021?", options: ["Brasil", "Argentina", "Colombia", "Perú"], correctAnswer: "Argentina" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué equipo hizo carrera Cristiano Ronaldo antes de Juventus?", options: ["Real Madrid", "Manchester United", "Barcelona", "PSG"], correctAnswer: "Real Madrid" },
  { category: "Deporte", difficulty: "Medio", question: "¿Qué ciclista tiene 7 Tours de France (luego descalificado)?", options: ["Miguel Indurain", "Lance Armstrong", "Jacques Anquetil", "Bernard Hinault"], correctAnswer: "Lance Armstrong" },
  { category: "Deporte", difficulty: "Medio", question: "¿Cuál es el récord mundial de 100m lisos masculino?", options: ["9.58s", "9.63s", "9.72s", "9.84s"], correctAnswer: "9.58s" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué deporte se usa un 'puck'?", options: ["Hockey sobre hielo", "Bádminton", "Críquet", "Field hockey"], correctAnswer: "Hockey sobre hielo" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién ganó el Mundial de Fútbol 2018?", options: ["Alemania", "Argentina", "Francia", "Croacia"], correctAnswer: "Francia" },
  { category: "Deporte", difficulty: "Medio", question: "¿Qué país inventó el cricket?", options: ["Australia", "India", "Inglaterra", "Sudáfrica"], correctAnswer: "Inglaterra" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién fue conocido como 'La Pulga'?", options: ["Maradona", "Messi", "Aguero", "Tevez"], correctAnswer: "Messi" },
  { category: "Deporte", difficulty: "Medio", question: "¿Cuántos minutos dura cada mitad en hockey sobre hielo profesional?", options: ["15", "20", "25", "30"], correctAnswer: "20" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué país se originó el taekwondo?", options: ["Japón", "China", "Corea", "Tailandia"], correctAnswer: "Corea" },
  { category: "Deporte", difficulty: "Medio", question: "¿Quién ganó la Fórmula 1 en 2021?", options: ["Lewis Hamilton", "Max Verstappen", "Charles Leclerc", "Valtteri Bottas"], correctAnswer: "Max Verstappen" },
  { category: "Deporte", difficulty: "Medio", question: "¿En qué deporte se usa la expresión 'bogie'?", options: ["Golf", "Bowling", "Billar", "Dard"], correctAnswer: "Golf" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién ganó el primer Mundial de Fútbol en 1930?", options: ["Argentina", "Brasil", "Uruguay", "Italia"], correctAnswer: "Uruguay" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Cuántos títulos de Champions League tiene el AC Milan?", options: ["5", "6", "7", "8"], correctAnswer: "7" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién fue el primer campeón mundial de ajedrez reconocido oficialmente?", options: ["Emanuel Lasker", "Wilhelm Steinitz", "José Raúl Capablanca", "Alexander Alekhine"], correctAnswer: "Wilhelm Steinitz" },
  { category: "Deporte", difficulty: "Dificil", question: "¿En qué año se integró el fútbol femenino a los Juegos Olímpicos?", options: ["1992", "1996", "2000", "2004"], correctAnswer: "1996" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Cuál es el estadio más grande del mundo por capacidad?", options: ["Camp Nou", "Wembley", "Rungrado May Day", "Maracaná"], correctAnswer: "Rungrado May Day" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién ganó 4 medallas de oro en los Juegos Olímpicos de Berlín 1936?", options: ["Jesse Owens", "Carl Lewis", "Paavo Nurmi", "Emil Zátopek"], correctAnswer: "Jesse Owens" },
  { category: "Deporte", difficulty: "Dificil", question: "¿En qué año se jugó el primer partido de rugby internacional?", options: ["1871", "1875", "1880", "1888"], correctAnswer: "1871" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién fue el primer pitcher en lanzar un juego perfecto en la Serie Mundial?", options: ["Don Larsen", "Cy Young", "Sandy Koufax", "Roy Halladay"], correctAnswer: "Don Larsen" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Cuántos jugadores en cancha tiene el fútbol australiano por equipo?", options: ["15", "16", "18", "20"], correctAnswer: "18" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién ganó la Copa Mundial de Cricket 2019?", options: ["India", "Australia", "Inglaterra", "Nueva Zelanda"], correctAnswer: "Inglaterra" },
  { category: "Deporte", difficulty: "Dificil", question: "¿En qué deporte se usa el término 'chukker'?", options: ["Polo", "Hockey sobre hierba", "Críquet", "Lacrosse"], correctAnswer: "Polo" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién tiene el récord de más vueltas en el Tour de France?", options: ["Bernard Hinault", "Eddy Merckx", "Miguel Indurain", "Jacques Anquetil"], correctAnswer: "Eddy Merckx" },
  { category: "Deporte", difficulty: "Dificil", question: "¿En qué año se fundó la FIFA?", options: ["1904", "1908", "1912", "1920"], correctAnswer: "1904" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién ganó el Mundial de Fútbol de 1978?", options: ["Holanda", "Argentina", "Brasil", "Italia"], correctAnswer: "Argentina" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Cuál fue el primer país africano en jugar un Mundial de Fútbol?", options: ["Nigeria", "Camerún", "Egipto", "Marruecos"], correctAnswer: "Egipto" },
  { category: "Deporte", difficulty: "Dificil", question: "¿En qué año se permitió professionalism en rugby union?", options: ["1993", "1995", "1997", "2000"], correctAnswer: "1995" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién fue el primer español en ganar el Tour de France?", options: ["Miguel Indurain", "Pedro Delgado", "Carlos Sastre", "Alberto Contador"], correctAnswer: "Pedro Delgado" },
  { category: "Deporte", difficulty: "Dificil", question: "¿En qué deporte se anotan 'ends'?", options: ["Boccia", "Bowls", "Tir al arco", "Curling"], correctAnswer: "Curling" },
  { category: "Deporte", difficulty: "Dificil", question: "¿En qué país se celebraron los primeros Juegos Olímpicos modernos?", options: ["Francia", "Grecia", "Inglaterra", "Estados Unidos"], correctAnswer: "Grecia" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién tiene el récord de más Grand Slams en tenis masculino?", options: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"], correctAnswer: "Novak Djokovic" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Cuántos jugadores hay en un equipo de fútbol americano en total (no en cancha)?", options: ["33", "45", "53", "60"], correctAnswer: "53" },
  { category: "Deporte", difficulty: "Dificil", question: "¿Quién ganó el Super Bowl en 2023?", options: ["Eagles", "Chiefs", "49ers", "Bengals"], correctAnswer: "Chiefs" },
  { category: "Deporte", difficulty: "Experto", question: "¿Cuál fue el primer equipo de fútbol en usar números en las camisetas?", options: ["Arsenal", "Chelsea", "Sheffield Wednesday", "Everton"], correctAnswer: "Chelsea" },
  { category: "Deporte", difficulty: "Experto", question: "¿En qué año se instituyó la regla de los 3 puntos en basketball?", options: ["1979", "1980", "1981", "1982"], correctAnswer: "1979" },
  { category: "Deporte", difficulty: "Experto", question: "¿Quién fue el primer no británico en ganar el Open Championship?", options: ["Bobby Jones", "Walter Hagen", "J.H. Taylor", "Arnaud Massy"], correctAnswer: "Arnaud Massy" },
  { category: "Deporte", difficulty: "Experto", question: "¿En qué año se jugó el primer partido oficial de cricket Test?", options: ["1877", "1880", "1882", "1885"], correctAnswer: "1877" },
  { category: "Deporte", difficulty: "Experto", question: "¿Quién tiene el récord de más carreras en MLB (hits)?", options: ["Ty Cobb", "Pete Rose", "Hank Aaron", "Derek Jeter"], correctAnswer: "Pete Rose" },
  { category: "Deporte", difficulty: "Experto", question: "¿En qué deporte se compitió por primera vez en los Juegos Olímpicos modernos?", options: ["Atletismo", "Natación", "Esgrima", "Ciclismo"], correctAnswer: "Atletismo" },
  { category: "Deporte", difficulty: "Experto", question: "¿Quién fue el primer boxeador en ganar el título mundial en 8 categorías distintas?", options: ["Manny Pacquiao", "Floyd Mayweather", "Oscar De La Hoya", "Thomas Hearns"], correctAnswer: "Manny Pacquiao" },
  { category: "Deporte", difficulty: "Experto", question: "¿Cuántos hoyos tiene un campo de golf de campeonato?", options: ["16", "18", "20", "22"], correctAnswer: "18" },
  { category: "Deporte", difficulty: "Experto", question: "¿Quién ganó el primer Tour de France en 1903?", options: ["Maurice Garin", "Lucien Pothier", "Fernand Augereau", "Hippolyte Aucouturier"], correctAnswer: "Maurice Garin" },
  { category: "Deporte", difficulty: "Experto", question: "¿En qué año se permitió por primera vez la participación de mujeres en atletismo olímpico?", options: ["1924", "1928", "1932", "1936"], correctAnswer: "1928" },
  { category: "Deporte", difficulty: "Experto", question: "¿Quién tiene el récord de más medallas olímpicas de oro en carreras de velocidad?", options: ["Usain Bolt", "Carl Lewis", "Paavo Nurmi", "Michael Johnson"], correctAnswer: "Usain Bolt" },
  { category: "Deporte", difficulty: "Experto", question: "¿Cuál fue el primer equipo no uruguayo ni argentino en ganar la Copa América?", options: ["Brasil", "Chile", "Perú", "Colombia"], correctAnswer: "Brasil" },
  { category: "Deporte", difficulty: "Experto", question: "¿Quién fue el primer mexicano en ganar el Mundial de Fórmula 1?", options: ["Sergio Pérez", "Pedro Rodríguez", "Moisés Solana", "Ricardo Rodríguez"], correctAnswer: "Pedro Rodríguez" },
]

const ENTRETENIMIENTO_DEPORTE_QUESTIONS: QuestionSeed[] = RAW_ENTRETENIMIENTO_DEPORTE.map((q, i) => ({
  ...q,
  uuid: `q-entdep-${(i + 1).toString().padStart(4, "0")}`,
}))

// Combinar todas las preguntas
export const QUESTIONS_SEED: QuestionSeed[] = [
  ...ENTRETENIMIENTO_DEPORTE_QUESTIONS,
  ...HISTORIA_QUESTIONS,
  ...MATEMATICAS_QUESTIONS,
  ...CIENCIA_QUESTIONS,
  ...VIDEOJUEGOS_QUESTIONS,
  ...GEOGRAFIA_QUESTIONS,
  ...ARTE_QUESTIONS,
  ...TECNOLOGIA_QUESTIONS,
  ...MITOLOGIA_QUESTIONS,
  // Nuevas categorías Aquatic Ambience
  ...OCEANO_QUESTIONS,
  ...RETROFUTURISMO_QUESTIONS,
  ...IA_QUESTIONS,
  ...ASTRONOMIA_QUESTIONS,
  ...CULTURAPOP_QUESTIONS,
  ...MARAVILLAS_QUESTIONS,
]
