// Arte y Literatura — 100+ preguntas
import type { QuestionSeed } from "../questions"

const RAW: Omit<QuestionSeed, "uuid">[] = [
  { category: "Arte", difficulty: "Facil", question: "¿Quién pintó La Mona Lisa?", options: ["Miguel Ángel", "Leonardo da Vinci", "Rafael", "Botticelli"], correctAnswer: "Leonardo da Vinci" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién escribió 'Romeo y Julieta'?", options: ["Cervantes", "Shakespeare", "Lope de Vega", "Molière"], correctAnswer: "Shakespeare" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién pintó 'El Guernica'?", options: ["Dalí", "Picasso", "Miró", "Goya"], correctAnswer: "Picasso" },
  { category: "Arte", difficulty: "Facil", question: "¿Cuál es la obra más famosa de Miguel de Cervantes?", options: ["La Celestina", "Don Quijote", "Lazarillo de Tormes", "El Cantar de Mio Cid"], correctAnswer: "Don Quijote" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién escribió 'Cien años de soledad'?", options: ["Borges", "García Márquez", "Vargas Llosa", "Neruda"], correctAnswer: "García Márquez" },
  { category: "Arte", difficulty: "Facil", question: "¿En qué museo está La Mona Lisa?", options: ["Museo del Prado", "Louvre", "British Museum", "Met"], correctAnswer: "Louvre" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién pintó 'La noche estrellada'?", options: ["Van Gogh", "Monet", "Cézanne", "Renoir"], correctAnswer: "Van Gogh" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién escribió 'Hamlet'?", options: ["Shakespeare", "Cervantes", "Goethe", "Dante"], correctAnswer: "Shakespeare" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién es el autor de 'El Principito'?", options: ["Saint-Exupéry", "Jules Verne", "Victor Hugo", "Camus"], correctAnswer: "Saint-Exupéry" },
  { category: "Arte", difficulty: "Facil", question: "¿Qué pintor es famoso por sus lirios de agua?", options: ["Manet", "Monet", "Degas", "Renoir"], correctAnswer: "Monet" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién escribió 'La Odisea'?", options: ["Homero", "Virgilio", "Sófocles", "Esopo"], correctAnswer: "Homero" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién es el autor de 'Drácula'?", options: ["Mary Shelley", "Bram Stoker", "Edgar Allan Poe", "H.P. Lovecraft"], correctAnswer: "Bram Stoker" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién es el autor de 'Crimen y castigo'?", options: ["Tolstói", "Dostoievski", "Chéjov", "Gogol"], correctAnswer: "Dostoievski" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién pintó 'Las Meninas'?", options: ["Goya", "Velázquez", "Murillo", "El Greco"], correctAnswer: "Velázquez" },
  { category: "Arte", difficulty: "Facil", question: "¿En qué país nació Picasso?", options: ["Italia", "Francia", "España", "Portugal"], correctAnswer: "España" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién escribió '1984'?", options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Isaac Asimov"], correctAnswer: "George Orwell" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién es el autor de 'El Señor de los Anillos'?", options: ["C.S. Lewis", "J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin"], correctAnswer: "J.R.R. Tolkien" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién pintó 'La persistencia de la memoria' (relojes blandos)?", options: ["Picasso", "Dalí", "Magritte", "Miró"], correctAnswer: "Dalí" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién escribió 'Orgullo y prejuicio'?", options: ["Charlotte Brontë", "Jane Austen", "Emily Brontë", "Virginia Woolf"], correctAnswer: "Jane Austen" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién es el autor de 'La divina comedia'?", options: ["Petrarca", "Boccaccio", "Dante", "Maquiavelo"], correctAnswer: "Dante" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién es el autor de 'Moby Dick'?", options: ["Herman Melville", "Mark Twain", "Edgar Allan Poe", "Jack London"], correctAnswer: "Herman Melville" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién es el autor de 'Don Juan Tenorio'?", options: ["Zorrilla", "Lope de Vega", "Calderón de la Barca", "Tirso de Molina"], correctAnswer: "Zorrilla" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién pintó 'La última cena'?", options: ["Miguel Ángel", "Leonardo da Vinci", "Rafael", "Tiziano"], correctAnswer: "Leonardo da Vinci" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién escribió 'La Iliada'?", options: ["Homero", "Hesíodo", "Píndaro", "Safo"], correctAnswer: "Homero" },
  { category: "Arte", difficulty: "Facil", question: "¿Quién escribió 'Los miserables'?", options: ["Balzac", "Victor Hugo", "Flaubert", "Zola"], correctAnswer: "Victor Hugo" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'Crimen y castigo'?", options: ["Tolstói", "Dostoievski", "Gogol", "Chéjov"], correctAnswer: "Dostoievski" },
  { category: "Arte", difficulty: "Medio", question: "¿Qué movimiento artístico lideró Andy Warhol?", options: ["Cubismo", "Pop Art", "Surrealismo", "Expresionismo"], correctAnswer: "Pop Art" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién compuso 'Las cuatro estaciones'?", options: ["Bach", "Vivaldi", "Mozart", "Händel"], correctAnswer: "Vivaldi" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'La metamorfosis'?", options: ["Kafka", "Musil", "Mann", "Hesse"], correctAnswer: "Kafka" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién pintó 'El grito'?", options: ["Munch", "Klimt", "Schiele", "Kandinsky"], correctAnswer: "Munch" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'Ulises'?", options: ["James Joyce", "Virginia Woolf", "T.S. Eliot", "Ezra Pound"], correctAnswer: "James Joyce" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién pintó 'Los girasoles'?", options: ["Van Gogh", "Monet", "Cézanne", "Renoir"], correctAnswer: "Van Gogh" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién es el autor de 'Cien sonetos de amor'?", options: ["Pablo Neruda", "Benedetti", "García Lorca", "Bécquer"], correctAnswer: "Pablo Neruda" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién compuso la 'Novena Sinfonía'?", options: ["Mozart", "Beethoven", "Bach", "Brahms"], correctAnswer: "Beethoven" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'En el camino'?", options: ["Jack Kerouac", "Allen Ginsberg", "William Burroughs", "Ernest Hemingway"], correctAnswer: "Jack Kerouac" },
  { category: "Arte", difficulty: "Medio", question: "¿Qué artista cortó su oreja?", options: ["Gaugin", "Van Gogh", "Cézanne", "Toulouse-Lautrec"], correctAnswer: "Van Gogh" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'Rayuela'?", options: ["Cortázar", "Borges", "Bioy Casares", "Sábato"], correctAnswer: "Cortázar" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién pintó 'El nacimiento de Venus'?", options: ["Botticelli", "Leonardo", "Rafael", "Tiziano"], correctAnswer: "Botticelli" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién compuso 'La flauta mágica'?", options: ["Mozart", "Beethoven", "Verdi", "Wagner"], correctAnswer: "Mozart" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'El viejo y el mar'?", options: ["Faulkner", "Hemingway", "Steinbeck", "Fitzgerald"], correctAnswer: "Hemingway" },
  { category: "Arte", difficulty: "Medio", question: "¿Qué escultura es famosa de Miguel Ángel?", options: ["El Pensador", "David", "El Beso", "La Piedad"], correctAnswer: "David" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién es autor de 'La casa de los espíritus'?", options: ["Isabel Allende", "Laura Esquivel", "Elena Poniatowska", "Rosario Castellanos"], correctAnswer: "Isabel Allende" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'El proceso'?", options: ["Kafka", "Camus", "Sartre", "Beckett"], correctAnswer: "Kafka" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién compuso 'Carmen'?", options: ["Bizet", "Puccini", "Verdi", "Rossini"], correctAnswer: "Bizet" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién es el autor de 'La tregua'?", options: ["Benedetti", "Neruda", "Cortázar", "García Márquez"], correctAnswer: "Benedetti" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'Frankenstein'?", options: ["Mary Shelley", "Bram Stoker", "Edgar Allan Poe", "H.G. Wells"], correctAnswer: "Mary Shelley" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién es el autor de 'La filosofía en el tocador'?", options: ["Sade", "Rousseau", "Voltaire", "Diderot"], correctAnswer: "Sade" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién compuso 'El lago de los cisnes'?", options: ["Chaikovski", "Rajmáninov", "Stravinski", "Prokófiev"], correctAnswer: "Chaikovski" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'El nombre de la rosa'?", options: ["Umberto Eco", "Italo Calvino", "Borgues", "Tabucchi"], correctAnswer: "Umberto Eco" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién pintó 'Las señoritas de Avignon'?", options: ["Picasso", "Matisse", "Braque", "Modigliani"], correctAnswer: "Picasso" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'La colmena'?", options: ["Cela", "Delibes", "Galdós", "Unamuno"], correctAnswer: "Cela" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién es el autor de 'La ciudad y los perros'?", options: ["Vargas Llosa", "García Márquez", "Borges", "Fuentes"], correctAnswer: "Vargas Llosa" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién compuso 'La primavera' (sinfonía)?", options: ["Beethoven", "Schumann", "Mendelssohn", "Brahms"], correctAnswer: "Schumann" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'Crónica de una muerte anunciada'?", options: ["García Márquez", "Vargas Llosa", "Borges", "Cortázar"], correctAnswer: "García Márquez" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién pintó 'Los fusilamientos del 3 de mayo'?", options: ["Goya", "Velázquez", "Picasso", "Dalí"], correctAnswer: "Goya" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién es el autor de 'La dama de las camelias'?", options: ["Dumas (hijo)", "Victor Hugo", "Balzac", "Flaubert"], correctAnswer: "Dumas (hijo)" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién escribió 'La guerra y la paz'?", options: ["Dostoievski", "Tolstói", "Chéjov", "Gogol"], correctAnswer: "Tolstói" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién compuso 'Las bodas de Fígaro'?", options: ["Mozart", "Beethoven", "Verdi", "Rossini"], correctAnswer: "Mozart" },
  { category: "Arte", difficulty: "Medio", question: "¿Quién es el autor de 'Lazarillo de Tormes'?", options: ["Anónimo", "Cervantes", "Quevedo", "Alemán"], correctAnswer: "Anónimo" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién pintó 'El jardín de las delicias'?", options: ["El Bosco", "Bruegel", "Dalí", "Durero"], correctAnswer: "El Bosco" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién escribió 'Ulises'?", options: ["James Joyce", "Virginia Woolf", "Samuel Beckett", "T.S. Eliot"], correctAnswer: "James Joyce" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién compuso 'La consagración de la primavera'?", options: ["Stravinski", "Debussy", "Ravel", "Bartók"], correctAnswer: "Stravinski" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién es el autor de 'La bola de cristal' (obra filosófica)?", options: ["Sartre", "Camus", "Heidegger", "Husserl"], correctAnswer: "Sartre" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién escribió 'Pedro Páramo'?", options: ["Juan Rulfo", "Carlos Fuentes", "Octavio Paz", "Elena Garro"], correctAnswer: "Juan Rulfo" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién pintó 'El tres de mayo de 1808'?", options: ["Goya", "Velázquez", "Murillo", "Greco"], correctAnswer: "Goya" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién escribió 'La edad de la razón'?", options: ["Sartre", "Camus", "Beauvoir", "Merleau-Ponty"], correctAnswer: "Sartre" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién compuso 'La traviata'?", options: ["Verdi", "Puccini", "Rossini", "Donizetti"], correctAnswer: "Verdi" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién escribió 'Aura'?", options: ["Carlos Fuentes", "Cortázar", "García Márquez", "Vargas Llosa"], correctAnswer: "Carlos Fuentes" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién pintó 'El ángel caído'?", options: ["Picasso", "Cabanel", "Dalí", "Mateo Cerezo"], correctAnswer: "Cabanel" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién es el autor de 'El aleph'?", options: ["Borges", "Cortázar", "Bioy Casares", "Silvina Ocampo"], correctAnswer: "Borges" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién compuso 'Messiah'?", options: ["Händel", "Bach", "Vivaldi", "Telemann"], correctAnswer: "Händel" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién pintó 'El entierro del conde de Orgaz'?", options: ["El Greco", "Velázquez", "Goya", "Murillo"], correctAnswer: "El Greco" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién escribió 'La dama boba'?", options: ["Lope de Vega", "Calderón", "Tirso", "Moreto"], correctAnswer: "Lope de Vega" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién compuso 'Aida'?", options: ["Verdi", "Puccini", "Bellini", "Donizetti"], correctAnswer: "Verdi" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién pintó 'La liberty guiando al pueblo'?", options: ["Delacroix", "Géricault", "David", "Ingres"], correctAnswer: "Delacroix" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién escribió 'Tirano Banderas'?", options: ["Valle-Inclán", "Baroja", "Azorín", "Unamuno"], correctAnswer: "Valle-Inclán" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién es autor de 'Niebla'?", options: ["Unamuno", "Azorín", "Baroja", "Valle-Inclán"], correctAnswer: "Unamuno" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién compuso 'Las bodas de Fígaro'?", options: ["Mozart", "Rossini", "Verdi", "Puccini"], correctAnswer: "Mozart" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién escribió 'Luces de Bohemia'?", options: ["Valle-Inclán", "Lorca", "Alberti", "Cernuda"], correctAnswer: "Valle-Inclán" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién es autor de 'La galatea'?", options: ["Cervantes", "Lope", "Góngora", "Quevedo"], correctAnswer: "Cervantes" },
  { category: "Arte", difficulty: "Dificil", question: "¿Quién compuso 'Las estaciones' (oratorio)?", options: ["Haydn", "Händel", "Bach", "Mozart"], correctAnswer: "Haydn" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién pintó 'Las tres gracias'?", options: ["Rubens", "Rafael", "Tiziano", "Botticelli"], correctAnswer: "Rubens" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién escribió 'Ficciones'?", options: ["Borges", "Cortázar", "Bioy Casares", "Silvina Ocampo"], correctAnswer: "Borges" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién compuso 'Polovtsian Dances'?", options: ["Borodin", "Rimski-Kórsakov", "Músorgski", "Cui"], correctAnswer: "Borodin" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién escribió 'La montaña mágica'?", options: ["Thomas Mann", "Hermann Hesse", "Robert Musil", "Franz Kafka"], correctAnswer: "Thomas Mann" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién pintó 'El caballero de la mano en el pecho'?", options: ["El Greco", "Velázquez", "Goya", "Zurbarán"], correctAnswer: "El Greco" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién compuso 'La enfermedad del niño' (ópera)?", options: ["Berg", "Schoenberg", "Webern", "Hindemith"], correctAnswer: "Berg" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién escribió 'W ou le souvenir d'enfance'?", options: ["Perec", "Modiano", "Le Clézio", "Houellebecq"], correctAnswer: "Perec" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién pintó 'La bodega de la rue de la Goutte d'Or'?", options: ["Van Gogh", "Cézanne", "Toulouse-Lautrec", "Signac"], correctAnswer: "Van Gogh" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién compuso 'Wozzeck'?", options: ["Berg", "Schoenberg", "Webern", "Hindemith"], correctAnswer: "Berg" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién escribió 'Los gozos y las sombras'?", options: ["Gonzalo Torrente Ballester", "Cela", "Delibes", "Goytisolo"], correctAnswer: "Gonzalo Torrente Ballester" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién pintó 'El descendimiento' (Van der Weyden)?", options: ["Van der Weyden", "Van Eyck", "Memling", "Bosch"], correctAnswer: "Van der Weyden" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién compuso 'Pelleas et Melisande'?", options: ["Debussy", "Fauré", "Schoenberg", "Ravel"], correctAnswer: "Debussy" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién escribió 'Finnegans Wake'?", options: ["James Joyce", "Samuel Beckett", "Ezra Pound", "T.S. Eliot"], correctAnswer: "James Joyce" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién pintó 'La maja vestida' y 'La maja desnuda'?", options: ["Goya", "Velázquez", "Greco", "Picasso"], correctAnswer: "Goya" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién compuso 'Petrushka'?", options: ["Stravinski", "Prokófiev", "Rajmáninov", "Chaikovski"], correctAnswer: "Stravinski" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién escribió 'La narración de Arthur Gordon Pym'?", options: ["Edgar Allan Poe", "Herman Melville", "Mark Twain", "Jules Verne"], correctAnswer: "Edgar Allan Poe" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién es el autor de 'Cuentos de la selva'?", options: ["Horacio Quiroga", "García Márquez", "Rulfo", "Borges"], correctAnswer: "Horacio Quiroga" },
  { category: "Arte", difficulty: "Experto", question: "¿Quién pintó 'Los embajadores'?", options: ["Holbein", "Cranach", "Durero", "Bruegel"], correctAnswer: "Holbein" },
]

export const ARTE_QUESTIONS: QuestionSeed[] = RAW.map((q, i) => ({
  ...q,
  uuid: `q-arte-${(i + 1).toString().padStart(4, "0")}`,
}))
