// Ciencia — 100+ preguntas
import type { QuestionSeed } from "../questions"

const RAW: Omit<QuestionSeed, "uuid">[] = [
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es el símbolo químico del agua?", options: ["O2", "H2O", "CO2", "HO"], correctAnswer: "H2O" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuántos planetas tiene el Sistema Solar?", options: ["7", "8", "9", "10"], correctAnswer: "8" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Qué planeta es conocido como el Planeta Rojo?", options: ["Venus", "Marte", "Júpiter", "Saturno"], correctAnswer: "Marte" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es el órgano más grande del cuerpo humano?", options: ["Hígado", "Cerebro", "Piel", "Pulmones"], correctAnswer: "Piel" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Qué gas respiramos para vivir?", options: ["Nitrógeno", "Oxígeno", "Hidrógeno", "Dióxido de carbono"], correctAnswer: "Oxígeno" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es el símbolo químico del oro?", options: ["Au", "Ag", "Go", "Or"], correctAnswer: "Au" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuántos huesos tiene el cuerpo humano adulto?", options: ["186", "206", "226", "246"], correctAnswer: "206" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Qué planeta es el más cercano al Sol?", options: ["Venus", "Tierra", "Mercurio", "Marte"], correctAnswer: "Mercurio" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es el animal más grande del mundo?", options: ["Elefante", "Ballena azul", "Tiburón ballena", "Jirafa"], correctAnswer: "Ballena azul" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es la velocidad de la luz (aprox)?", options: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "30,000 km/s"], correctAnswer: "300,000 km/s" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es la fórmula del dióxido de carbono?", options: ["CO", "CO2", "C2O", "C2O2"], correctAnswer: "CO2" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Qué órgano bombea la sangre?", options: ["Pulmones", "Hígado", "Corazón", "Riñones"], correctAnswer: "Corazón" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es el planeta más grande del Sistema Solar?", options: ["Saturno", "Júpiter", "Neptuno", "Urano"], correctAnswer: "Júpiter" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Qué tipo de animal es una rana?", options: ["Mamífero", "Reptil", "Anfibio", "Pez"], correctAnswer: "Anfibio" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es la galaxia donde vivimos?", options: ["Andrómeda", "Vía Láctea", "Triángulo", "Sombrero"], correctAnswer: "Vía Láctea" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuántos corazones tiene un pulpo?", options: ["1", "2", "3", "4"], correctAnswer: "3" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es el metal líquido a temperatura ambiente?", options: ["Mercurio", "Plomo", "Hierro", "Cobre"], correctAnswer: "Mercurio" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Qué planta produce el oxígeno que respiramos?", options: ["Hongos", "Algas", "Plantas verdes", "Todas las anteriores"], correctAnswer: "Todas las anteriores" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuántas patas tiene una araña?", options: ["6", "8", "10", "12"], correctAnswer: "8" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es el animal terrestre más rápido?", options: ["León", "Guepardo", "Caballo", "Antílope"], correctAnswer: "Guepardo" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuál es el símbolo del oxígeno?", options: ["O", "Ox", "Og", "On"], correctAnswer: "O" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Qué órgano procesa la sangre para limpiarla?", options: ["Hígado", "Bazo", "Riñones", "Páncreas"], correctAnswer: "Riñones" },
  { category: "Ciencia", difficulty: "Facil", question: "¿En qué estado está el helado?", options: ["Sólido", "Líquido", "Gaseoso", "Plasma"], correctAnswer: "Sólido" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Cuántos litros tiene un metro cúbico?", options: ["100", "500", "1000", "10000"], correctAnswer: "1000" },
  { category: "Ciencia", difficulty: "Facil", question: "¿Qué estudia la botánica?", options: ["Animales", "Plantas", "Rocas", "Estrellas"], correctAnswer: "Plantas" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el elemento más abundante en el universo?", options: ["Oxígeno", "Carbono", "Hidrógeno", "Helio"], correctAnswer: "Hidrógeno" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el pH del agua pura?", options: ["5", "7", "9", "10"], correctAnswer: "7" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Quién formuló la teoría de la relatividad?", options: ["Newton", "Einstein", "Hawking", "Tesla"], correctAnswer: "Einstein" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es la unidad de medida de la resistencia eléctrica?", options: ["Voltio", "Amperio", "Ohmio", "Watio"], correctAnswer: "Ohmio" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué órgano produce la insulina?", options: ["Hígado", "Páncreas", "Tiroides", "Riñones"], correctAnswer: "Páncreas" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es la velocidad del sonido en el aire (aprox)?", options: ["340 m/s", "540 m/s", "740 m/s", "1000 m/s"], correctAnswer: "340 m/s" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuántos cromosomas tiene el ser humano?", options: ["44", "46", "48", "50"], correctAnswer: "46" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué científico propuso las leyes del movimiento?", options: ["Galileo", "Newton", "Einstein", "Kepler"], correctAnswer: "Newton" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué parte de la célula contiene el ADN?", options: ["Citoplasma", "Mitocondrias", "Núcleo", "Ribosomas"], correctAnswer: "Núcleo" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es la estrella más cercana a la Tierra (no el Sol)?", options: ["Sirio", "Alfa Centauri", "Polaris", "Betelgeuse"], correctAnswer: "Alfa Centauri" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué gas causa el efecto invernadero principal?", options: ["Oxígeno", "Nitrógeno", "CO2", "Helio"], correctAnswer: "CO2" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el metal más ligero?", options: ["Aluminio", "Litio", "Titanio", "Magnesio"], correctAnswer: "Litio" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué tipo de energía produce el Sol?", options: ["Química", "Nuclear", "Eléctrica", "Mecánica"], correctAnswer: "Nuclear" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el planeta más caliente del Sistema Solar?", options: ["Mercurio", "Venus", "Marte", "Tierra"], correctAnswer: "Venus" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué científico descubrió la penicilina?", options: ["Pasteur", "Fleming", "Curie", "Mendel"], correctAnswer: "Fleming" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el grupo de animales más numeroso?", options: ["Mamíferos", "Insectos", "Aves", "Peces"], correctAnswer: "Insectos" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué órgano es responsable del sentido del olfato?", options: ["Ojo", "Oído", "Nariz", "Lengua"], correctAnswer: "Nariz" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es la capa más externa de la Tierra?", options: ["Manto", "Núcleo", "Corteza", "Litosfera"], correctAnswer: "Corteza" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuántos años luz mide aproximadamente la Vía Láctea?", options: ["10,000", "100,000", "1,000,000", "10,000,000"], correctAnswer: "100,000" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el componente principal del Sol?", options: ["Helio", "Hidrógeno", "Oxígeno", "Carbono"], correctAnswer: "Hidrógeno" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué proceso usan las plantas para hacer energía?", options: ["Respiración", "Fotosíntesis", "Digestión", "Transpiración"], correctAnswer: "Fotosíntesis" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el animal con el cerebro más grande?", options: ["Elefante", "Cachalote", "Humano", "Delfín"], correctAnswer: "Cachalote" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué número atómico tiene el carbono?", options: ["4", "6", "8", "12"], correctAnswer: "6" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es la temperatura de fusión del hielo en °C?", options: ["-10", "0", "10", "32"], correctAnswer: "0" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué tipo de onda es el sonido?", options: ["Electromagnética", "Mecánica longitudinal", "Transversal", "Cuántica"], correctAnswer: "Mecánica longitudinal" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuántas fases tiene la Luna?", options: ["2", "4", "6", "8"], correctAnswer: "4" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el símbolo del sodio?", options: ["S", "So", "Na", "N"], correctAnswer: "Na" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el hueso más largo del cuerpo humano?", options: ["Tibia", "Fémur", "Húmero", "Peroné"], correctAnswer: "Fémur" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué temperatura es el cero absoluto en °C?", options: ["-100°", "-273°", "-500°", "-1000°"], correctAnswer: "-273°" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el planeta con más lunas conocidas?", options: ["Júpiter", "Saturno", "Urano", "Neptuno"], correctAnswer: "Saturno" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué pigmento da color verde a las plantas?", options: ["Caroteno", "Clorofila", "Antocianina", "Xantófila"], correctAnswer: "Clorofila" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el mineral más duro de la Tierra?", options: ["Oro", "Hierro", "Diamante", "Cuarzo"], correctAnswer: "Diamante" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuántos años tarda Saturno en orbitar el Sol?", options: ["12", "29", "84", "165"], correctAnswer: "29" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Qué es el HCl?", options: ["Ácido sulfúrico", "Ácido clorhídrico", "Ácido nítrico", "Sal común"], correctAnswer: "Ácido clorhídrico" },
  { category: "Ciencia", difficulty: "Medio", question: "¿Cuál es el componente principal del aire?", options: ["Oxígeno", "Nitrógeno", "CO2", "Argón"], correctAnswer: "Nitrógeno" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es la constante de Planck (aprox)?", options: ["6.6 × 10^-34 J·s", "3.0 × 10^8 m/s", "9.8 m/s²", "1.6 × 10^-19 J"], correctAnswer: "6.6 × 10^-34 J·s" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Qué partícula subatómica tiene carga negativa?", options: ["Protón", "Neutrón", "Electrón", "Fotón"], correctAnswer: "Electrón" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es el isótopo más común del carbono?", options: ["C-12", "C-13", "C-14", "C-16"], correctAnswer: "C-12" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Quién propuso el modelo de doble hélice del ADN?", options: ["Mendel", "Watson y Crick", "Pasteur", "Darwin"], correctAnswer: "Watson y Crick" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es la cuarta dimensión (en relatividad)?", options: ["Espacio", "Tiempo", "Masa", "Energía"], correctAnswer: "Tiempo" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es la velocidad de escape de la Tierra (aprox)?", options: ["11.2 km/s", "7.9 km/s", "15.0 km/s", "20.0 km/s"], correctAnswer: "11.2 km/s" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Qué tipo de célula no tiene núcleo?", options: ["Animal", "Vegetal", "Procariota", "Hongo"], correctAnswer: "Procariota" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es la fórmula del ácido sulfúrico?", options: ["H2SO4", "HCl", "HNO3", "H3PO4"], correctAnswer: "H2SO4" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es la edad aproximada del universo?", options: ["10 mil millones de años", "13.8 mil millones de años", "20 mil millones de años", "100 mil millones de años"], correctAnswer: "13.8 mil millones de años" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es la estrella más cercana al Sistema Solar?", options: ["Sirio", "Alfa Centauri", "Polaris", "Sol"], correctAnswer: "Sol" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Qué tipo de radiación tiene más energía?", options: ["Infrarroja", "Visible", "Ultravioleta", "Rayos gamma"], correctAnswer: "Rayos gamma" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es el punto de ebullición del agua en la cima del Everest?", options: ["100°C", "95°C", "70°C", "50°C"], correctAnswer: "70°C" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Qué ley describe la fuerza entre dos cargas eléctricas?", options: ["Ley de Ohm", "Ley de Coulomb", "Ley de Newton", "Ley de Kepler"], correctAnswer: "Ley de Coulomb" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es el hueso más pequeño del cuerpo humano?", options: ["Estribo", "Martillo", "Yunque", "Fémur"], correctAnswer: "Estribo" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es la función principal de los glóbulos rojos?", options: ["Combatir infecciones", "Transportar oxígeno", "Coagular sangre", "Producir hormonas"], correctAnswer: "Transportar oxígeno" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es el nombre del proceso de división celular que produce gametos?", options: ["Mitosis", "Meiosis", "Citocinesis", "Apoptosis"], correctAnswer: "Meiosis" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es el símbolo del potasio?", options: ["P", "Po", "K", "Pt"], correctAnswer: "K" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es el metal más conductor de electricidad?", options: ["Cobre", "Plata", "Oro", "Aluminio"], correctAnswer: "Plata" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es el segundo elemento más abundante en la corteza terrestre?", options: ["Oxígeno", "Silicio", "Aluminio", "Hierro"], correctAnswer: "Silicio" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Qué tipo de roca es el granito?", options: ["Sedimentaria", "Ígnea", "Metamórfica", "Volcánica"], correctAnswer: "Ígnea" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es la velocidad orbital de la Tierra alrededor del Sol (aprox)?", options: ["30 km/s", "100 km/s", "300 km/s", "1000 km/s"], correctAnswer: "30 km/s" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es la principal función del hígado?", options: ["Bombear sangre", "Filtrar toxinas", "Producir insulina", "Digerir fibra"], correctAnswer: "Filtrar toxinas" },
  { category: "Ciencia", difficulty: "Dificil", question: "¿Cuál es el tamaño aproximado de un átomo?", options: ["10^-10 m", "10^-15 m", "10^-20 m", "10^-5 m"], correctAnswer: "10^-10 m" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Cuál es la constante de gravitación universal (G)?", options: ["6.67 × 10^-11 N·m²/kg²", "9.8 m/s²", "3 × 10^8 m/s", "1.6 × 10^-19 C"], correctAnswer: "6.67 × 10^-11 N·m²/kg²" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Qué partícula es responsable de la fuerza débil nuclear?", options: ["Fotón", "Gluón", "Bosones W y Z", "Gravitón"], correctAnswer: "Bosones W y Z" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Cuál es la masa del electrón (aprox)?", options: ["9.1 × 10^-31 kg", "1.67 × 10^-27 kg", "1.6 × 10^-19 kg", "9.1 × 10^-15 kg"], correctAnswer: "9.1 × 10^-31 kg" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Qué teoría describe el comportamiento de partículas subatómicas?", options: ["Relatividad", "Mecánica cuántica", "Termodinámica", "Cinemática"], correctAnswer: "Mecánica cuántica" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Cuál es la entropía de un sistema en el cero absoluto?", options: ["Máxima", "Cero", "Infinita", "Indefinida"], correctAnswer: "Cero" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Qué cantidad se conserva en una reacción nuclear?", options: ["Masa", "Energía", "Masa-energía", "Carga"], correctAnswer: "Masa-energía" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Qué ecuación describe la equivalencia entre masa y energía?", options: ["E = mc", "E = mc²", "E = m²c", "E = m/c²"], correctAnswer: "E = mc²" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Cuál es la constante de Avogadro?", options: ["6.022 × 10^23", "3.14 × 10^8", "9.8 × 10^-3", "1.6 × 10^-19"], correctAnswer: "6.022 × 10^23" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Qué partícula media la fuerza electromagnética?", options: ["Gluón", "Fotón", "Bosón Z", "Gravitón"], correctAnswer: "Fotón" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Cuál es el principio de incertidumbre de Heisenberg?", options: ["Δx · Δp ≥ ℏ/2", "E = mc²", "F = ma", "PV = nRT"], correctAnswer: "Δx · Δp ≥ ℏ/2" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Cuál es el nombre del bosón que da masa a las partículas?", options: ["Bosón de gauge", "Bosón de Higgs", "Bosón W", "Bosón Z"], correctAnswer: "Bosón de Higgs" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Qué número cuántico describe la forma del orbital?", options: ["n", "l", "m", "s"], correctAnswer: "l" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Cuál es el número de neutrinos en el Modelo Estándar?", options: ["3", "6", "12", "24"], correctAnswer: "3" },
  { category: "Ciencia", difficulty: "Experto", question: "¿Cuál es el nombre del límite donde nada puede escapar de un agujero negro?", options: ["Horizonte de sucesos", "Singularidad", "Ergosfera", " Fotosfera"], correctAnswer: "Horizonte de sucesos" },
]

export const CIENCIA_QUESTIONS: QuestionSeed[] = RAW.map((q, i) => ({
  ...q,
  uuid: `q-cien-${(i + 1).toString().padStart(4, "0")}`,
}))
