// Geografía — 100+ preguntas
import type { QuestionSeed } from "../questions"

const RAW: Omit<QuestionSeed, "uuid">[] = [
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es la capital de Francia?", options: ["Berlín", "Madrid", "París", "Roma"], correctAnswer: "París" },
  { category: "Geografia", difficulty: "Facil", question: "¿En qué continente está Egipto?", options: ["Asia", "África", "Europa", "Oceanía"], correctAnswer: "África" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es el río más largo del mundo?", options: ["Nilo", "Amazonas", "Misisipi", "Yangtsé"], correctAnswer: "Amazonas" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es la capital de Japón?", options: ["Pekín", "Tokio", "Seúl", "Bangkok"], correctAnswer: "Tokio" },
  { category: "Geografia", difficulty: "Facil", question: "¿En qué país está el Monte Everest?", options: ["India", "China", "Nepal", "Pakistán"], correctAnswer: "Nepal" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuántos continentes hay?", options: ["5", "6", "7", "8"], correctAnswer: "7" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es la capital de Argentina?", options: ["Lima", "Santiago", "Buenos Aires", "Montevideo"], correctAnswer: "Buenos Aires" },
  { category: "Geografia", difficulty: "Facil", question: "¿En qué océano está Hawaii?", options: ["Atlántico", "Pacífico", "Índico", "Ártico"], correctAnswer: "Pacífico" },
  { category: "Geografia", difficulty: "Facil", question: "¿Qué país tiene más habitantes?", options: ["Rusia", "India", "China", "Estados Unidos"], correctAnswer: "India" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es la capital de Italia?", options: ["Milán", "Roma", "Venecia", "Florencia"], correctAnswer: "Roma" },
  { category: "Geografia", difficulty: "Facil", question: "¿Qué país tiene forma de bota?", options: ["Grecia", "Italia", "España", "Portugal"], correctAnswer: "Italia" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es la capital de Brasil?", options: ["Río de Janeiro", "São Paulo", "Brasilia", "Salvador"], correctAnswer: "Brasilia" },
  { category: "Geografia", difficulty: "Facil", question: "¿Qué continente es el más grande?", options: ["África", "Asia", "América", "Europa"], correctAnswer: "Asia" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es el océano más grande?", options: ["Atlántico", "Índico", "Pacífico", "Ártico"], correctAnswer: "Pacífico" },
  { category: "Geografia", difficulty: "Facil", question: "¿En qué país está la Torre Eiffel?", options: ["Inglaterra", "Francia", "Italia", "España"], correctAnswer: "Francia" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es la capital de España?", options: ["Barcelona", "Sevilla", "Madrid", "Valencia"], correctAnswer: "Madrid" },
  { category: "Geografia", difficulty: "Facil", question: "¿En qué continente está Australia?", options: ["Asia", "Oceanía", "África", "América"], correctAnswer: "Oceanía" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es el desierto más grande del mundo?", options: ["Sahara", "Gobi", "Atacama", "Antártico"], correctAnswer: "Antártico" },
  { category: "Geografia", difficulty: "Facil", question: "¿En qué país está el Big Ben?", options: ["Francia", "Inglaterra", "Italia", "España"], correctAnswer: "Inglaterra" },
  { category: "Geografia", difficulty: "Facil", question: "¿Qué país es conocido como 'El País del Sol Naciente'?", options: ["China", "Corea", "Japón", "Tailandia"], correctAnswer: "Japón" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es la capital de México?", options: ["Guadalajara", "Monterrey", "Ciudad de México", "Cancún"], correctAnswer: "Ciudad de México" },
  { category: "Geografia", difficulty: "Facil", question: "¿En qué país está el Coliseo Romano?", options: ["Grecia", "Italia", "España", "Francia"], correctAnswer: "Italia" },
  { category: "Geografia", difficulty: "Facil", question: "¿Qué país tiene la bandera con un arcoíris?", options: ["Bolivia", "Perú", "Ecuador", "Colombia"], correctAnswer: "Perú" },
  { category: "Geografia", difficulty: "Facil", question: "¿Cuál es la capital de Rusia?", options: ["San Petersburgo", "Moscú", "Kiev", "Kazán"], correctAnswer: "Moscú" },
  { category: "Geografia", difficulty: "Facil", question: "¿Qué país es una isla y un continente?", options: ["Madagascar", "Australia", "Japón", "Inglaterra"], correctAnswer: "Australia" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Australia?", options: ["Sídney", "Melbourne", "Canberra", "Brisbane"], correctAnswer: "Canberra" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué país está el monte Fuji?", options: ["China", "Japón", "Corea", "Vietnam"], correctAnswer: "Japón" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es el país más grande del mundo en área?", options: ["China", "Estados Unidos", "Canadá", "Rusia"], correctAnswer: "Rusia" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es el lago más grande del mundo?", options: ["Lago Superior", "Mar Caspio", "Lago Victoria", "Lago Baikal"], correctAnswer: "Mar Caspio" },
  { category: "Geografia", difficulty: "Medio", question: "¿Qué país tiene más zonas horarias?", options: ["Rusia", "Estados Unidos", "Francia", "China"], correctAnswer: "Francia" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Egipto?", options: ["Alejandría", "El Cairo", "Giza", "Luxor"], correctAnswer: "El Cairo" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué país está el Machu Picchu?", options: ["Bolivia", "Chile", "Perú", "Ecuador"], correctAnswer: "Perú" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Canadá?", options: ["Toronto", "Montreal", "Ottawa", "Vancouver"], correctAnswer: "Ottawa" },
  { category: "Geografia", difficulty: "Medio", question: "¿Qué río pasa por Londres?", options: ["Sena", "Támesis", "Rin", "Danubio"], correctAnswer: "Támesis" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué país está el Papa (Vaticano)?", options: ["España", "Italia", "Francia", "Portugal"], correctAnswer: "Italia" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Corea del Sur?", options: ["Pionyang", "Seúl", "Busan", "Incheon"], correctAnswer: "Seúl" },
  { category: "Geografia", difficulty: "Medio", question: "¿Qué país tiene forma de 'S' alargada?", options: ["Argentina", "Chile", "Noruega", "Italia"], correctAnswer: "Chile" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Sudáfrica (legislativa)?", options: ["Ciudad del Cabo", "Pretoria", "Bloemfontein", "Johannesburgo"], correctAnswer: "Ciudad del Cabo" },
  { category: "Geografia", difficulty: "Medio", question: "¿Qué país tiene los fiordos más famosos?", options: ["Suecia", "Finlandia", "Noruega", "Dinamarca"], correctAnswer: "Noruega" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Grecia?", options: ["Esparta", "Atenas", "Tebas", "Olimpia"], correctAnswer: "Atenas" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué país está el Kremlin?", options: ["Polonia", "Rusia", "Ucrania", "Bielorrusia"], correctAnswer: "Rusia" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es el país más pequeño del mundo?", options: ["Mónaco", "San Marino", "Vaticano", "Liechtenstein"], correctAnswer: "Vaticano" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué continente está Mongolia?", options: ["Europa", "Asia", "África", "América"], correctAnswer: "Asia" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de India?", options: ["Bombay", "Calcuta", "Nueva Delhi", "Bangalore"], correctAnswer: "Nueva Delhi" },
  { category: "Geografia", difficulty: "Medio", question: "¿Qué país es conocido por sus tulipanes?", options: ["Bélgica", "Holanda", "Dinamarca", "Suecia"], correctAnswer: "Holanda" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Portugal?", options: ["Oporto", "Lisboa", "Braga", "Faro"], correctAnswer: "Lisboa" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué país está el Kilimanjaro?", options: ["Kenia", "Tanzania", "Etiopía", "Uganda"], correctAnswer: "Tanzania" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Turquía?", options: ["Estambul", "Ankara", "Izmir", "Antalya"], correctAnswer: "Ankara" },
  { category: "Geografia", difficulty: "Medio", question: "¿Qué océano baña la costa este de África?", options: ["Atlántico", "Índico", "Pacífico", "Ártico"], correctAnswer: "Índico" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué país está el lago Baikal?", options: ["China", "Mongolia", "Rusia", "Kazajistán"], correctAnswer: "Rusia" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de China?", options: ["Shanghái", "Pekín", "Hong Kong", "Cantón"], correctAnswer: "Pekín" },
  { category: "Geografia", difficulty: "Medio", question: "¿Qué país tiene el mayor número de habitantes por km²?", options: ["China", "India", "Mónaco", "Bangladés"], correctAnswer: "Mónaco" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Cuba?", options: ["Santiago", "La Habana", "Camagüey", "Holguín"], correctAnswer: "La Habana" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué país está el Salar de Uyuni?", options: ["Perú", "Chile", "Bolivia", "Argentina"], correctAnswer: "Bolivia" },
  { category: "Geografia", difficulty: "Medio", question: "¿Qué país tiene el lago Ness?", options: ["Gales", "Escocia", "Irlanda", "Inglaterra"], correctAnswer: "Escocia" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Marruecos?", options: ["Casablanca", "Rabat", "Fez", "Marrakech"], correctAnswer: "Rabat" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué país está la Patagonia?", options: ["Chile", "Argentina", "Perú", "Bolivia"], correctAnswer: "Argentina" },
  { category: "Geografia", difficulty: "Medio", question: "¿Qué país africano fue el primero en independizarse?", options: ["Egipto", "Etiopía", "Liberia", "Ghana"], correctAnswer: "Etiopía" },
  { category: "Geografia", difficulty: "Medio", question: "¿Cuál es la capital de Indonesia?", options: ["Bali", "Yakarta", "Surabaya", "Bandung"], correctAnswer: "Yakarta" },
  { category: "Geografia", difficulty: "Medio", question: "¿En qué país está el monte Kilimanjaro?", options: ["Kenia", "Tanzania", "Etiopía", "Uganda"], correctAnswer: "Tanzania" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Mongolia?", options: ["Erdenet", "Ulan Bator", "Darhan", "Choibalsan"], correctAnswer: "Ulan Bator" },
  { category: "Geografia", difficulty: "Dificil", question: "¿En qué país está el lago Tanganika?", options: ["Tanzania", "Uganda", "Kenia", "Etiopía"], correctAnswer: "Tanzania" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Kazajistán?", options: ["Almaty", "Astana", "Shymkent", "Karaganda"], correctAnswer: "Astana" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Qué país tiene el mayor número de islas?", options: ["Indonesia", "Suecia", "Filipinas", "Japón"], correctAnswer: "Suecia" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Afganistán?", options: ["Kandahar", "Kabul", "Herat", "Mazar"], correctAnswer: "Kabul" },
  { category: "Geografia", difficulty: "Dificil", question: "¿En qué país está el delta del Okavango?", options: ["Sudáfrica", "Botsuana", "Namibia", "Zimbabue"], correctAnswer: "Botsuana" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Birmania (Myanmar)?", options: ["Rangún", "Naypyidó", "Mandalay", "Bago"], correctAnswer: "Naypyidó" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Qué río es el más caudaloso del mundo?", options: ["Nilo", "Amazonas", "Congo", "Yangtsé"], correctAnswer: "Amazonas" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Finlandia?", options: ["Turku", "Helsinki", "Tampere", "Oulu"], correctAnswer: "Helsinki" },
  { category: "Geografia", difficulty: "Dificil", question: "¿En qué país está el Monte Elbrus?", options: ["Turquía", "Rusia", "Georgia", "Armenia"], correctAnswer: "Rusia" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Suiza?", options: ["Zúrich", "Ginebra", "Berna", "Basilea"], correctAnswer: "Berna" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Qué país tiene el lago más profundo del mundo?", options: ["Rusia", "EE.UU.", "Canadá", "Tanzania"], correctAnswer: "Rusia" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Islandia?", options: ["Akureyri", "Reikiavik", "Keflavík", "Hafnarfjörður"], correctAnswer: "Reikiavik" },
  { category: "Geografia", difficulty: "Dificil", question: "¿En qué país está el estrecho de Bering?", options: ["Rusia y EE.UU.", "Canadá y EE.UU.", "Japón y Rusia", "Suecia y Finlandia"], correctAnswer: "Rusia y EE.UU." },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Nueva Zelanda?", options: ["Auckland", "Wellington", "Christchurch", "Hamilton"], correctAnswer: "Wellington" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Qué país es el más aislado geográficamente?", options: ["Australia", "Nueva Zelanda", "Islandia", "Madagascar"], correctAnswer: "Nueva Zelanda" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Vietnam?", options: ["Hanói", "Ho Chi Minh", "Da Nang", "Hue"], correctAnswer: "Hanói" },
  { category: "Geografia", difficulty: "Dificil", question: "¿En qué país está el monte Aconcagua?", options: ["Chile", "Argentina", "Perú", "Bolivia"], correctAnswer: "Argentina" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Etiopía?", options: ["Gondar", "Addis Abeba", "Dire Dawa", "Mek'ele"], correctAnswer: "Addis Abeba" },
  { category: "Geografia", difficulty: "Dificil", question: "¿En qué país está el lago Titicaca?", options: ["Bolivia y Perú", "Chile y Argentina", "Ecuador y Perú", "Bolivia y Chile"], correctAnswer: "Bolivia y Perú" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Cuál es la capital de Tailandia?", options: ["Chiang Mai", "Bangkok", "Phuket", "Pattaya"], correctAnswer: "Bangkok" },
  { category: "Geografia", difficulty: "Dificil", question: "¿Qué país tiene la mayor densidad de población?", options: ["Mónaco", "Singapur", "Bangladés", "Bahrein"], correctAnswer: "Mónaco" },
  { category: "Geografia", difficulty: "Experto", question: "¿Cuál es la capital de Liechtenstein?", options: ["Balzers", "Vaduz", "Schaan", "Triesen"], correctAnswer: "Vaduz" },
  { category: "Geografia", difficulty: "Experto", question: "¿En qué país está el lago Vostok?", options: ["Canadá", "Rusia", "Antártida", "Groenlandia"], correctAnswer: "Antártida" },
  { category: "Geografia", difficulty: "Experto", question: "¿Cuál es la capital de Surinam?", options: ["Paramaribo", "Nieuw Nickerie", "Moengo", "Albina"], correctAnswer: "Paramaribo" },
  { category: "Geografia", difficulty: "Experto", question: "¿En qué país está el monte Damavand?", options: ["Irak", "Irán", "Afganistán", "Pakistán"], correctAnswer: "Irán" },
  { category: "Geografia", difficulty: "Experto", question: "¿Cuál es la capital de Bhután?", options: ["Paro", "Timbu", "Punakha", "Wangdue"], correctAnswer: "Timbu" },
  { category: "Geografia", difficulty: "Experto", question: "¿Qué país tiene el lago más grande de agua dulce por superficie?", options: ["Rusia", "Canadá", "EE.UU.", "Brasil"], correctAnswer: "Canadá" },
  { category: "Geografia", difficulty: "Experto", question: "¿Cuál es la capital de Yibuti?", options: ["Ali Sabieh", "Yibuti", "Tadjoura", "Obock"], correctAnswer: "Yibuti" },
  { category: "Geografia", difficulty: "Experto", question: "¿En qué país está el cabo de Hornos?", options: ["Argentina", "Chile", "Antártida", "Sudáfrica"], correctAnswer: "Chile" },
  { category: "Geografia", difficulty: "Experto", question: "¿Cuál es la capital de Comoras?", options: ["Mutsamudu", "Moroni", "Fomboni", "Domoni"], correctAnswer: "Moroni" },
  { category: "Geografia", difficulty: "Experto", question: "¿Qué país tiene la costa más larga del mundo?", options: ["Rusia", "Canadá", "Australia", "Indonesia"], correctAnswer: "Canadá" },
  { category: "Geografia", difficulty: "Experto", question: "¿Cuál es la capital de Kiribati?", options: ["Bairiki", "South Tarawa", "Betio", "Bikenibeu"], correctAnswer: "South Tarawa" },
  { category: "Geografia", difficulty: "Experto", question: "¿En qué país está el pico Jaya?", options: ["Papúa Nueva Guinea", "Indonesia", "Filipinas", "Malasia"], correctAnswer: "Indonesia" },
  { category: "Geografia", difficulty: "Experto", question: "¿Cuál es la capital de Vanuatu?", options: ["Luganville", "Port Vila", "Norsup", "Isangel"], correctAnswer: "Port Vila" },
  { category: "Geografia", difficulty: "Experto", question: "¿Qué país tiene el mayor número de volcanes activos?", options: ["Japón", "Indonesia", "EE.UU.", "Islandia"], correctAnswer: "Indonesia" },
  { category: "Geografia", difficulty: "Experto", question: "¿Cuál es la capital de Tuvalu?", options: ["Vaiaku", "Funafuti", "Asau", "Fongafale"], correctAnswer: "Funafuti" },
  { category: "Geografia", difficulty: "Experto", question: "¿En qué país está el monte Ojos del Salado?", options: ["Chile", "Argentina", "Bolivia", "Perú"], correctAnswer: "Chile" },
  { category: "Geografia", difficulty: "Experto", question: "¿Cuál es la capital de Seychelles?", options: ["Victoria", "Anse Boileau", "Anse Royale", "Beau Vallon"], correctAnswer: "Victoria" },
]

export const GEOGRAFIA_QUESTIONS: QuestionSeed[] = RAW.map((q, i) => ({
  ...q,
  uuid: `q-geog-${(i + 1).toString().padStart(4, "0")}`,
}))
