// Historia — 100+ preguntas
import type { QuestionSeed } from "../questions"

const RAW: Omit<QuestionSeed, "uuid">[] = [
  { category: "Historia", difficulty: "Facil", question: "¿En qué año cayó el Muro de Berlín?", options: ["1987", "1989", "1991", "1993"], correctAnswer: "1989" },
  { category: "Historia", difficulty: "Facil", question: "¿Quién fue el primer presidente de Estados Unidos?", options: ["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"], correctAnswer: "George Washington" },
  { category: "Historia", difficulty: "Facil", question: "¿En qué año comenzó la Segunda Guerra Mundial?", options: ["1937", "1939", "1941", "1945"], correctAnswer: "1939" },
  { category: "Historia", difficulty: "Facil", question: "¿Qué civilización construyó Machu Picchu?", options: ["Azteca", "Maya", "Inca", "Olmeca"], correctAnswer: "Inca" },
  { category: "Historia", difficulty: "Facil", question: "¿Quién fue el primer emperador de Roma?", options: ["Julio César", "Augusto", "Nerón", "Trajano"], correctAnswer: "Augusto" },
  { category: "Historia", difficulty: "Facil", question: "¿En qué año llegó Colón a América?", options: ["1488", "1492", "1496", "1500"], correctAnswer: "1492" },
  { category: "Historia", difficulty: "Facil", question: "¿Qué reina egipcia se alió con Marco Antonio?", options: ["Nefertiti", "Cleopatra", "Hatshepsut", "Nefertari"], correctAnswer: "Cleopatra" },
  { category: "Historia", difficulty: "Facil", question: "¿En qué año terminó la Primera Guerra Mundial?", options: ["1916", "1917", "1918", "1919"], correctAnswer: "1918" },
  { category: "Historia", difficulty: "Facil", question: "¿Quién pintó la Capilla Sixtina?", options: ["Leonardo da Vinci", "Miguel Ángel", "Rafael", "Botticelli"], correctAnswer: "Miguel Ángel" },
  { category: "Historia", difficulty: "Facil", question: "¿Qué país construyó la Gran Muralla China?", options: ["Japón", "China", "Mongolia", "Corea"], correctAnswer: "China" },
  { category: "Historia", difficulty: "Facil", question: "¿Quién fue conocido como el 'Rey Sol'?", options: ["Luis XIV", "Luis XVI", "Carlos V", "Napoleón"], correctAnswer: "Luis XIV" },
  { category: "Historia", difficulty: "Facil", question: "¿En qué año se independizó Estados Unidos?", options: ["1776", "1783", "1789", "1791"], correctAnswer: "1776" },
  { category: "Historia", difficulty: "Facil", question: "¿Quién fue el líder de la Revolución Cubana?", options: ["Che Guevara", "Fidel Castro", "Camilo Cienfuegos", "Raúl Castro"], correctAnswer: "Fidel Castro" },
  { category: "Historia", difficulty: "Facil", question: "¿En qué año se hundió el Titanic?", options: ["1910", "1912", "1914", "1916"], correctAnswer: "1912" },
  { category: "Historia", difficulty: "Facil", question: "¿Qué imperio construyó el Coliseo Romano?", options: ["Griego", "Egipcio", "Romano", "Bizantino"], correctAnswer: "Romano" },
  { category: "Historia", difficulty: "Facil", question: "¿Quién fue el primer hombre en pisar la Luna?", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Michael Collins"], correctAnswer: "Neil Armstrong" },
  { category: "Historia", difficulty: "Facil", question: "¿En qué año terminó la Guerra Fría (simbólicamente)?", options: ["1989", "1991", "1993", "1995"], correctAnswer: "1991" },
  { category: "Historia", difficulty: "Facil", question: "¿Qué civilización inventó la escritura cuneiforme?", options: ["Egipcia", "Sumeria", "Griega", "Fenicia"], correctAnswer: "Sumeria" },
  { category: "Historia", difficulty: "Facil", question: "¿Quién fue el primer emperador de China?", options: ["Kublai Khan", "Qin Shi Huang", "Gengis Khan", "Sun Yat-sen"], correctAnswer: "Qin Shi Huang" },
  { category: "Historia", difficulty: "Facil", question: "¿Qué evento provocó el inicio de la Primera Guerra Mundial?", options: ["Asesinato de Francisco Fernando", "Invasión de Polonia", "Revolución Rusa", "Tratado de Versalles"], correctAnswer: "Asesinato de Francisco Fernando" },
  { category: "Historia", difficulty: "Facil", question: "¿Quién fue Simón Bolívar?", options: ["Libertador de Sudamérica", "Rey de España", "Conquistador de México", "Emperador de Brasil"], correctAnswer: "Libertador de Sudamérica" },
  { category: "Historia", difficulty: "Facil", question: "¿En qué año se firmó la Declaración de los Derechos del Hombre?", options: ["1776", "1789", "1791", "1793"], correctAnswer: "1789" },
  { category: "Historia", difficulty: "Facil", question: "¿Qué continente fue llamado 'Nuevo Mundo'?", options: ["Asia", "África", "América", "Oceanía"], correctAnswer: "América" },
  { category: "Historia", difficulty: "Facil", question: "¿Quién descubrió la penicilina?", options: ["Alexander Fleming", "Marie Curie", "Louis Pasteur", "Robert Koch"], correctAnswer: "Alexander Fleming" },
  { category: "Historia", difficulty: "Facil", question: "¿En qué año cayó el Imperio Romano de Occidente?", options: ["376 d.C.", "476 d.C.", "576 d.C.", "676 d.C."], correctAnswer: "476 d.C." },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue el último zar de Rusia?", options: ["Alejandro III", "Nicolás II", "Pedro el Grande", "Iván el Terrible"], correctAnswer: "Nicolás II" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se firmó la Magna Carta?", options: ["1199", "1215", "1265", "1305"], correctAnswer: "1215" },
  { category: "Historia", difficulty: "Medio", question: "¿Qué imperio tenía su capital en Constantinopla?", options: ["Imperio Romano", "Imperio Bizantino", "Imperio Otomano", "Imperio Persa"], correctAnswer: "Imperio Bizantino" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue el primer presidente de Sudáfrica post-apartheid?", options: ["F.W. de Klerk", "Nelson Mandela", "Thabo Mbeki", "Desmond Tutu"], correctAnswer: "Nelson Mandela" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se produjo la Revolución Francesa?", options: ["1789", "1792", "1795", "1799"], correctAnswer: "1789" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue conocido como 'El Libertador'?", options: ["San Martín", "Bolívar", "Sucre", "Hidalgo"], correctAnswer: "Bolívar" },
  { category: "Historia", difficulty: "Medio", question: "¿Qué rey francés fue guillotinado en 1793?", options: ["Luis XIV", "Luis XV", "Luis XVI", "Luis XVIII"], correctAnswer: "Luis XVI" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién conquistó el Imperio Azteca?", options: ["Pizarro", "Cortés", "Colón", "Magallanes"], correctAnswer: "Cortés" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se fundó Roma (según la leyenda)?", options: ["553 a.C.", "653 a.C.", "753 a.C.", "853 a.C."], correctAnswer: "753 a.C." },
  { category: "Historia", difficulty: "Medio", question: "¿Qué presidente estadounidense dimitió tras el Watergate?", options: ["Lyndon B. Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter"], correctAnswer: "Richard Nixon" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue el primer hombre en dar la vuelta al mundo?", options: ["Cristóbal Colón", "Hernando de Magallanes", "Vasco da Gama", "Francisco Pizarro"], correctAnswer: "Hernando de Magallanes" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se proclamó la Independencia de México?", options: ["1810", "1813", "1821", "1824"], correctAnswer: "1810" },
  { category: "Historia", difficulty: "Medio", question: "¿Qué civilización creó los Juegos Olímpicos?", options: ["Romana", "Egipcia", "Griega", "Persa"], correctAnswer: "Griega" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue Winston Churchill?", options: ["Presidente de EE.UU.", "Primer Ministro británico", "Rey de Inglaterra", "General alemán"], correctAnswer: "Primer Ministro británico" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se unificó Alemania?", options: ["1989", "1990", "1991", "1992"], correctAnswer: "1990" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue el líder nazi en la Segunda Guerra Mundial?", options: ["Heinrich Himmler", "Adolf Hitler", "Joseph Goebbels", "Hermann Göring"], correctAnswer: "Adolf Hitler" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año murió Mahatma Gandhi?", options: ["1945", "1947", "1948", "1950"], correctAnswer: "1948" },
  { category: "Historia", difficulty: "Medio", question: "¿Qué civilización construyó las pirámides de Giza?", options: ["Griega", "Egipcia", "Romana", "Persa"], correctAnswer: "Egipcia" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue la última faraona de Egipto?", options: ["Nefertiti", "Cleopatra VII", "Hatshepsut", "Tausert"], correctAnswer: "Cleopatra VII" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se abolió la esclavitud en EE.UU.?", options: ["1863", "1865", "1868", "1870"], correctAnswer: "1865" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue el padre de la democracia ateniense?", options: ["Pericles", "Solón", "Clístenes", "Dracón"], correctAnswer: "Clístenes" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se fundó la ONU?", options: ["1943", "1945", "1947", "1949"], correctAnswer: "1945" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue el primer líder de la Unión Soviética?", options: ["Lenin", "Stalin", "Trotsky", "Kruschev"], correctAnswer: "Lenin" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se firmó el Tratado de Tordesillas?", options: ["1492", "1494", "1496", "1500"], correctAnswer: "1494" },
  { category: "Historia", difficulty: "Medio", question: "¿Qué imperio fue derrotado en la Batalla de Lepanto?", options: ["Imperio Otomano", "Imperio Bizantino", "Imperio Persa", "Imperio Mongol"], correctAnswer: "Imperio Otomano" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién proclamó la República en Brasil?", options: ["Pedro I", "Pedro II", "Deodoro da Fonseca", "Getúlio Vargas"], correctAnswer: "Deodoro da Fonseca" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se produjo la Revolución de Octubre en Rusia?", options: ["1915", "1917", "1919", "1921"], correctAnswer: "1917" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se produjo la caída de Tenochtitlan?", options: ["1519", "1521", "1523", "1525"], correctAnswer: "1521" },
  { category: "Historia", difficulty: "Medio", question: "¿Qué presidente estadounidense fue asesinado en Dallas?", options: ["Lincoln", "Roosevelt", "Kennedy", "Nixon"], correctAnswer: "Kennedy" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue el fundador de la dinastía Ming?", options: ["Hongwu", "Yongle", "Zhu Di", "Kublai"], correctAnswer: "Hongwu" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se inauguró el Canal de Panamá?", options: ["1910", "1914", "1918", "1920"], correctAnswer: "1914" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién descubrió el mar del Sur (Pacífico) desde América?", options: ["Colón", "Núñez de Balboa", "Magallanes", "Pizarro"], correctAnswer: "Núñez de Balboa" },
  { category: "Historia", difficulty: "Medio", question: "¿Qué rey inglés tuvo seis esposas?", options: ["Enrique VII", "Enrique VIII", "Eduardo VI", "Carlos I"], correctAnswer: "Enrique VIII" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año comenzó la Revolución Industrial?", options: ["1650", "1750", "1850", "1950"], correctAnswer: "1750" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién escribió 'El Príncipe'?", options: ["Maquiavelo", "Tomás Moro", "Erasmo", "Bacon"], correctAnswer: "Maquiavelo" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se fundó la Compañía de Jesús?", options: ["1534", "1540", "1550", "1560"], correctAnswer: "1540" },
  { category: "Historia", difficulty: "Medio", question: "¿Qué presidente estadounidense lideró durante la Gran Depresión?", options: ["Hoover", "Roosevelt", "Truman", "Eisenhower"], correctAnswer: "Roosevelt" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se firmó la Constitución de los Estados Unidos?", options: ["1776", "1787", "1789", "1791"], correctAnswer: "1787" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién lideró la Campaña del Desierto en Argentina?", options: ["Mitre", "Roca", "Sarmiento", "Alsina"], correctAnswer: "Roca" },
  { category: "Historia", difficulty: "Medio", question: "¿En qué año se independizó Brasil?", options: ["1810", "1822", "1830", "1840"], correctAnswer: "1822" },
  { category: "Historia", difficulty: "Medio", question: "¿Quién fue el último gobernante romano de Occidente?", options: ["Rómulo Augústulo", "Julio Nepote", "Orestes", "Odoacro"], correctAnswer: "Rómulo Augústulo" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fue el fundador del Imperio Mongol?", options: ["Kublai Khan", "Gengis Khan", "Tamerlán", "Ogodai"], correctAnswer: "Gengis Khan" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se produjo la batalla de Las Navas de Tolosa?", options: ["1109", "1212", "1313", "1414"], correctAnswer: "1212" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fue el primer rey de la dinastía Borbón en España?", options: ["Felipe V", "Carlos III", "Fernando VI", "Carlos IV"], correctAnswer: "Felipe V" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se firmó la Paz de Westfalia?", options: ["1618", "1648", "1688", "1718"], correctAnswer: "1648" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fue el último emperador inca?", options: ["Atahualpa", "Huayna Cápac", "Túpac Amaru I", "Manco Inca"], correctAnswer: "Atahualpa" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se produjo la batalla de Waterloo?", options: ["1813", "1815", "1817", "1819"], correctAnswer: "1815" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fundó la República de Roma?", options: ["Lucio Junio Bruto", "Tarquinio el Soberbio", "Rómulo", "Numa Pompilio"], correctAnswer: "Lucio Junio Bruto" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se firmó el Tratado de Versalles?", options: ["1918", "1919", "1920", "1921"], correctAnswer: "1919" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fue el último emperador bizantino?", options: ["Constantino XI", "Justiniano I", "Basilio II", "Miguel VIII"], correctAnswer: "Constantino XI" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se proclamó la República en España por primera vez?", options: ["1868", "1873", "1874", "1880"], correctAnswer: "1873" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fue el primer emperador del Sacro Imperio Romano Germánico?", options: ["Carlomagno", "Otón I", "Federico Barbarroja", "Enrique IV"], correctAnswer: "Carlomagno" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se produjo la conquista de Granada?", options: ["1489", "1492", "1495", "1500"], correctAnswer: "1492" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fue la primera mujer en ganar un Premio Nobel?", options: ["Marie Curie", "Bertha von Suttner", "Selma Lagerlöf", "Pearl Buck"], correctAnswer: "Marie Curie" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se fundó la ciudad de Buenos Aires?", options: ["1536", "1580", "1610", "1640"], correctAnswer: "1580" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se produjo la batalla de San Quintín?", options: ["1557", "1559", "1567", "1577"], correctAnswer: "1557" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fue el primer virrey de la Nueva España?", options: ["Hernán Cortés", "Antonio de Mendoza", "Luis de Velasco", "Pedro de Alvarado"], correctAnswer: "Antonio de Mendoza" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se fundó la Universidad de Salamanca?", options: ["1130", "1218", "1300", "1400"], correctAnswer: "1218" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fue el primer faraón de Egipto?", options: ["Narmer", "Khufu", "Tutankamón", "Ramsés II"], correctAnswer: "Narmer" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se descubrió Tutankamón?", options: ["1912", "1922", "1932", "1942"], correctAnswer: "1922" },
  { category: "Historia", difficulty: "Dificil", question: "¿Qué rey español abdicó tras el motín de Aranjuez?", options: ["Fernando VII", "Carlos IV", "José Bonaparte", "Isabel II"], correctAnswer: "Carlos IV" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién fue el primer presidente de México?", options: ["Guadalupe Victoria", "Benito Juárez", "Porfirio Díaz", "Agustín de Iturbide"], correctAnswer: "Guadalupe Victoria" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se firmó la Constitución de Cádiz?", options: ["1810", "1812", "1814", "1816"], correctAnswer: "1812" },
  { category: "Historia", difficulty: "Dificil", question: "¿Quién lideró la rebelión de esclavos en Haití?", options: ["Toussaint Louverture", "Jean-Jacques Dessalines", "Henri Christophe", "Alexandre Pétion"], correctAnswer: "Toussaint Louverture" },
  { category: "Historia", difficulty: "Dificil", question: "¿Qué emperador romano legalizó el cristianismo?", options: ["Constantino", "Teodosio", "Juliano", "Valentiniano"], correctAnswer: "Constantino" },
  { category: "Historia", difficulty: "Dificil", question: "¿En qué año se firmó la Bula Inter Caetera?", options: ["1491", "1493", "1495", "1497"], correctAnswer: "1493" },
  { category: "Historia", difficulty: "Experto", question: "¿Quién fue el primer emperador del Japón (según la tradición)?", options: ["Jinmu", "Nintoku", "Suiko", "Kammu"], correctAnswer: "Jinmu" },
  { category: "Historia", difficulty: "Experto", question: "¿En qué año se produjo la batalla de Maratón?", options: ["490 a.C.", "480 a.C.", "470 a.C.", "460 a.C."], correctAnswer: "490 a.C." },
  { category: "Historia", difficulty: "Experto", question: "¿Quién fue el fundador de Cartago (según la leyenda)?", options: ["Dido", "Aníbal", "Asdrúbal", "Amílcar Barca"], correctAnswer: "Dido" },
  { category: "Historia", difficulty: "Experto", question: "¿En qué año se produjo el Cisma de Occidente?", options: ["1378", "1388", "1398", "1408"], correctAnswer: "1378" },
  { category: "Historia", difficulty: "Experto", question: "¿Quién fue el fundador del Imperio Bizantino?", options: ["Constantino I", "Justiniano I", "Heráclito", "Arcadio"], correctAnswer: "Constantino I" },
  { category: "Historia", difficulty: "Experto", question: "¿En qué año se descubrió América por primera vez (vikingos)?", options: ["700", "800", "900", "1000"], correctAnswer: "1000" },
  { category: "Historia", difficulty: "Experto", question: "¿Quién fue el primer rey visigodo de Toledo?", options: ["Leovigildo", "Atanagildo", "Recaredo", "Rodrigo"], correctAnswer: "Atanagildo" },
  { category: "Historia", difficulty: "Experto", question: "¿En qué año se produjo la conquista de Constantinopla por los turcos?", options: ["1435", "1453", "1473", "1493"], correctAnswer: "1453" },
  { category: "Historia", difficulty: "Experto", question: "¿Quién fue el fundador de la dinastía Carolingia?", options: ["Pipino el Breve", "Carlos Martel", "Carlomagno", "Ludovico Pío"], correctAnswer: "Pipino el Breve" },
  { category: "Historia", difficulty: "Experto", question: "¿En qué año se proclamó la Independencia de Haití?", options: ["1798", "1804", "1810", "1815"], correctAnswer: "1804" },
  { category: "Historia", difficulty: "Experto", question: "¿Quién fue el último virrey del Río de la Plata?", options: ["Baltasar Hidalgo de Cisneros", "Santiago de Liniers", "Rafael de Sobremonte", "Juan José de Vértiz"], correctAnswer: "Baltasar Hidalgo de Cisneros" },
  { category: "Historia", difficulty: "Experto", question: "¿En qué año se fundó el Reino de Asturias?", options: ["718", "722", "732", "742"], correctAnswer: "718" },
  { category: "Historia", difficulty: "Experto", question: "¿Quién fue el fundador del Imperio Aqueménida?", options: ["Ciro el Grande", "Darío I", "Jerjes", "Cambises"], correctAnswer: "Ciro el Grande" },
  { category: "Historia", difficulty: "Experto", question: "¿Quién fue el primer emperador del Brasil?", options: ["Pedro I", "Pedro II", "João VI", "Tiradentes"], correctAnswer: "Pedro I" },
]

export const HISTORIA_QUESTIONS: QuestionSeed[] = RAW.map((q, i) => ({
  ...q,
  uuid: `q-hist-${(i + 1).toString().padStart(4, "0")}`,
}))
