// Matemáticas — 100+ preguntas
import type { QuestionSeed } from "../questions"

const RAW: Omit<QuestionSeed, "uuid">[] = [
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuánto es 7 × 8?", options: ["54", "56", "58", "62"], correctAnswer: "56" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuál es la raíz cuadrada de 144?", options: ["10", "11", "12", "13"], correctAnswer: "12" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuántos lados tiene un triángulo?", options: ["2", "3", "4", "5"], correctAnswer: "3" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuánto es 25% de 200?", options: ["25", "50", "75", "100"], correctAnswer: "50" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuántos grados tiene un ángulo recto?", options: ["45", "60", "90", "180"], correctAnswer: "90" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuál es el número pi aproximado?", options: ["3.14", "3.41", "3.16", "3.61"], correctAnswer: "3.14" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuántos lados tiene un hexágono?", options: ["5", "6", "7", "8"], correctAnswer: "6" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuánto es 9 × 9?", options: ["72", "81", "90", "99"], correctAnswer: "81" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuántos minutos hay en 2 horas?", options: ["60", "100", "120", "180"], correctAnswer: "120" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuál es el resultado de 15 + 27?", options: ["32", "42", "52", "62"], correctAnswer: "42" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuántos segundos tiene un minuto?", options: ["30", "60", "100", "120"], correctAnswer: "60" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuánto es 100 ÷ 4?", options: ["20", "25", "30", "40"], correctAnswer: "25" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Qué número es impar?", options: ["12", "14", "17", "20"], correctAnswer: "17" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuántos lados tiene un cuadrado?", options: ["3", "4", "5", "6"], correctAnswer: "4" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuánto es 6 × 7?", options: ["36", "42", "48", "54"], correctAnswer: "42" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuál es el número par?", options: ["3", "7", "11", "14"], correctAnswer: "14" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuánto es 144 ÷ 12?", options: ["10", "11", "12", "14"], correctAnswer: "12" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuántos días tiene una semana?", options: ["5", "6", "7", "8"], correctAnswer: "7" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuánto es 5² (5 al cuadrado)?", options: ["10", "15", "25", "50"], correctAnswer: "25" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuántos meses tiene un año?", options: ["10", "11", "12", "13"], correctAnswer: "12" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuál es el doble de 25?", options: ["45", "50", "55", "75"], correctAnswer: "50" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuánto es 1000 ÷ 10?", options: ["10", "100", "1000", "10000"], correctAnswer: "100" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuántas horas tiene un día?", options: ["12", "24", "36", "48"], correctAnswer: "24" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuánto es 11 × 11?", options: ["111", "121", "131", "141"], correctAnswer: "121" },
  { category: "Matematicas", difficulty: "Facil", question: "¿Cuál es la mitad de 90?", options: ["30", "40", "45", "50"], correctAnswer: "45" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 12³?", options: ["144", "1244", "1728", "1444"], correctAnswer: "1728" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el logaritmo en base 10 de 1000?", options: ["1", "2", "3", "10"], correctAnswer: "3" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuántos grados tiene un ángulo llano?", options: ["90", "120", "180", "360"], correctAnswer: "180" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el valor de π (pi) redondeado a 2 decimales?", options: ["3.12", "3.14", "3.16", "3.18"], correctAnswer: "3.14" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el factorial de 5 (5!)?", options: ["25", "60", "120", "720"], correctAnswer: "120" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 7² + 3²?", options: ["52", "58", "62", "68"], correctAnswer: "58" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es la suma de los ángulos internos de un triángulo?", options: ["90°", "180°", "270°", "360°"], correctAnswer: "180°" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es la suma de los ángulos internos de un cuadrilátero?", options: ["180°", "270°", "360°", "720°"], correctAnswer: "360°" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el área de un cuadrado de lado 7?", options: ["14", "28", "49", "64"], correctAnswer: "49" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el perímetro de un rectángulo de 5×3?", options: ["8", "15", "16", "30"], correctAnswer: "16" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de (-3) × (-4)?", options: ["-12", "-7", "7", "12"], correctAnswer: "12" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el MCD de 12 y 18?", options: ["2", "3", "6", "9"], correctAnswer: "6" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el MCM de 4 y 6?", options: ["12", "18", "24", "48"], correctAnswer: "12" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 2⁵?", options: ["10", "16", "25", "32"], correctAnswer: "32" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 1/2 + 1/4?", options: ["1/6", "2/6", "3/4", "1"], correctAnswer: "3/4" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuánto es 15% de 80?", options: ["8", "12", "15", "20"], correctAnswer: "12" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es la raíz cúbica de 27?", options: ["3", "6", "9", "12"], correctAnswer: "3" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 0.5 × 0.5?", options: ["0.10", "0.25", "0.50", "1.00"], correctAnswer: "0.25" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuántos ceros tiene un millón?", options: ["5", "6", "7", "9"], correctAnswer: "6" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 100 - 37?", options: ["53", "63", "73", "83"], correctAnswer: "63" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 8 ÷ 0.5?", options: ["4", "8", "12", "16"], correctAnswer: "16" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el número primo entre 14 y 18?", options: ["15", "16", "17", "18"], correctAnswer: "17" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuánto es 3! (factorial)?", options: ["3", "6", "9", "12"], correctAnswer: "6" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 4³?", options: ["12", "24", "64", "144"], correctAnswer: "64" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuánto es 35% de 200?", options: ["35", "70", "100", "175"], correctAnswer: "70" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el perímetro de un círculo de radio 1 (π·d)?", options: ["π", "2π", "π²", "π/2"], correctAnswer: "2π" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuántas caras tiene un cubo?", options: ["4", "6", "8", "12"], correctAnswer: "6" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuántas aristas tiene un cubo?", options: ["6", "8", "12", "16"], correctAnswer: "12" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuántos vértices tiene un cubo?", options: ["6", "8", "10", "12"], correctAnswer: "8" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de log₂(8)?", options: ["2", "3", "4", "8"], correctAnswer: "3" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 1/3 + 1/3?", options: ["1/9", "2/3", "1", "2/6"], correctAnswer: "2/3" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el área de un círculo de radio 2?", options: ["2π", "4π", "8π", "16π"], correctAnswer: "4π" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 5! ÷ 3!?", options: ["10", "20", "60", "120"], correctAnswer: "20" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuántos lados tiene un octágono?", options: ["6", "7", "8", "9"], correctAnswer: "8" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 6² + 8²?", options: ["100", "120", "144", "196"], correctAnswer: "100" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es la hipotenusa de un triángulo con catetos 3 y 4?", options: ["5", "6", "7", "8"], correctAnswer: "5" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuántos grados tiene un ángulo completo (vuelta)?", options: ["180°", "270°", "360°", "720°"], correctAnswer: "360°" },
  { category: "Matematicas", difficulty: "Medio", question: "¿Cuál es el resultado de 0.25 ÷ 0.5?", options: ["0.5", "0.75", "1.0", "2.0"], correctAnswer: "0.5" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de 2¹⁰?", options: ["512", "1024", "2048", "4096"], correctAnswer: "1024" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es la derivada de x²?", options: ["x", "2x", "x³/3", "2"], correctAnswer: "2x" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de log₁₀(0.001)?", options: ["-3", "-1", "0", "1"], correctAnswer: "-3" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es la integral de 2x?", options: ["2", "x²", "x² + C", "2x²"], correctAnswer: "x² + C" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el seno de 30°?", options: ["0", "0.5", "0.707", "1"], correctAnswer: "0.5" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el coseno de 60°?", options: ["0", "0.5", "0.707", "1"], correctAnswer: "0.5" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de 7!?", options: ["720", "2520", "5040", "7200"], correctAnswer: "5040" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el valor del número de Euler (e) aproximado?", options: ["2.18", "2.71", "3.14", "1.61"], correctAnswer: "2.71" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el valor de la proporción áurea (φ)?", options: ["1.41", "1.61", "1.81", "2.71"], correctAnswer: "1.61" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de √169?", options: ["11", "12", "13", "14"], correctAnswer: "13" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de √(81 + 144)?", options: ["12", "13", "15", "21"], correctAnswer: "15" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de 5² × 2³?", options: ["100", "150", "200", "250"], correctAnswer: "200" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de log₃(27)?", options: ["2", "3", "9", "27"], correctAnswer: "3" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es la tangente de 45°?", options: ["0", "0.5", "1", "√3"], correctAnswer: "1" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de 1 + 2 + 3 + ... + 10?", options: ["45", "55", "100", "110"], correctAnswer: "55" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de (3 + 5)²?", options: ["32", "34", "64", "100"], correctAnswer: "64" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de 6! ÷ 4!?", options: ["15", "30", "120", "720"], correctAnswer: "30" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es la derivada de sin(x)?", options: ["cos(x)", "-cos(x)", "-sin(x)", "tan(x)"], correctAnswer: "cos(x)" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de 1/4 ÷ 1/8?", options: ["1/2", "1/32", "2", "32"], correctAnswer: "2" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es la suma de los ángulos internos de un hexágono?", options: ["540°", "720°", "900°", "1080°"], correctAnswer: "720°" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de 0.1 × 0.1 × 0.1?", options: ["0.001", "0.01", "0.1", "1"], correctAnswer: "0.001" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuántos números primos hay entre 1 y 20?", options: ["6", "7", "8", "9"], correctAnswer: "8" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de 7³?", options: ["49", "143", "343", "749"], correctAnswer: "343" },
  { category: "Matematicas", difficulty: "Dificil", question: "¿Cuál es el resultado de √625?", options: ["15", "20", "25", "30"], correctAnswer: "25" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el límite de sin(x)/x cuando x tiende a 0?", options: ["0", "1", "∞", "no existe"], correctAnswer: "1" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es la derivada de ln(x)?", options: ["1/x", "x", "ln(x)/x", "e^x"], correctAnswer: "1/x" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el resultado de la integral de 0 a π de sin(x)dx?", options: ["0", "1", "2", "π"], correctAnswer: "2" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es la suma de los primeros 100 números naturales?", options: ["5050", "5100", "10000", "10100"], correctAnswer: "5050" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el valor de i² (i = √-1)?", options: ["1", "-1", "i", "-i"], correctAnswer: "-1" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el resultado de e^(iπ) + 1?", options: ["0", "1", "i", "-1"], correctAnswer: "0" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el resultado de ∫(1/x)dx?", options: ["1/x²", "x", "ln|x| + C", "1/x + C"], correctAnswer: "ln|x| + C" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el resultado de la derivada de e^x?", options: ["1", "e^x", "x·e^(x-1)", "e^(x+1)"], correctAnswer: "e^x" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es la suma de los ángulos internos de un pentágono?", options: ["360°", "540°", "720°", "900°"], correctAnswer: "540°" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el resultado de 2^10 + 2^9?", options: ["512", "1024", "1536", "2048"], correctAnswer: "1536" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el resultado de 13²?", options: ["156", "169", "196", "225"], correctAnswer: "169" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el resultado de 17 × 23?", options: ["371", "391", "411", "431"], correctAnswer: "391" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es la derivada de tan(x)?", options: ["sec²(x)", "cot²(x)", "1/cos(x)", "sec(x)tan(x)"], correctAnswer: "sec²(x)" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el volumen de un cubo de arista 3?", options: ["9", "27", "81", "243"], correctAnswer: "27" },
  { category: "Matematicas", difficulty: "Experto", question: "¿Cuál es el resultado de log₂(1024)?", options: ["8", "9", "10", "11"], correctAnswer: "10" },
]

export const MATEMATICAS_QUESTIONS: QuestionSeed[] = RAW.map((q, i) => ({
  ...q,
  uuid: `q-math-${(i + 1).toString().padStart(4, "0")}`,
}))
