// Mitología — 100+ preguntas
import type { QuestionSeed } from "../questions"

const RAW: Omit<QuestionSeed, "uuid">[] = [
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el rey de los dioses griegos?", options: ["Poseidón", "Zeus", "Hades", "Apolo"], correctAnswer: "Zeus" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el dios del mar en la mitología griega?", options: ["Zeus", "Hades", "Poseidón", "Hermes"], correctAnswer: "Poseidón" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el dios del inframundo griego?", options: ["Zeus", "Hades", "Apolo", "Hermes"], correctAnswer: "Hades" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Qué diosa griega es la del amor y la belleza?", options: ["Atenea", "Afrodita", "Artemisa", "Hera"], correctAnswer: "Afrodita" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el dios romano de la guerra?", options: ["Marte", "Júpiter", "Neptuno", "Apolo"], correctAnswer: "Marte" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Qué héroe griego mató al Minotauro?", options: ["Heracles", "Teseo", "Perseo", "Aquiles"], correctAnswer: "Teseo" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el dios nórdico del trueno?", options: ["Odín", "Thor", "Loki", "Freyr"], correctAnswer: "Thor" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Qué dios egipcio tiene cabeza de chacal?", options: ["Ra", "Anubis", "Horus", "Osiris"], correctAnswer: "Anubis" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el padre de los dioses nórdicos?", options: ["Thor", "Odín", "Loki", "Tyr"], correctAnswer: "Odín" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Qué dios griego lleva mensajes?", options: ["Apolo", "Hermes", "Hefesto", "Dioniso"], correctAnswer: "Hermes" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es la diosa griega de la sabiduría?", options: ["Atenea", "Afrodita", "Hera", "Artemisa"], correctAnswer: "Atenea" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Qué héroe mató a Medusa?", options: ["Heracles", "Perseo", "Teseo", "Jasón"], correctAnswer: "Perseo" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el dios del Sol en la mitología griega?", options: ["Apolo", "Helios", "Zeus", "Hermes"], correctAnswer: "Apolo" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Qué animal representa a Anubis?", options: ["Chacal", "Gato", "Halcón", "Escarabajo"], correctAnswer: "Chacal" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el dios del fuego (griego)?", options: ["Hefesto", "Apolo", "Hermes", "Dioniso"], correctAnswer: "Hefesto" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Qué dios egipcio es el del Sol?", options: ["Ra", "Osiris", "Anubis", "Seth"], correctAnswer: "Ra" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el dios griego del vino?", options: ["Dioniso", "Apolo", "Hermes", "Hefesto"], correctAnswer: "Dioniso" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Qué diosa es la cazadora virgin griega?", options: ["Artemisa", "Atenea", "Afrodita", "Hera"], correctAnswer: "Artemisa" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el dios egipcio con cabeza de halcón?", options: ["Horus", "Anubis", "Ra", "Osiris"], correctAnswer: "Horus" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Qué héroe griego realizó los 12 trabajos?", options: ["Perseo", "Heracles", "Teseo", "Aquiles"], correctAnswer: "Heracles" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién fue la reina del inframundo griego?", options: ["Perséfone", "Hera", "Atenea", "Afrodita"], correctAnswer: "Perséfone" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Cuál es el nombre romano de Zeus?", options: ["Marte", "Júpiter", "Mercurio", "Saturno"], correctAnswer: "Júpiter" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Cuál es el nombre romano de Afrodita?", options: ["Venus", "Juno", "Minerva", "Diana"], correctAnswer: "Venus" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Cuál es el nombre romano de Poseidón?", options: ["Neptuno", "Marte", "Plutón", "Apolo"], correctAnswer: "Neptuno" },
  { category: "Mitologia", difficulty: "Facil", question: "¿Quién es el dios nórdico de las trampas y engaños?", options: ["Thor", "Loki", "Odín", "Tyr"], correctAnswer: "Loki" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién era el padre de Heracles?", options: ["Apolo", "Zeus", "Poseidón", "Hades"], correctAnswer: "Zeus" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Cómo se llama el caballo alado de la mitología griega?", options: ["Pegaso", "Unicornio", "Quimera", "Grifo"], correctAnswer: "Pegaso" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién fue el héroe de la Ilíada?", options: ["Aquiles", "Odiseo", "Áyax", "Héctor"], correctAnswer: "Aquiles" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué monstruo tiene cuerpo de león y cabeza humana?", options: ["Esfinge", "Quimera", "Minotauro", "Centauro"], correctAnswer: "Esfinge" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién fue el héroe de la Odisea?", options: ["Aquiles", "Odiseo", "Heracles", "Teseo"], correctAnswer: "Odiseo" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Cómo se llama el barco de Jasón?", options: ["Argo", "Odisea", "Penteconte", "Trirreme"], correctAnswer: "Argo" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es el dios egipcio del inframundo?", options: ["Osiris", "Anubis", "Ra", "Horus"], correctAnswer: "Osiris" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué criatura es mitad hombre mitad toro?", options: ["Minotauro", "Centauro", "Sátiro", "Fauno"], correctAnswer: "Minotauro" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué criatura es mitad hombre mitad caballo?", options: ["Centauro", "Minotauro", "Sátiro", "Fauno"], correctAnswer: "Centauro" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es la esposa de Odín?", options: ["Frigg", "Freya", "Sif", "Hel"], correctAnswer: "Frigg" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué monstruo tiene tres cabezas (perro)?", options: ["Cerbero", "Quimera", "Hidra", "Ortro"], correctAnswer: "Cerbero" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién mató al Minotauro?", options: ["Heracles", "Teseo", "Perseo", "Jasón"], correctAnswer: "Teseo" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué dios egipcio asesinó a Osiris?", options: ["Seth", "Anubis", "Horus", "Ra"], correctAnswer: "Seth" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Cómo se llama la diosa nórdica del amor?", options: ["Freya", "Frigg", "Sif", "Hel"], correctAnswer: "Freya" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es el dios nórdico de la guerra y la justicia?", options: ["Tyr", "Thor", "Odín", "Loki"], correctAnswer: "Tyr" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué criatura es una serpiente de múltiples cabezas?", options: ["Hidra", "Quimera", "Basilisco", "Dragón"], correctAnswer: "Hidra" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién abrió la caja de Pandora?", options: ["Pandora", "Prometeo", "Epimeteo", "Deucalión"], correctAnswer: "Pandora" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién robó el fuego a los dioses?", options: ["Prometeo", "Epimeteo", "Heracles", "Teseo"], correctAnswer: "Prometeo" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Cuál es el nombre del martillo de Thor?", options: ["Mjolnir", "Gungnir", "Draupnir", "Hofund"], correctAnswer: "Mjolnir" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es la diosa griega de la cosecha?", options: ["Deméter", "Perséfone", "Hera", "Artemisa"], correctAnswer: "Deméter" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es el padre de los dioses romanos?", options: ["Saturno", "Júpiter", "Urano", "Caelus"], correctAnswer: "Saturno" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Cómo se llama el río del inframundo griego?", options: ["Estigia", "Aqueronte", "Leteo", "Flegetonte"], correctAnswer: "Estigia" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es el barquero del inframundo griego?", options: ["Caronte", "Hermes", "Tánatos", "Hipnos"], correctAnswer: "Caronte" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué héroe mató a la Quimera?", options: ["Belerofonte", "Perseo", "Teseo", "Heracles"], correctAnswer: "Belerofonte" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es el dios azteca del sol y la guerra?", options: ["Huitzilopochtli", "Quetzalcóatl", "Tezcatlipoca", "Tláloc"], correctAnswer: "Huitzilopochtli" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué dios azteca es la serpiente emplumada?", options: ["Quetzalcóatl", "Tezcatlipoca", "Huitzilopochtli", "Xipe Tótec"], correctAnswer: "Quetzalcóatl" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es el dios griego del viento del norte?", options: ["Bóreas", "Céfiro", "Noto", "Euro"], correctAnswer: "Bóreas" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién fue el héroe troyano de la Ilíada?", options: ["Héctor", "Paris", "Príamo", "Eneas"], correctAnswer: "Héctor" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué diosa romana es equivalente a Artemisa?", options: ["Diana", "Minerva", "Venus", "Juno"], correctAnswer: "Diana" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es la diosa griega de la victoria?", options: ["Nike", "Atenea", "Hera", "Ártemis"], correctAnswer: "Nike" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Cómo se llama el caballo de Aquiles?", options: ["Janto", "Bucéfalo", "Pegaso", "Arapaima"], correctAnswer: "Janto" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién fue el último faraón egipcio (mitología)?", options: ["Cleopatra", "Nectanebo II", "Ramsés III", "Tutankamón"], correctAnswer: "Cleopatra" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Qué dios griego es el mensajero entre dioses y hombres?", options: ["Hermes", "Apolo", "Zeus", "Hefesto"], correctAnswer: "Hermes" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es el dios maya de la lluvia?", options: ["Chaac", "Kukulcán", "Itzamná", "Huracán"], correctAnswer: "Chaac" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Cuál es el nombre del reino de los muertos nórdico?", options: ["Hel", "Valhalla", "Asgard", "Midgard"], correctAnswer: "Hel" },
  { category: "Mitologia", difficulty: "Medio", question: "¿Quién es el dios nórdico de la luz?", options: ["Baldur", "Heimdall", "Forseti", "Hodr"], correctAnswer: "Baldur" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién era el padre de los Titanes griegos?", options: ["Urano", "Crono", "Zeus", "Gea"], correctAnswer: "Urano" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién fue el líder de los Titanes?", options: ["Crono", "Urano", "Zeus", "Océano"], correctAnswer: "Crono" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Cuántos trabajos tuvo que realizar Heracles?", options: ["10", "12", "14", "16"], correctAnswer: "12" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién fue la madre de Perseo?", options: ["Dánae", "Medusa", "Andrómeda", "Casiopea"], correctAnswer: "Dánae" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Cómo se llama la madre de Zeus?", options: ["Rea", "Gea", "Mnemósine", "Temis"], correctAnswer: "Rea" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién profetizó la caída de Troya?", options: ["Casandra", "Hécuba", "Laocoonte", "Príamo"], correctAnswer: "Casandra" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién mató a Aquiles?", options: ["Paris", "Héctor", "Agamenón", "Príamo"], correctAnswer: "Paris" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Cuál era el talón vulnerable de Aquiles?", options: ["El izquierdo", "El derecho", "Ambos", "Ninguno"], correctAnswer: "El izquierdo" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Cómo se llama el lobo gigante nórdico?", options: ["Fenrir", "Jörmungandr", "Sköll", "Hati"], correctAnswer: "Fenrir" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Cómo se llama la serpiente del mundo nórdico?", options: ["Jörmungandr", "Fenrir", "Níðhöggr", "Fafnir"], correctAnswer: "Jörmungandr" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Qué dios egipcio tiene cabeza de ibis?", options: ["Thot", "Anubis", "Horus", "Ra"], correctAnswer: "Thot" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién es la diosa egipcia de la magia?", options: ["Isis", "Hathor", "Maat", "Sejmet"], correctAnswer: "Isis" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Cómo se llama el paraíso nórdico de los guerreros?", options: ["Valhalla", "Asgard", "Vanaheim", "Alfheim"], correctAnswer: "Valhalla" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién es el dios griego del sueño?", options: ["Hipnos", "Tánatos", "Morfeo", "Hermes"], correctAnswer: "Hipnos" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién es el dios griego de la muerte?", options: ["Tánatos", "Hipnos", "Hades", "Caronte"], correctAnswer: "Tánatos" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Cómo se llama el árbol de la vida nórdico?", options: ["Yggdrasil", "Bálder", "Mímameiðr", "Læraðr"], correctAnswer: "Yggdrasil" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién es el dios griego del tiempo?", options: ["Crono", "Urano", "Zeus", "Aión"], correctAnswer: "Crono" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Qué hija del rey Minos dio el hilo a Teseo?", options: ["Ariadna", "Fedra", "Pasífae", "Cálice"], correctAnswer: "Ariadna" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién es el dios griego de la medicina?", options: ["Asclepio", "Apolo", "Hermes", "Hefesto"], correctAnswer: "Asclepio" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién es la musa de la poesía épica?", options: ["Calíope", "Clio", "Melpómene", "Talía"], correctAnswer: "Calíope" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Cómo se llama el primer humano en la mitología griega?", options: ["Deucalión", "Prometeo", "Epimeteo", "Pandora"], correctAnswer: "Deucalión" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién es la diosa griega de la venganza?", options: ["Némesis", "Temis", "Dike", "Atenea"], correctAnswer: "Némesis" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Cuántas cabezas tenía la Hidra de Lerna?", options: ["7", "9", "12", "100"], correctAnswer: "9" },
  { category: "Mitologia", difficulty: "Dificil", question: "¿Quién mató al dragón que custodiaba el vellocino de oro?", options: ["Jasón", "Heracles", "Perseo", "Teseo"], correctAnswer: "Jasón" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Quién es la diosa griega de la noche?", options: ["Nyx", "Hemera", "Érebo", "Caos"], correctAnswer: "Nyx" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Quién es el dios griego del amor masculino?", options: ["Eros", "Anteros", "Hímero", "Pothos"], correctAnswer: "Eros" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Cómo se llama la esposa de Osiris?", options: ["Isis", "Nephthys", "Hathor", "Maat"], correctAnswer: "Isis" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Quién es el dios griego de los rebaños?", options: ["Pan", "Hermes", "Apolo", "Dioniso"], correctAnswer: "Pan" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Quién era el padre de los cíclopes?", options: ["Urano", "Crono", "Gea", "Zeus"], correctAnswer: "Urano" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Cómo se llama la diosa egipcia de la verdad?", options: ["Maat", "Isis", "Hathor", "Seshat"], correctAnswer: "Maat" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Quién es el dios griego de los sueños?", options: ["Morfeo", "Hipnos", "Tánatos", "Fantaso"], correctAnswer: "Morfeo" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Cómo se llama el perro de dos cabezas hermano de Cerbero?", options: ["Ortro", "Cerbero", "Hidra", "Quimera"], correctAnswer: "Ortro" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Qué dios nórdico custodia el Bifröst?", options: ["Heimdall", "Thor", "Tyr", "Baldur"], correctAnswer: "Heimdall" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Quién es el dios védico del fuego?", options: ["Agni", "Indra", "Varuna", "Soma"], correctAnswer: "Agni" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Quién es el dios hindú de la destrucción?", options: ["Shiva", "Vishnu", "Brahma", "Ganesh"], correctAnswer: "Shiva" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Cómo se llama el río del olvido del inframundo?", options: ["Leteo", "Estigia", "Aqueronte", "Cocito"], correctAnswer: "Leteo" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Quién es el dios azteca de la lluvia?", options: ["Tláloc", "Quetzalcóatl", "Huitzilopochtli", "Xipe Tótec"], correctAnswer: "Tláloc" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Cómo se llama el barco que cruza el sol en el cielo egipcio?", options: ["Barca de Ra", "Barca de Osiris", "Barca de Horus", "Barca solar"], correctAnswer: "Barca solar" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Quién fue la primera mujer en la mitología griega?", options: ["Pandora", "Eva", "Pirra", "Deucalión"], correctAnswer: "Pandora" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Qué era el río Flegetonte?", options: ["Río de fuego", "Río de olvido", "Río de lamentaciones", "Río de odio"], correctAnswer: "Río de fuego" },
  { category: "Mitologia", difficulty: "Experto", question: "¿Cómo se llama el gigante de 100 ojos?", options: ["Argo", "Argos", "Cíclope", "Hecatónquiro"], correctAnswer: "Argos" },
]

export const MITOLOGIA_QUESTIONS: QuestionSeed[] = RAW.map((q, i) => ({
  ...q,
  uuid: `q-mito-${(i + 1).toString().padStart(4, "0")}`,
}))
