// Videojuegos — 100+ preguntas
import type { QuestionSeed } from "../questions"

const RAW: Omit<QuestionSeed, "uuid">[] = [
  { category: "Videojuegos", difficulty: "Facil", question: "¿Quién es el protagonista de Super Mario?", options: ["Luigi", "Mario", "Bowser", "Yoshi"], correctAnswer: "Mario" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Qué compañía creó la PlayStation?", options: ["Microsoft", "Nintendo", "Sony", "Sega"], correctAnswer: "Sony" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿En qué juego se recolectan monedas y estrellas?", options: ["Sonic", "Super Mario 64", "Crash Bandicoot", "Mega Man"], correctAnswer: "Super Mario 64" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Qué color es Sonic?", options: ["Rojo", "Verde", "Azul", "Amarillo"], correctAnswer: "Azul" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Cuál es el juego más vendido de todos los tiempos?", options: ["Tetris", "Minecraft", "GTA V", "Wii Sports"], correctAnswer: "Minecraft" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Qué personaje es el héroe de The Legend of Zelda?", options: ["Link", "Zelda", "Ganon", "Navi"], correctAnswer: "Link" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Qué consola lanzó Nintendo en 2017?", options: ["Wii U", "Switch", "3DS", "GameCube"], correctAnswer: "Switch" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿En qué juego aparecen Pikachu y Charizard?", options: ["Digimon", "Pokémon", "Yokai Watch", "Monster Hunter"], correctAnswer: "Pokémon" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Quién es el protagonista de Halo?", options: ["Marcus Fenix", "Master Chief", "Kratos", "Nathan Drake"], correctAnswer: "Master Chief" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿En qué año se lanzó Minecraft (versión completa)?", options: ["2009", "2011", "2013", "2015"], correctAnswer: "2011" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Qué compañía creó la Xbox?", options: ["Sony", "Microsoft", "Nintendo", "Sega"], correctAnswer: "Microsoft" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Cuál es el grito famoso de Mario?", options: ["¡Yahoo!", "¡It's-a me, Mario!", "¡Wahoo!", "¡Here we go!"], correctAnswer: "¡It's-a me, Mario!" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿En qué juego construyes con bloques?", options: ["Roblox", "Minecraft", "Tetris", "Lego Star Wars"], correctAnswer: "Minecraft" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Quién es el villano principal de Donkey Kong?", options: ["Bowser", "King K. Rool", "Ganon", "Dr. Eggman"], correctAnswer: "King K. Rool" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Qué animal es Crash Bandicoot?", options: ["Zorro", "Bandicoot", "Canguro", "Wombat"], correctAnswer: "Bandicoot" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿En qué videojuego eres un Dios de la guerra?", options: ["Dark Souls", "God of War", "Devil May Cry", "Bayonetta"], correctAnswer: "God of War" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Quién es el enemigo de Sonic?", options: ["Bowser", "Dr. Eggman", "Ganon", "Sephiroth"], correctAnswer: "Dr. Eggman" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Qué consola precedió a la PS4?", options: ["PS2", "PS3", "PSX", "PSP"], correctAnswer: "PS3" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Cuál es el protagonista de Tomb Raider?", options: ["Lara Croft", "Nathan Drake", "Indiana Jones", "Sam Fisher"], correctAnswer: "Lara Croft" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Qué juego tiene cubos que caen?", options: ["Tetris", "Puyo Puyo", "Dr. Mario", "Candy Crush"], correctAnswer: "Tetris" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿En qué año se lanzó el primer Pokémon?", options: ["1994", "1996", "1998", "2000"], correctAnswer: "1996" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Quién es el creador de Mario?", options: ["Hideo Kojima", "Shigeru Miyamoto", "Satoru Iwata", "Yuji Naka"], correctAnswer: "Shigeru Miyamoto" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿En qué juego aparecen los 'creepers'?", options: ["Roblox", "Minecraft", "Terraria", "Fortnite"], correctAnswer: "Minecraft" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿Qué color es el fantasma Blinky en Pac-Man?", options: ["Rojo", "Rosa", "Cian", "Naranja"], correctAnswer: "Rojo" },
  { category: "Videojuegos", difficulty: "Facil", question: "¿En qué videojuego eres un cazador de monstruos?", options: ["Dark Souls", "Monster Hunter", "Witcher", "Skyrim"], correctAnswer: "Monster Hunter" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Quién dirigió el desarrollo de Metal Gear Solid?", options: ["Hideo Kojima", "Shigeru Miyamoto", "Yu Suzuki", "Fumito Ueda"], correctAnswer: "Hideo Kojima" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó el primer Final Fantasy?", options: ["1985", "1987", "1990", "1992"], correctAnswer: "1987" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Quién es el protagonista de The Witcher?", options: ["Geralt de Rivia", "Kratos", "Lara Croft", "Nathan Drake"], correctAnswer: "Geralt de Rivia" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Cuál fue la primera consola de Nintendo?", options: ["NES", "SNES", "Color TV-Game", "Game & Watch"], correctAnswer: "Color TV-Game" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó Grand Theft Auto V?", options: ["2011", "2013", "2015", "2017"], correctAnswer: "2013" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Quién es el protagonista de God of War (original)?", options: ["Atreus", "Kratos", "Baldur", "Zeus"], correctAnswer: "Kratos" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Cuál es la espada legendaria de Link?", options: ["Master Sword", "Excalibur", "Andúril", "Frostmourne"], correctAnswer: "Master Sword" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó The Legend of Zelda: Ocarina of Time?", options: ["1996", "1998", "2000", "2002"], correctAnswer: "1998" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Qué compañía desarrolló Dark Souls?", options: ["Capcom", "FromSoftware", "Bandai Namco", "Square Enix"], correctAnswer: "FromSoftware" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Cuál es el nombre del protagonista de Half-Life?", options: ["Gordon Freeman", "Adrian Shephard", "Barney Calhoun", "Eli Vance"], correctAnswer: "Gordon Freeman" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó World of Warcraft?", options: ["2002", "2004", "2006", "2008"], correctAnswer: "2004" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Qué estudio creó Overwatch?", options: ["Valve", "Blizzard", "Riot", "Epic Games"], correctAnswer: "Blizzard" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Quién es el villano principal de Final Fantasy VII?", options: ["Kefka", "Sephiroth", "Kuja", "Ultimecia"], correctAnswer: "Sephiroth" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Qué año se lanzó Street Fighter II?", options: ["1989", "1991", "1993", "1995"], correctAnswer: "1991" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Cuál es el nombre del protagonista de Resident Evil (primer juego)?", options: ["Chris Redfield", "Leon Kennedy", "Jill Valentine", "Albert Wesker"], correctAnswer: "Chris Redfield" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Qué estudio desarrolló The Last of Us?", options: ["Naughty Dog", "Rockstar", "Insomniac", "Bungie"], correctAnswer: "Naughty Dog" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Quién es el protagonista de Uncharted?", options: ["Lara Croft", "Nathan Drake", "Indiana Jones", "Marco Polo"], correctAnswer: "Nathan Drake" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Qué consola lanzó Sega en 1998 (su última)?", options: ["Saturn", "Dreamcast", "Genesis", "Master System"], correctAnswer: "Dreamcast" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó Fortnite: Battle Royale?", options: ["2015", "2017", "2019", "2021"], correctAnswer: "2017" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Quién es el creador de Pac-Man?", options: ["Toru Iwatani", "Shigeru Miyamoto", "Hideo Kojima", "Yu Suzuki"], correctAnswer: "Toru Iwatani" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Qué juego popularizó el género 'battle royale'?", options: ["PUBG", "Fortnite", "Apex Legends", "Warzone"], correctAnswer: "PUBG" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Cuál es el nombre de la princesa en Super Mario?", options: ["Zelda", "Peach", "Daisy", "Rosalina"], correctAnswer: "Peach" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó el primer Super Smash Bros.?", options: ["1997", "1999", "2001", "2003"], correctAnswer: "1999" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Qué videojuego tiene a Kratos como protagonista?", options: ["Devil May Cry", "God of War", "Heavenly Sword", "Darksiders"], correctAnswer: "God of War" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Quién es el protagonista de Metal Gear Solid?", options: ["Raiden", "Solid Snake", "Big Boss", "Otacon"], correctAnswer: "Solid Snake" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó el Atari 2600?", options: ["1975", "1977", "1980", "1983"], correctAnswer: "1977" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Cuántos personajes jugables hay en Super Smash Bros. Ultimate (base)?", options: ["40", "60", "74", "89"], correctAnswer: "74" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Qué compañía desarrolló League of Legends?", options: ["Valve", "Riot Games", "Blizzard", "Epic"], correctAnswer: "Riot Games" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó Doom (original)?", options: ["1990", "1993", "1996", "1999"], correctAnswer: "1993" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Cuál es el nombre del protagonista de Devil May Cry?", options: ["Dante", "Vergil", "Nero", "Trish"], correctAnswer: "Dante" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Qué videojuego tiene lugar en Rapture?", options: ["BioShock", "Fallout", "Half-Life", "Deus Ex"], correctAnswer: "BioShock" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó el primer Pokémon Rojo/Azul en Europa?", options: ["1996", "1998", "1999", "2000"], correctAnswer: "1999" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Quién es el creador de Tetris?", options: ["Alexey Pajitnov", "Shigeru Miyamoto", "Hideo Kojima", "Yuji Naka"], correctAnswer: "Alexey Pajitnov" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿En qué año se lanzó la Nintendo 64?", options: ["1994", "1996", "1998", "2000"], correctAnswer: "1996" },
  { category: "Videojuegos", difficulty: "Medio", question: "¿Quién es el protagonista de Metroid?", options: ["Master Chief", "Samus Aran", "Marcus Fenix", "Doomguy"], correctAnswer: "Samus Aran" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Qué año se lanzó el primer Final Fantasy VII?", options: ["1995", "1997", "1999", "2001"], correctAnswer: "1997" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Quién dirigió Shadow of the Colossus?", options: ["Hideo Kojima", "Fumito Ueda", "Hidetaka Miyazaki", "Yu Suzuki"], correctAnswer: "Fumito Ueda" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Cuál fue el último juego de Sega Genesis?", options: ["Sonic 3D Blast", "Sonic Spinball", "Comix Zone", "Toy Story"], correctAnswer: "Sonic 3D Blast" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿En qué año se lanzó Silent Hill 2?", options: ["1999", "2001", "2003", "2005"], correctAnswer: "2001" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Quién compuso la banda sonora de Final Fantasy?", options: ["Nobuo Uematsu", "Koji Kondo", "Yoko Shimomura", "Yasunori Mitsuda"], correctAnswer: "Nobuo Uematsu" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿En qué año se lanzó Super Metroid?", options: ["1992", "1994", "1996", "1998"], correctAnswer: "1994" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Cuál fue el primer juego de la saga Metal Gear?", options: ["1987", "1990", "1995", "1998"], correctAnswer: "1987" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Qué desarrolladora creó Bloodborne?", options: ["Capcom", "FromSoftware", "Bandai", "Square Enix"], correctAnswer: "FromSoftware" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Quién es el protagonista de Castlevania: Symphony of the Night?", options: ["Simon Belmont", "Alucard", "Trevor Belmont", "Richter Belmont"], correctAnswer: "Alucard" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿En qué año se lanzó la Game Boy original?", options: ["1987", "1989", "1991", "1993"], correctAnswer: "1989" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Cuál es el verdadero nombre de Master Chief?", options: ["John-117", "Carter-117", "James-117", "Marcus-117"], correctAnswer: "John-117" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Quién compuso la banda sonora de Super Mario Bros.?", options: ["Nobuo Uematsu", "Koji Kondo", "Yoko Shimomura", "Yuzo Koshiro"], correctAnswer: "Koji Kondo" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿En qué año se lanzó Chrono Trigger?", options: ["1993", "1995", "1997", "1999"], correctAnswer: "1995" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Quién es el protagonista de Mega Man X?", options: ["X", "Zero", "Mega Man", "Proto Man"], correctAnswer: "X" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Cuál fue el primer juego de Pokémon en 3D principal?", options: ["Pokémon X/Y", "Pokémon Sun/Moon", "Pokémon Sword/Shield", "Pokémon Diamond/Pearl"], correctAnswer: "Pokémon X/Y" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿En qué año se lanzó EarthBound (Mother 2)?", options: ["1992", "1994", "1996", "1998"], correctAnswer: "1994" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Quién es el creador de EarthBound?", options: ["Shigesato Itoi", "Hideo Kojima", "Yuji Horii", "Koichi Ishii"], correctAnswer: "Shigesato Itoi" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Qué juego de Konami es conocido por su código de trampa?", options: ["Castlevania", "Contra", "Metal Gear", "Silent Hill"], correctAnswer: "Contra" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Quién dirigió The Legend of Zelda: Breath of the Wild?", options: ["Shigeru Miyamoto", "Eiji Aonuma", "Hidemaro Fujibayashi", "Satoru Iwata"], correctAnswer: "Hidemaro Fujibayashi" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Qué estudio desarrolló Persona 5?", options: ["Atlus", "Square Enix", "Capcom", "Bandai"], correctAnswer: "Atlus" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿En qué año se lanzó Ico?", options: ["1999", "2001", "2003", "2005"], correctAnswer: "2001" },
  { category: "Videojuegos", difficulty: "Dificil", question: "¿Quién compuso la banda sonora de Silent Hill?", options: ["Akira Yamaoka", "Nobuo Uematsu", "Koji Kondo", "Yoko Shimomura"], correctAnswer: "Akira Yamaoka" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿En qué año se lanzó la Game & Watch?", options: ["1978", "1980", "1982", "1984"], correctAnswer: "1980" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿Quién fue el creador de Final Fantasy?", options: ["Hironobu Sakaguchi", "Yuji Horii", "Hideo Kojima", "Tetsuya Nomura"], correctAnswer: "Hironobu Sakaguchi" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿En qué año se lanzó el primer Resident Evil?", options: ["1994", "1996", "1998", "2000"], correctAnswer: "1996" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿Quién fue el primer director de Metroid?", options: ["Shigeru Miyamoto", "Yoshio Sakamoto", "Gunpei Yokoi", "Satoru Iwata"], correctAnswer: "Gunpei Yokoi" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿En qué año se lanzó Star Fox?", options: ["1991", "1993", "1995", "1997"], correctAnswer: "1993" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿Cuál fue el primer juego de FromSoftware?", options: ["Demon's Souls", "King's Field", "Dark Souls", "Bloodborne"], correctAnswer: "King's Field" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿Quién compuso la banda sonora de Chrono Trigger?", options: ["Nobuo Uematsu", "Yasunori Mitsuda", "Yoko Shimomura", "Koji Kondo"], correctAnswer: "Yasunori Mitsuda" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿En qué año se lanzó el primer Castlevania?", options: ["1984", "1986", "1988", "1990"], correctAnswer: "1986" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿Quién es el protagonista de Shenmue?", options: ["Ryo Hazuki", "Kazuma Kiryu", "Akira Yuki", "Jotaro Kujo"], correctAnswer: "Ryo Hazuki" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿En qué año se lanzó la Sega Master System?", options: ["1985", "1986", "1987", "1989"], correctAnswer: "1986" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿Quién dirigió Panzer Dragoon Saga?", options: ["Yukio Futatsugi", "Hideo Kojima", "Yu Suzuki", "Hidetaka Miyazaki"], correctAnswer: "Yukio Futatsugi" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿Cuál fue el último juego de la saga Mother?", options: ["Mother", "Mother 2", "Mother 3", "Mother 4"], correctAnswer: "Mother 3" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿En qué año se lanzó Akalabeth (primer Ultima)?", options: ["1977", "1979", "1981", "1983"], correctAnswer: "1979" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿Quién creó la saga Dragon Quest?", options: ["Yuji Horii", "Hironobu Sakaguchi", "Hideo Kojima", "Tetsuya Nomura"], correctAnswer: "Yuji Horii" },
  { category: "Videojuegos", difficulty: "Experto", question: "¿En qué año se lanzó el primer Street Fighter?", options: ["1985", "1987", "1989", "1991"], correctAnswer: "1987" },
]

export const VIDEOJUEGOS_QUESTIONS: QuestionSeed[] = RAW.map((q, i) => ({
  ...q,
  uuid: `q-game-${(i + 1).toString().padStart(4, "0")}`,
}))
