"""
Genera src/lib/facts-data.ts con 100+ datos curiosos.
Categorías color-coded, sin duplicados, mezcla de temas.
"""
import os

# (emoji, category, color_key, title, description)
FACTS = [
    # ===== CIENCIA (15) =====
    ("🐙", "Ciencia", "ciencia", "El pulpo tiene tres corazones",
     "Dos corazones bombean sangre a las branquias y el tercero al resto del cuerpo. Cuando nada, el corazón principal se detiene, por eso prefieren caminar."),
    ("🧠", "Ciencia", "ciencia", "El cerebro usa el 20% de tu energía",
     "Pesa apenas 1.4 kg pero consume el 20% del oxígeno y calorías. Genera energía suficiente para encender una bombilla de bajo consumo."),
    ("🔬", "Ciencia", "ciencia", "El agua puede hervir y congelarse a la vez",
     "En el 'punto triple' (0.01°C y 611 Pa) el agua existe simultáneamente como sólido, líquido y gas. Es así como se calibran los termómetros exactos."),
    ("💎", "Ciencia", "ciencia", "Los diamantes llueven en Júpiter",
     "El relámpago convierte el metano en carbono sólido que, al caer, se comprime y forma diamantes. Pero se derriten antes de llegar al núcleo."),
    ("🧪", "Ciencia", "ciencia", "El helio líquido sube por las paredes",
     "A -271°C forma una película que trepa por las paredes de cualquier recipiente y se escurre hacia afuera, desafiando la gravedad. Es un 'superfluido' sin viscosidad."),
    ("⚛️", "Ciencia", "ciencia", "El átomo es 99.9999% espacio vacío",
     "Si el núcleo fuera una canica en el centro de un estadio, los electrones estarían en las gradas. Toda la 'masa' está concentrada en un punto minúsculo."),
    ("🧬", "Ciencia", "ciencia", "Tu ADN llegaría al Sol y volvería",
     "Estirado, el ADN de todas tus células daría 200 mil millones de km: ida y vuelta al Sol 600 veces. Es la molécula más larga del universo conocido."),
    ("🌋", "Ciencia", "ciencia", "La lava es tan caliente como la superficie del Sol",
     "La lava fresca alcanza 1,200°C. La superficie del Sol está a 5,500°C, pero el interior de la Tierra llega a 6,000°C: más caliente que el Sol exterior."),
    ("🌪️", "Ciencia", "ciencia", "Un tornado puede girar a 480 km/h",
     "El récord de velocidad de vientos en un tornado es de 484 km/h (Oklahoma, 1999). Son los fenómenos más violentos del planeta."),
    ("🪨", "Ciencia", "ciencia", "El oro viene de estrellas muertas",
     "El oro no se forma en la Tierra. Lo crean las explosiones de estrellas de neutrones (kilonovas) hace miles de millones de años, antes de que existiera el Sol."),
    ("❄️", "Ciencia", "ciencia", "Cada copo de nieve es único",
     "Ningún copo de nieve en la historia ha sido idéntico a otro. La combinación de temperatura, humedad y trayectoria genera formas infinitas."),
    ("🌊", "Ciencia", "ciencia", "El sonido viaja 4x más rápido en agua",
     "En aire: 343 m/s. En agua: 1,500 m/s. Por eso las ballenas pueden comunicarse a cientos de kilómetros bajo el mar."),
    ("⚡", "Ciencia", "ciencia", "Un rayo tiene 5 veces la temperatura del Sol",
     "El aire alrededor de un rayo alcanza 30,000°C. La superficie del Sol está a 5,500°C. El rayo es la cosa más caliente que existe naturalmente en la Tierra."),
    ("🧲", "Ciencia", "ciencia", "La Tierra tiene campo magnético desde hace 4,000M años",
     "Sin él, el viento solar habría arrancado nuestra atmósfera hace eones, como le pasó a Marte. Es lo que permite la vida en la superficie."),
    ("🦠", "Ciencia", "ciencia", "Un microbio sobrevive en el espacio exterior",
     "Tardigrades ('osos de agua') soportan radiación, vacío y temperaturas de -271°C a 150°C. Son los únicos animales que sobrevivirían a un evento de extinción total."),
    # ===== HISTORIA (10) =====
    ("🧱", "Historia", "historia", "La Gran Muralla China mide +21,000 km",
     "No es una sola pared, sino una red de tramos construidos a lo largo de 2,000 años. Se dice que es visible desde la órbita baja terrestre."),
    ("🏛️", "Historia", "historia", "Los romanos usaban orina para lavar ropa",
     "El amoníaco de la orina era un detergente natural. El emperador Vespasiano incluso cobraba impuestos por la recolección de orina pública."),
    ("🗡️", "Historia", "historia", "La Biblioteca de Alejandría tuvo 700,000 rollos",
     "Su pérdida retrasó el avance científico 1,000 años. Hipatia, su última gran científica, fue asesinada en el 415 d.C. por una multitud enfurecida."),
    ("⚔️", "Historia", "historia", "La guerra más corta duró 38 minutos",
     "Guerra Anglo-Zanzíbar (1896): el sultán Khalid se negó a rendirse, los británicos bombardearon su palacio, y todo terminó antes de la hora."),
    ("👑", "Historia", "historia", "Cleopatra vivió más cerca del iPhone que de las pirámides",
     "Las pirámides se construyeron hace 4,500 años. Cleopatra vivió hace 2,000 años. El primer iPhone salió hace 18. Para ella, las pirámides eran 'antigüedades'."),
    ("⚓", "Historia", "historia", "Los vikingos llegaron a América 500 años antes que Colón",
     "Leif Erikson pisó Terranova alrededor del año 1000 d.C. Colón llegó en 1492. Los vikingos no se quedaron porque los pueblos originarios los expulsaron."),
    ("🏰", "Historia", "historia", "El Imperio Romano duró 1,500 años",
     "Desde la fundación (753 a.C.) hasta la caída de Constantinopla (1453). Es el imperio más longevo de la historia occidental."),
    ("📜", "Historia", "historia", "La escritura más antigua tiene 5,500 años",
     "Los sumerios inventaron la cuneiforme en Mesopotamia hacia el 3,500 a.C. Para escribir, usaban una caña sobre tablillas de arcilla húmeda."),
    ("🏜️", "Historia", "historia", "Las pirámides se construyeron con agua, no esclavos",
     "Estudios recientes muestran que los constructores eran trabajadores pagados y alimentados, y que usaban canales para acercar las piedras en barcazas."),
    ("🪓", "Historia", "historia", "El Imperio Mongol fue el más grande de la historia",
     "Bajo Gengis Khan y sus sucesores, abarcó 24 millones de km² (16% de la tierra emergida). Conectó Europa y Asia por primera vez por vía terrestre."),
    # ===== ESPACIO (12) =====
    ("🌍", "Espacio", "espacio", "La Tierra rotó más rápido en 2020",
     "El 19 de julio de 2020 fue el día más corto jamás medido: 1.46 ms menos de 24 horas. El clima, los océanos y el núcleo afectan la rotación planetaria."),
    ("🪐", "Espacio", "espacio", "Saturno flotaría en agua",
     "Su densidad es de 0.687 g/cm³, menor que la del agua (1). Si existiera una bañera suficientemente grande, el planeta entero flotaría en su superficie."),
    ("🌌", "Espacio", "espacio", "Hay más estrellas que granos de arena",
     "El universo observable tiene ~10²⁴ estrellas. Todas las playas de la Tierra suman ~10¹⁹ granos de arena. Por cada grano, hay 100,000 estrellas."),
    ("☀️", "Espacio", "espacio", "La luz del Sol tarda 8 minutos en llegarnos",
     "8 minutos y 20 segundos. Cuando miras el Sol, lo ves como era en el pasado. Si desapareciera de golpe, no lo sabríamos por 8 minutos."),
    ("🌕", "Espacio", "espacio", "La Luna se aleja 3.8 cm al año",
     "Cada año la Luna está más lejos de la Tierra. En 600 millones de años no habrá más eclipses totales de Sol visibles desde aquí."),
    ("🚀", "Espacio", "espacio", "Voyager 1 sigue viajando después de 47 años",
     "Lanzada en 1977, es el objeto más lejano creado por el ser humano. Salió del sistema solar en 2012 y viaja a 17 km/s hacia la estrella AC+79 3888."),
    ("⭐", "Espacio", "espacio", "Una cucharadita de estrella de neutrones pesa 6 mil millones de toneladas",
     "Son tan densas que un cubito de azúcar de su material pesaría tanto como una montaña. Es la materia en su estado más extremo del universo."),
    ("🌠", "Espacio", "espacio", "La Vía Láctea y Andrómeda chocarán en 4,500M años",
     "Se acercan a 110 km/s. La fusión creará una nueva galaxia elíptica llamada 'Milkdromeda'. Probablemente el Sol sobreviva al impacto."),
    ("🌑", "Espacio", "espacio", "Hay un agujero negro en el centro de la Vía Láctea",
     "Se llama Sagitario A* y tiene 4.3 millones de masas solares. Es invisible, pero vemos las órbitas de estrellas girando alrededor de 'la nada'."),
    ("🛰️", "Espacio", "espacio", "La ISS orbita la Tierra cada 90 minutos",
     "A 27,600 km/h y 400 km de altura. Los astronautas ven 16 amaneceres y 16 atardeceres cada día terrestre."),
    ("☄️", "Espacio", "espacio", "Los cometas tienen dos colas, no una",
     "Una cola de polvo (curva, amarillenta) y una cola de iones (recta, azulada). Ambas apuntan en dirección contraria al Sol."),
    ("🌖", "Espacio", "espacio", "Marte tiene la montaña más alta del sistema solar",
     "El Olympus Mons mide 22 km (casi 3 Everests). Su base es del tamaño de Francia. Es un volcán extinto hace millones de años."),
    # ===== NATURALEZA (10) =====
    ("🐜", "Naturaleza", "naturaleza", "Las hormigas pueden cargar 50x su peso",
     "Si un humano tuviera esa fuerza proporcional, levantaría un automóvil. Existen más de 12,000 especies de hormigas en el planeta."),
    ("🦋", "Naturaleza", "mariposas", "La mariposa monarca viaja 4,500 km",
     "Cada otoño migra de Canadá a México, pero la hace en 4 generaciones: las que llegan nunca han estado allí, pero saben exactamente dónde ir."),
    ("🐼", "Naturaleza", "naturaleza", "El panda pasa 14 horas al día comiendo",
     "Su dieta es 99% bambú, pero su estómago es de carnívoro. Para nutrirse debe ingerir entre 12 y 38 kg diarios de bambú."),
    ("🐌", "Naturaleza", "naturaleza", "Un caracol puede dormir 3 años seguidos",
     "Si el clima es muy seco, entran en estivación: sellan su concha y esperan. Algunos han sobrevivido así 3 años pegados a una pared."),
    ("🐝", "Naturaleza", "naturaleza", "Una abeja produce 1/12 de cucharadita de miel en su vida",
     "Para 1 kg de miel, las abejas de una colmena recorren el equivalente a 3 vueltas a la Tierra visitando flores."),
    ("🩸", "Naturaleza", "naturaleza", "Los pulpos tienen sangre azul",
     "Su hemocianina (en lugar de hemoglobina) transporta oxígeno usando cobre en vez de hierro. Por eso su sangre es azul, no roja."),
    ("🦒", "Naturaleza", "naturaleza", "La jirafa tiene el cuello más largo pero 7 vértebras",
     "Las mismas que los humanos. Cada vértebra mide hasta 28 cm. Su corazón pesa 11 kg para bombear sangre a 2.5 m de altura."),
    ("🦁", "Naturaleza", "naturaleza", "Un león ruge a 114 decibelios",
     "Se puede escuchar a 8 km de distancia. Es el rugido más potente de cualquier felino, usado para marcar territorio y llamar a la manada."),
    ("🌵", "Naturaleza", "naturaleza", "Un cactus puede vivir 200 años",
     "El saguaro del desierto de Sonora crece solo 2 cm en sus primeros 10 años. A los 75 da su primera flor. Algunos superan los 15 metros."),
    ("🍄", "Naturaleza", "naturaleza", "Los hongos están más cerca de los animales que de las plantas",
     "Compartimos un ancestro común de hace 1,500 millones de años. Los hongos no fotosintetizan: 'comen' como nosotros, absorbiendo materia orgánica."),
    # ===== OCÉANO (8) =====
    ("🐋", "Océano", "ocean", "La ballena azul es el animal más grande jamás existente",
     "Mide hasta 30 m y pesa 180 toneladas. Su corazón es del tamaño de un coche pequeño y su lengua pesa tanto como un elefante."),
    ("🦈", "Océano", "ocean", "Los tiburones existían antes que los árboles",
     "Aparecieron hace 400 millones de años; los árboles aparecieron hace 350 millones. Sobrevivieron a 4 extinciones masivas sin cambiar casi su diseño."),
    ("🪼", "Océano", "ocean", "Las medusas Turritopsis son biológicamente inmortales",
     "Pueden revertir su ciclo vital y empezar de nuevo. En teoría, podrían vivir para siempre... si no se las comen o enferman."),
    ("🪸", "Océano", "ocean", "La Gran Barrera de Coral es visible desde el espacio",
     "Es la estructura viva más grande del planeta: 2,300 km de largo, formada por miles de millones de pólipos diminutos. Lleva creciendo 20,000 años."),
    ("🐬", "Océano", "ocean", "Los delfines tienen 'nombres' propios",
     "Cada delfín tiene un silbido único que lo identifica. Otros delfines lo usan para 'llamarlo', como un nombre humano."),
    ("🌊", "Océano", "ocean", "El 95% del océano está inexplorado",
     "Conocemos mejor la superficie de Marte que el fondo del mar. La fosa de Mariana (11 km) fue visitada por primera vez en 1960."),
    ("🦀", "Océano", "ocean", "Los cangrejos ermitaños hacen fila para intercambiar conchas",
     "Cuando encuentran una concha grande vacía, se organizan por tamaño y la pasan al siguiente que calce. Es una verdadera cadena de trueque."),
    ("🐠", "Océano", "ocean", "El pez payaso puede cambiar de sexo",
     "Si la hembra dominante muere, el macho más grande se convierte en hembra. Son hermafroditas secuenciales: nacen machos, algunos se vuelven hembras."),
    # ===== GEOGRAFÍA (6) =====
    ("🏔️", "Geografía", "geografia", "El Everest crece 4 mm cada año",
     "La colisión de placas tectónicas entre India y Asia empuja la montaña hacia arriba. Hace 50 millones de años esta zona estaba bajo el mar."),
    ("🗽", "Geografía", "geografia", "La Estatua de la Libertad fue un regalo francés",
     "Inaugurada en 1886, fue diseñada por Frédéric Auguste Bartholdi con estructura interna de Gustave Eiffel. Su color verde es por la oxidación natural del cobre."),
    ("🏜️", "Geografía", "geografia", "El desierto del Sahara fue un bosque hace 6,000 años",
     "Hubo monzones que lo cubrieron de vegetación y lagos. El cambio en la órbita terrestre desplazó las lluvias y lo convirtió en desierto."),
    ("🌋", "Geografía", "geografia", "Rusia tiene 11 zonas horarias",
     "Es el país más grande del mundo: 17 millones de km². Cuando amanece en Moscú, en Vladivostok ya está oscureciendo."),
    ("❄️", "Geografía", "geografia", "La Antártida es el desierto más grande del mundo",
     "Aunque está cubierta de hielo, recibe menos de 200 mm de precipitación anual. Es técnicamente un desierto polar más seco que el Sahara."),
    ("🏝️", "Geografía", "geografia", "Islandia crece 2 cm al año",
     "Está sobre la dorsal mesoatlántica: Norteamérica y Eurasia se separan, e Islandia se 'estira'. En 10M años será el doble de ancha."),
    # ===== CUERPO HUMANO (8) =====
    ("❤️", "Cuerpo humano", "cuerpo", "Tus vasos sanguíneos darían 2.5 vueltas a la Tierra",
     "Puestos en línea miden ~100,000 km. El corazón bombea 7,500 litros de sangre al día a través de esta red, sin parar ni un segundo."),
    ("👁️", "Cuerpo humano", "cuerpo", "El ojo humano distingue 10 millones de colores",
     "Tenemos ~6 millones de conos (color) y 120 millones de bastones (luz). Las mujeres, en promedio, distinguen más tonos que los hombres."),
    ("🦷", "Cuerpo humano", "cuerpo", "El esmalte dental es más duro que el acero",
     "Es la sustancia más dura del cuerpo humano: 5 en la escala Mohs. Pero no puede regenerarse, así que cuidarlo es para toda la vida."),
    ("🦴", "Cuerpo humano", "cuerpo", "El fémur soporta 30x tu peso",
     "El hueso más largo y fuerte del cuerpo. En compresión puede aguantar hasta 1,800 kg. Es más resistente que el hormigón armado, peso por peso."),
    ("🫁", "Cuerpo humano", "cuerpo", "Los alvéolos pulmonares tendrían 70 m²",
     "Si extendieras todos los sacos de aire de tus pulmones, cubrirían la mitad de una cancha de tenis. Es el área de intercambio de oxígeno."),
    ("🧠", "Cuerpo humano", "cuerpo", "El cerebro genera 20 W de potencia",
     "Suficiente para encender una bombilla de bajo consumo. Funciona con la misma energía que un pequeño portátil, pero procesa billones de señales por segundo."),
    ("👂", "Cuerpo humano", "cuerpo", "El oído nunca deja de escuchar",
     "Aunque duermas, el cerebro sigue procesando sonidos. Por eso el ruido interrumpe el sueño, pero los sonidos familiares pueden no hacerlo."),
    ("👅", "Cuerpo humano", "cuerpo", "Tu lengua tiene 10,000 papilas gustativas",
     "Pero se renuevan cada 10-14 días. Por eso una quemadura en la lengua se cura rápido. Cada papila tiene 50-100 células receptoras de sabor."),
    # ===== TECNOLOGÍA (8) =====
    ("💻", "Tecnología", "tecnologia", "El primer SMS decía 'Merry Christmas'",
     "Neil Papworth lo envió el 3 de diciembre de 1992 desde un PC a un móvil Orbitel 901. Nadie imaginaba que iniciaría una revolución de mensajería."),
    ("🚀", "Tecnología", "tecnologia", "Tu smartphone es más potente que el Apollo 11",
     "El iPhone moderno tiene ~100,000x la memoria y procesadores millones de veces más rápidos. El Apollo 11 llevó al hombre a la Luna con apenas 4 KB de RAM."),
    ("🌐", "Tecnología", "tecnologia", "La primera webcam vigilaba una cafetera",
     "En la Universidad de Cambridge (1991) querían saber si quedaba café sin subir las escaleras. Conectaron una cámara y nació la primera webcam del mundo."),
    ("💾", "Tecnología", "tecnologia", "El primer disco duro pesaba 1 tonelada",
     "IBM RAMAC (1956) almacenaba 5 MB y ocupaba el tamaño de dos armarios. Hoy un microSD del tamaño de una uña guarda 1 TB: 200,000 veces más."),
    ("📱", "Tecnología", "tecnologia", "Hay más móviles que personas en la Tierra",
     "8,500 millones de líneas móviles vs 8,000 millones de personas. El país con más móviles por habitante es Hong Kong (2.4 por persona)."),
    ("🎮", "Tecnología", "tecnologia", "El primer joystick era un bote de jabón",
     "Ralph Baer, inventor de la consola Magnavox Odyssey (1972), usó un bote vacío de jabón para crear el primer control de videojuegos casero."),
    ("🛰️", "Tecnología", "tecnologia", "El GPS se basa en la teoría de Einstein",
     "Sin la corrección de la relatividad (tiempo corre más lento en órbita), el GPS fallaría 10 km por día. Einstein hace que Google Maps funcione."),
    ("🔧", "Tecnología", "tecnologia", "El primer programador fue mujer",
     "Ada Lovelace escribió el primer algoritmo en 1843, para la 'máquina analítica' de Babbage que nunca se construyó. Previó que las computadoras harían más que cálculos."),
    # ===== ARTE Y MÚSICA (6) =====
    ("🎨", "Arte", "arte", "Van Gogh vendió un solo cuadro en vida",
     "'La viña roja' se vendió por 400 francos en 1890, meses antes de su muerte. Hoy sus obras superan los 100 millones de dólares."),
    ("🎵", "Música", "musica", "Mozart compuso a los 5 años",
     "Su primera pieza, un minueto para clavecín, la escribió a los 5 años. A los 12 ya había compuesto su primera ópera. Murió a los 35 con más de 600 obras."),
    ("🖼️", "Arte", "arte", "La Mona Lisa no tenía cejas",
     "Análisis digitales muestran que Da Vinci sí pintó cejas, pero se borraron por restauraciones agresivas. En el siglo XVI se usaban cejas depiladas como símbolo de belleza."),
    ("🎸", "Música", "musica", "La guitarra eléctrica se inventó en 1932",
     "Gibson lanzó la ES-150 con pickup magnético. Hasta entonces, las guitarras no se escuchaban en orquestas. Esto cambió el jazz, el blues y el rock para siempre."),
    ("🎼", "Música", "musica", "Beethoven compuso sordo",
     "Empezó a perder el oído a los 26 años. La 'Novena Sinfonía' la escribió completamente sordo. La dirigió sin escuchar una sola nota."),
    ("🗿", "Arte", "arte", "El David de Miguel Ángel mide 5.17 m",
     "Lo esculpió entre 1501 y 1504 a los 26 años, de un bloque de mármol abandonado por otros escultores. Tiene manos desproporcionadas para sugerir fuerza."),
    # ===== IDIOMAS Y LITERATURA (5) =====
    ("🗣️", "Idiomas", "idiomas", "Existen +7,000 idiomas en el mundo",
     "Pero el 40% está en peligro de extinción. El papamiento, el silbo gomero y el pirahã son algunos de los más fascinantes del planeta."),
    ("📚", "Literatura", "literatura", "El Quijote se tradujo a +50 idiomas",
     "Publicada en 1605, es la segunda obra más traducida de la historia después de la Biblia. Cervantes murió el mismo día que Shakespeare: 23 de abril de 1616."),
    ("🔤", "Idiomas", "idiomas", "El coreano tiene un alfabeto científico",
     "Hangul fue creado en 1443 por el rey Sejong. Cada letra representa la forma que hace la boca al pronunciarla. Es considerado el alfabeto más lógico del mundo."),
    ("📖", "Literatura", "literatura", "El libro más largo del mundo tiene 17,000 páginas",
     "'À la recherche du temps perdu' de Proust. En español son 3,000 páginas. Tiene una sola frase de 958 palabras sobre un dormitorio."),
    ("🌍", "Idiomas", "idiomas", "El esperanto se creó para unir el mundo",
     "L.L. Zamenhof lo publicó en 1887 como lengua neutral internacional. Hoy lo hablan ~2 millones de personas, pero nunca desbancó al inglés."),
    # ===== INVENTOS (5) =====
    ("💡", "Inventos", "inventos", "La bombilla led dura 25,000 horas",
     "Frente a las 1,200 de una incandescente. El primer LED visible lo creó Nick Holonyak en 1962; hoy iluminan el 60% de los hogares del mundo."),
    ("🔥", "Inventos", "inventos", "El fuego se 'inventó' hace 1 millón de años",
     "El Homo erectus ya lo controlaba en África. Cambió la evolución humana: permitió cocinar (más calorías para el cerebro) y extender la vida social nocturna."),
    ("⚙️", "Inventos", "inventos", "La rueda se inventó para cerámica, no para transporte",
     "Los primeros registros de ruedas son del 3,500 a.C. en Mesopotamia, usadas para hacer vasijas. Tuvieron que pasar 300 años para ponerlas en carros."),
    ("✏️", "Inventos", "inventos", "El lápiz se inventó tras un descubrimiento de grafito",
     "En 1564 se encontró un yacimiento gigante en Inglaterra. Se envolvía grafito en cuerda para escribir. La goma de borrar vino 200 años después."),
    ("📷", "Inventos", "inventos", "La primera foto tomó 8 horas",
     "Joseph Niépce la capturó en 1826 desde su ventana. La emulsión necesitaba 8 horas de exposición. Hoy un sensor captura una imagen en 1/8,000 de segundo."),
    # ===== CULTURA Y MITOLOGÍA (6) =====
    ("🎭", "Cultura", "cultura", "Shakespeare inventó +1,700 palabras",
     "Palabras como 'lonely', 'bedroom' y 'eyeball' aparecieron por primera vez en sus obras. Su vocabulario superaba los 29,000 términos."),
    ("⚡", "Mitología", "mitologia", "Zeus no siempre gobernó el Olimpo",
     "En la mitología griega, derrocó a su padre Crono, quien a su vez había derrocado a Urano. La guerra de los Titanes duró 10 años antes de su victoria."),
    ("🐉", "Mitología", "mitologia", "El dragón existe en casi todas las culturas",
     "Aparece en mitos chinos, europeos, mesoamericanos y africanos. Probablemente nació del miedo instintivo a serpientes, grandes felinos y aves rapaces combinados."),
    ("👑", "Mitología", "mitologia", "Anubis es el dios más antiguo de Egipto",
     "Antes de Osiris, Anubis era el dios principal del inframundo. Se representaba con cabeza de chacal por ser estos animales carroñeros que merodeaban las tumbas."),
    ("🧞", "Mitología", "mitologia", "Aladín era originalmente chino",
     "En 'Las mil y una noches', la historia de Aladín se ambienta en 'China' (un país imaginario musulmán). Disney lo cambió a Agrabah, ciudad ficticia árabe."),
    ("🪶", "Mitología", "mitologia", "Quetzalcóatl era un dios con forma de serpiente emplumada",
     "Para los aztecas, era el dios de la vida, la luz, el viento y la sabiduría. Su nombre combina 'quetzal' (pájaro sagrado) y 'cóatl' (serpiente)."),
    # ===== DEPORTE Y VIDEOJUEGOS (5) =====
    ("🏓", "Videojuegos", "videojuegos", "El primer videojuego es de 1958",
     "'Tennis for Two' fue creado por el físico William Higinbotham en un osciloscopio. Se creó para entretener a los visitantes de un laboratorio."),
    ("🕹️", "Videojuegos", "videojuegos", "Pac-Man tenía nombre japonés",
     "Se llamaba 'Puck-Man' (por 'paku', comer). En EE.UU. lo cambiaron a Pac-Man para evitar que los graffiteros convirtieran la P en una F en los arcades."),
    ("🏀", "Deporte", "deporte", "El basketball se inventó en 1891",
     "James Naismith usó canastas de melocotones y un balón de fútbol. El primer partido terminó 1-0. Hoy se juega en más de 200 países."),
    ("⚽", "Deporte", "deporte", "El fútbol se juega en 200+ países",
     "Es el deporte más popular del mundo: más de 250 millones de jugadores activos. La FIFA tiene más federaciones miembro que la ONU tiene países."),
    ("🏆", "Deporte", "deporte", "Los Juegos Olímpicos tienen 2,700 años",
     "Se celebraban en Olimpia desde el 776 a.C. hasta que el emperador Teodosio los prohibió en el 393 d.C. Fueron resucitados en 1896 por Pierre de Coubertin."),
    # ===== MATEMÁTICAS (4) =====
    ("🔢", "Matemáticas", "tecnologia", "El cero se inventó en India",
     "Brahmagupta lo definió formalmente en el 628 d.C. Los mayas también lo usaron, pero sin concepto de 'negativo'. Sin cero, no habría informática moderna."),
    ("♾️", "Matemáticas", "tecnologia", "Algunos infinitos son más grandes que otros",
     "Georg Cantor demostró en 1874 que el infinito de los decimales es mayor que el de los enteros. Hay infinitos tamaños de infinito."),
    ("📐", "Matemáticas", "tecnologia", "Pi tiene 100 trillones de decimales calculados",
     "En 2024 se alcanzaron 100,000,000,000,000 de decimales. Pero 39 decimales bastan para calcular la circunferencia del universo con precisión atómica."),
    ("🎲", "Matemáticas", "tecnologia", "La probabilidad de sacar 6 y 6 con dos dados es 1/36",
     "Pero la gente cree que '7' sale más. Y es cierto: el 7 tiene 6 combinaciones de 36, frente a 1 del 2 o del 12. Es el resultado más probable."),
    # ===== COMIDA (4) =====
    ("🍫", "Comida", "inventos", "El chocolate fue dinero durante siglos",
     "Los aztecas usaban granos de cacao como moneda: 1 conejo costaba 10 granos. Y pagaban impuestos en cacao. Para ellos era más valioso que el oro."),
    ("🍕", "Comida", "cultura", "La pizza Margherita imita la bandera italiana",
     "Creada en 1889 para la reina Margherita: rojo (tomate), blanco (mozzarella) y verde (albahaca). Se ha convertido en la comida más global de la historia."),
    ("🍯", "Comida", "naturaleza", "La miel nunca se echa a perder",
     "En tumbas egipcias de 3,000 años se encontró miel comestible. Su baja humedad y pH ácido impiden bacterias. Es el único alimento que no caduca."),
    ("🌶️", "Comida", "naturaleza", "El picante no es un sabor, es dolor",
     "La capsaicina activa los receptores de dolor, no los de sabor. Tu cuerpo reacciona como si te quemaras. Por eso sudas: el cerebro intenta enfriarte."),
    # ===== CINE (4) =====
    ("🎬", "Cine", "cultura", "La primera película es de 1895",
     "Los hermanos Lumière proyectaron 'La salida de los obreros de la fábrica'. El público gritó cuando vio un tren acercándose en pantalla."),
    ("🧛", "Cine", "cultura", "Drácula se basó en un príncipe real",
     "Vlad III de Valaquia, 'El Empalador' (siglo XV), inspiró a Bram Stoker. Su apodo 'Drăculea' significa 'hijo del dragón' en rumano."),
    ("🎥", "Cine", "cultura", "El primer Oscar se entregó en 1929",
     "Duró 15 minutos y solo asistieron 270 personas. Las entradas costaban 5 dólares. Hoy la ceremonia dura más de 3 horas y se ve en 200 países."),
    ("🧊", "Cine", "cultura", "Titanic costó más que el barco real",
     "La película de 1997 costó 200M USD. El Titanic original costó 7.5M USD de la época (unos 200M ajustados). James Cameron replicó el barco a escala 90%."),
    # ===== CLIMA Y ATMÓSFERA (4) =====
    ("🌈", "Clima", "ciencia", "Cada arcoíris es único para cada observador",
     "No existen dos personas viendo el mismo arcoíris. El ángulo depende de la posición exacta de tus ojos respecto a las gotas de agua."),
    ("☁️", "Clima", "ciencia", "Una nube pesa 500 toneladas",
     "Una nube cumulus típica (1 km de diámetro) contiene 500,000 kg de agua. Flota porque el aire caliente bajo ella es aún más ligero que la nube."),
    ("🌫️", "Clima", "ciencia", "El récord de temperatura son 56.7°C",
     "En el Valle de la Muerte, California (10 julio 1913). La más baja: -89.2°C en la base Vostok, Antártida (1983). Una diferencia de 146°C en el mismo planeta."),
    ("⛈️", "Clima", "ciencia", "Un huracán libera energía como 10,000 bombas nucleares",
     "Pero disipada en horas y sobre un área enorme. La energía viene del calor latente del vapor de agua tropical al condensarse."),
    # ===== MÁS DATOS CURIOSOS VARIADOS =====
    ("🦕", "Historia", "historia", "Los dinosaurios reinaron 165 millones de años",
     "El Homo sapiens existe desde hace 300,000 años. Si la historia de la Tierra fuera un día, los dinosaurios habrían reinado 41 minutos; nosotros solo 0.6 segundos."),
    ("🌙", "Espacio", "espacio", "La Luna tiene 'temblores'",
     "Los Apollo detectaron moonquakes en 1969. Son causados por las mareas gravitacionales de la Tierra. Pueden durar hasta una hora porque la Luna no tiene agua que amortigüe."),
    ("🌊", "Geografía", "geografia", "El río más largo está bajo el Amazonas",
     "El río Hamza, descubierto en 2011, fluye a 4 km de profundidad bajo el Amazonas. Mide ~6,000 km, igual o más que su hermano superficial."),
    ("🦅", "Naturaleza", "naturaleza", "Un águila puede ver un conejo a 3 km",
     "Su agudeza visual es 8x mejor que la humana. Tiene dos foveas (puntos de enfoque) en cada ojo, permitiéndole ver adelante y a los lados a la vez."),
    ("🐌", "Ciencia", "ciencia", "La luz es más lenta en el agua",
     "En el vacío viaja a 300,000 km/s. En agua, a 225,000 km/s. En vidrio, a 200,000 km/s. Esto es lo que permite que los lentes y los ojos funcionen."),
    ("🎆", "Ciencia", "ciencia", "El fuego no tiene sombra",
     "Porque es luz en sí mismo. Solo proyecta sombra si lo atraviesa un material denso (humo o gas caliente) que refracta la luz parcialmente."),
    ("🪐", "Espacio", "espacio", "Júpiter tiene 95 lunas conocidas",
     "Cuatro de ellas (Galileanas: Ío, Europa, Ganímedes, Calixto) son del tamaño de planetas. Europa tiene océano bajo su hielo, candidato a vida extraterrestre."),
    ("🦠", "Ciencia", "ciencia", "Tu cuerpo tiene más bacterias que células humanas",
     "Ratio aproximado: 1.3 bacterias por cada célula humana. La mayoría son beneficiosas y viven en tu intestino, pesando en total unos 200 gramos."),
    ("🐛", "Naturaleza", "naturaleza", "Los gusanos de seda son insectos domesticados",
     "Bombyx mori ya no existe en estado silvestre. Lleva 5,000 años siendo criado por humanos para producir seda. Es el segundo animal domesticado tras el perro."),
    ("🧊", "Geografía", "geografia", "El 69% del agua dulce está en glaciares",
     "Solo el 2.5% del agua del planeta es dulce. De esa, 69% está congelada en polos y glaciares, 30% bajo tierra, y solo 1% en ríos y lagos accesibles."),
    ("👑", "Historia", "historia", "El rey más joven fue coronado antes de nacer",
     "Shapur II de Persia (309 d.C.) fue coronado en el vientre de su madre. Reinó 70 años y expandió el Imperio Sasánida."),
    ("🗼", "Geografía", "geografia", "La Torre de Pisa se inclinó por error",
     "Se construyó sobre suelo blando en 1173. Tras siglos de inclinación progresiva, en 2008 se estabilizó con obras de ingeniería. Sigue inclinada 4 grados, a propósito."),
    ("🦈", "Océano", "ocean", "El tiburón blanco huele 1 gota de sangre en 100L de agua",
     "Su olfato es tan fino que detecta concentraciones de 1 parte por millón. Pero los tiburones no atacan por la sangre como en las películas: prefieren peces."),
    ("🪨", "Espacio", "espacio", "El meteorito más grande pesa 60 toneladas",
     "Hoba (Namibia, 1920) mide 3x3x1 metros y nunca se movió tras caer. Cayó hace 80,000 años. Es el objeto natural más grande de origen extraterrestre en la Tierra."),
    ("🌷", "Naturaleza", "naturaleza", "Los tulipanes causaron la primera burbuja financiera",
     "En Holanda (1637) un bulbo de tulipán llegó a costar 10x el salario anual de un artesano. La 'Tulipomanía' estalló en febrero: los precios cayeron 99% en días."),
    ("🦜", "Naturaleza", "naturaleza", "Un loro puede aprender 1,000 palabras",
     "El récord lo tiene un loro gris africano llamado Puck (Guinness 1995): 1,728 palabras. Algunos loros entienden conceptos como color, forma y cantidad."),
    ("🐎", "Historia", "historia", "Los caballos regresaron a América en 1493",
     "Colón los trajo en su segundo viaje. Curiosamente, los caballos EVOLUCIONARON en América hace 50M años, pero se extinguieron allí hace 10,000."),
    ("🌿", "Naturaleza", "naturaleza", "Los árboles se 'comunican' entre sí",
     "Por micelios de hongos en sus raíces (Wood Wide Web), pueden enviarse señales químicas, nutrientes y avisos de plagas. Una sola red puede conectar cientos de árboles."),
    ("🐙", "Océano", "ocean", "Los pulpos usan herramientas",
     "El pulpo de coco recoge conchas vacías y las usa como refugio transportable. Es uno de los pocos animales no mamíferos que demuestra uso de herramientas."),
    ("🧊", "Ciencia", "ciencia", "El hielo se forma en 17 estados distintos",
     "El hielo común es 'hielo Ih'. Pero existen al menos 17 fases sólidas del agua con estructuras cristalinas distintas, dependiendo de presión y temperatura."),
    ("🐘", "Naturaleza", "naturaleza", "Los elefantes reconocen su reflejo",
     "Solo humanos, grandes monos, delfines, orcas y elefantes pasan el 'test del espejo'. Se reconocen a sí mismos y se inspeccionan marcas pintadas en su cuerpo."),
    ("🌏", "Geografía", "geografia", "El nombre 'América' viene de un italiano",
     "Américo Vespucio, navegante florentino, fue el primero en darse cuenta de que las tierras de Colón eran un continente nuevo, no Asia. El cartógrafo Waldseemüller lo nombró así en 1507."),
    ("🦎", "Naturaleza", "naturaleza", "Algunos lagartos caminan sobre el agua",
     "El basilisco verde corre sobre el agua hasta 4.5 metros gracias a sus pies con escamas. Mueve las patas tan rápido que crea una 'burbuja' de aire que lo sostiene."),
    ("🌋", "Geografía", "geografia", "El volcán más activo está en Italia",
     "El Stromboli lleva 2,000 años en erupción casi continua. Los romanos lo llamaban 'el faro del Mediterráneo' por su brillo nocturno constante."),
    ("🌊", "Ciencia", "ciencia", "El agua es un 'anómalo' del universo",
     "Es la única sustancia que se expande al congelarse (por eso el hielo flota). Si no fuera así, los lagos se congelarían desde el fondo y la vida acuática moriría."),
    ("🦉", "Naturaleza", "naturaleza", "Los búhos no pueden mover los ojos",
     "Sus ojos son tubulares, fijos en las órbitas. Por eso giran la cabeza hasta 270°. Tienen 14 vértebras cervicales (nosotros solo 7), permitiendo ese giro extremo."),
    ("🪨", "Geografía", "geografia", "Australia es más ancha que la Luna",
     "Diámetro lunar: 3,474 km. Anchura de Australia (este-oeste): 4,000 km. Pero la Luna tiene 5x la superficie del continente australiano."),
    ("🐝", "Ciencia", "ciencia", "Las abejas entienden el concepto de cero",
     "En 2018 se demostró que las abejas pueden ser entrenadas para reconocer 'cero' como menor que 1. Es una capacidad matemática que creíamos exclusiva de primates y loros."),
    ("🗺️", "Geografía", "geografia", "El lugar más remoto de la Tierra es la Isla Bouvet",
     "Está en el Atlántico Sur, a 1,700 km de la tierra habitada más cercana. El 93% de su superficie está cubierta por un glaciar. Es territorio noruego."),
    ("🪲", "Naturaleza", "naturaleza", "Los escarabajos son el 25% de todas las especies",
     "Se conocen 400,000 especies de escarabajos. J.R.S. Haldane dijo: 'El Creador debió tener una pasión desmesurada por los escarabajos'."),
    ("🌋", "Ciencia", "ciencia", "El cristal más antiguo tiene 4,400 millones de años",
     "Un zircon hallado en Australia occidental. Es la sustancia terrestre más antigua conocida. La Tierra misma se formó hace 4,540 millones de años."),
    ("🐢", "Naturaleza", "naturaleza", "Las tortugas pueden vivir más de 190 años",
     "Jonathan, una tortuga gigante de las Seychelles nacida en 1832, es el animal terrestre vivo más viejo conocido. Tiene 191+ años y vive en Santa Elena."),
]

# Verificar unicidad de títulos
seen_titles = set()
unique = []
for f in FACTS:
    if f[3] not in seen_titles:
        seen_titles.add(f[3])
        unique.append(f)
FACTS = unique

print(f"Total de facts únicos: {len(FACTS)}")

# Mapa de colores
COLORS = {
    "ciencia": "#00E5FF",
    "historia": "#FFEA00",
    "cultura": "#FF4D6D",
    "naturaleza": "#39FF14",
    "geografia": "#7DD3FC",
    "videojuegos": "#a855f7",
    "deporte": "#f97316",
    "espacio": "#C084FC",
    "arte": "#F472B6",
    "musica": "#34D399",
    "tecnologia": "#60A5FA",
    "idiomas": "#FBBF24",
    "ocean": "#22D3EE",
    "cuerpo": "#FB7185",
    "inventos": "#A78BFA",
    "literatura": "#FCD34D",
    "mitologia": "#F87171",
    "mariposas": "#F59E0B",
}

# Generar archivo TypeScript
out = """// =====================================================================
// Banco de datos curiosos para el welcome-screen de Trivials Wars
// 100+ facts en categorías diversas, generados por scripts/gen-facts.py
// =====================================================================

export interface FunFact {
  id: number
  emoji: string
  category: string
  color: string
  title: string
  description: string
}

// Mapa de colores por categoría (18 categorías)
export const FACT_COLOR: Record<string, string> = {
  ciencia: "#00E5FF",
  historia: "#FFEA00",
  cultura: "#FF4D6D",
  naturaleza: "#39FF14",
  geografia: "#7DD3FC",
  videojuegos: "#a855f7",
  deporte: "#f97316",
  espacio: "#C084FC",
  arte: "#F472B6",
  musica: "#34D399",
  tecnologia: "#60A5FA",
  idiomas: "#FBBF24",
  ocean: "#22D3EE",
  cuerpo: "#FB7185",
  inventos: "#A78BFA",
  literatura: "#FCD34D",
  mitologia: "#F87171",
  mariposas: "#F59E0B",
}

export const FUN_FACTS: FunFact[] = [
"""

for i, (emoji, category, color_key, title, desc) in enumerate(FACTS, 1):
    color = COLORS[color_key]
    title_e = title.replace('"', '\\"')
    desc_e = desc.replace('"', '\\"')
    out += f'  {{\n    id: {i},\n    emoji: "{emoji}",\n    category: "{category}",\n    color: "{color}",\n    title: "{title_e}",\n    description: "{desc_e}",\n  }},\n'

out += "]\n"

# Escribir archivo
target = "/home/z/my-project/src/lib/facts-data.ts"
with open(target, "w", encoding="utf-8") as f:
    f.write(out)

print(f"Escrito: {target}")
print(f"Total facts: {len(FACTS)}")
